### ISSUE TITLE
Map website not working

### ISSUE THREAD

**Issue by nmills3** [webbukkit/dynmap#3710] opened 2022-03-10 07:54 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** So last yesterday I pregenerated my world and then let dynmap render the 2d and 3d maps over the day before playing with some friends, that night everything working fine and the map was working as expected. After we finished playing i changed the config to pause the full render when 1 player or more was online and then restarted the server and it was still working. Then i woke up this morning and went to check the map to see if it had rendered anymore and now the webserver just isn't working. The page just hangs on loading forever

* **Dynmap Version:** Dynmap-3.4-beta-2-spigot
* **Server Version:** spigot-1.18.2 (server auto updates to the latest release on startup so whatever the newest is)
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/zC9wPAb0)
* **Server Host (if applicable):** Self hosted in a docker container on top of unraid
* **Pastebin of crashlogs or other relevant logs:** no crashes
* **Other Relevant Data/Screenshots:** other plugins include CoreProtect21.0 DeathLocation and FastChunkPregenerator
* **Steps to Replicate:** Unsure as issue happened overnight

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment] 2022-03-10 07:55
check the latest.log for errors, the webserver not there is indicative of a configuration problem.

**Comment by nmills3** [comment] 2022-03-10 07:57
here's the log from the last time i started and then stopped the server. There are dynmap errors around sqlite but only when shutting down the server it seems https://pastebin.com/xmnfReK2

**Comment by JurgenKuyper** [comment] 2022-03-10 08:03
looks like either your db is not respoonding or the db is corrupt

**Comment by nmills3** [comment] 2022-03-10 08:04
Well i don't think it can be the first one as it's a local sqlite db so i guess it's corrupt. is there any way i can fix that without regenerating the map?

**Comment by nmills3** [comment] 2022-03-10 08:06
also i'm not sure if this is really worth anything but sqlite db browser says the db passes integrity checks

**Comment by generrosity** [comment] 2022-03-10 09:18
Quick answer no - you can wipe the database and start a "radiusrender" immediately, and continue diagnosing if its a SQL or hosting problem. Without knowing your root cause, getting back working and figuring it out might be your highest concern.

Its possible the DB has configuration itself that might be causing issues ... there is a reference to 'waittimeout' in [one place](https://discord.com/channels/722722769950998560/722723942111903765/943227505651900457), and potentially you might get 'sql write error' or similar useful error when doing radiusrender (such as files are too large, too many, timeouts, or communication inconsistancies). Hopefully its just a one-off dirty crash??

But I would suggest to start small, and potentially take a snapshot you can roll back to as part of your testing.

**Comment by nmills3** [comment] 2022-03-10 09:36
for now i'm just going to switch back to file tree storage. Generally a prefer sqlite because if i want to move the server it's faster to copy 1 giant sqlite db that it is to copy thousands of small image files. But given that the tree can't really be corrupted i'm going to go with that

**Comment by generrosity** [comment] 2022-03-17 01:02
Cool :) Closing for now.  Unknown root cause severely breaking SQL data.

**Closed as completed by generrosity** 2022-03-17 01:02 UTC
Labels: Answered, Support Question
