### ISSUE TITLE
Concrete not rendering

### ISSUE THREAD

**Issue by MrWonka** [webbukkit/dynmap#2133] opened 2017-08-19 02:55 UTC
Concrete, (or at least black concrete) doesn't render at all on dynamap V2.5

**Comment by Rasor1911** [comment] 2017-08-19 15:14
#2120

**Comment by Pangamma** [comment] 2018-01-04 18:50
Please fix this.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 17:08
Duplicate of #2120

**Closed by FedUpWith-Tech** 2020-07-28 17:08 UTC
Labels: Duplicate
