### ISSUE TITLE
Map not rendering chunks properly

### ISSUE THREAD

**Issue by 1AndOnlyPika** [webbukkit/dynmap#2788] opened 2020-02-11 21:22 UTC
There are black chunks around but if i tp to those chunks its already generated. Heres my map: http://pikasmp.live/

**Comment by Synt3x** [comment] 2020-02-11 21:38
- Are you sure that the chunks is generated?
- Did you pre generate the chunks with world border?
- If the map is pre generated, you can always run a full render of the map. I think the command is /dynmap fullrender. You can find the command if you type /dynmap as op.

**Comment by 1AndOnlyPika** [comment] 2020-02-11 21:40
> * Are you sure that the chunks is generated?
> * Did you pre-generate the chunks with world boarder?
> * If the map is pre-generated you can always run a full render of the map. Type /dynmap and you will see all available commands. I think its dynmap fullrender.

Yes, it is pregenerated with worldborder. everything else that was loaded generated fine. excpet for a few circles and patches.

Is there like a way to render only unrendered tiles?

**Comment by Synt3x** [comment] 2020-02-11 21:42
I'm not sure. I would just do a fullrender and go to bed. :)

**Comment by 1AndOnlyPika** [comment] 2020-02-11 21:45
> I'm not sure. I would just do a fullrender and go to bed. :)

Thats what I did and thats what came out.

**Comment by Synt3x** [comment] 2020-02-11 21:52
I guess your server console is still getting a lot of rendering messages from dynmap? Seems like your 3d view isn't fully rendered yet (not even close). When Dynmap stop spamming the console with rendering message and you still have black boxes, I would back here. :)

**Comment by 1AndOnlyPika** [comment] 2020-02-11 21:56
kk

**Comment by Synt3x** [comment] 2020-06-20 03:01
@1AndOnlyPika did your issue got solved?

**Comment by FedUpWith-Tech** [comment] 2020-07-31 18:52
Duplicate of #2485

**Closed as completed** 2021-12-17 18:31 UTC
Labels: Duplicate
