### ISSUE TITLE
Dynmap not rendering terrain generated with Terrain Control

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#1921] opened 2016-03-24 21:04 UTC
- git-Spigot-f04e043-52c7fc0 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
- dynmap v2.3-SNAPSHOT-1132
- TerrainControl v2.8.0-SNAPSHOT

Dynmap does not render anything but there are also no console errors.

**Comment by gbl** [comment] 2016-03-25 12:01
Duplicate of https://github.com/webbukkit/dynmap/issues/1908 and https://github.com/webbukkit/dynmap/issues/1914. Constantly opening new threads won't make things go any faster.

**Comment by bloggy** [comment] 2016-03-31 18:37
Sorry for that, but it's a long time since these bugs have been reported and there's no fix, yet. We are unable to use dynmap at all because of the incompatibility with terrain control. Any ETA on this?

**Comment by gbl** [comment] 2016-03-31 22:44
If you really want to, you can try my personal, inofficial bug fix at 
http://minecraft.guntram.de/dynmap-2.3-alpha-1-gbl.jar. Please note that 
this is a completely unofficial version for which there is no support 
and which should be replaced with a working official version ASAP. But, 
it worked for me on a test server, with a TC world and a EWG world.


Am 31.03.2016 um 20:37 schrieb bloggy:

**Comment by bloggy** [comment] 2016-04-01 09:44
I am not familiar with java, sorry! :-( Will this be fixed in the next version of dynmap? And if so, when do you think will you release it? Thanks for your efforts!

**Comment by bloggy** [comment] 2016-04-01 12:19
Tested and does not work for me.
Maybe because my biomes have a ReplaceToBiomeName value?

**Comment by gbl** [comment] 2016-04-01 15:54
I'm not the maker of dynmap, sorry. I don't even claim to understand much of the code. Only thing i can say is i got the java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.* exceptions described in #1908 and #1914, and when i wrote the patch i copied to #1908, and patched the jar file with it, dynmap started working for me, with an EWG world and a TC world as well; see http://minecraft.guntram.de/dynmap-worldgen/. This patched jar file is what i put up for download.  If that version doesn't work for you, i'm afraid i won't be able to help.

**Comment by mikeprimm** [comment] 2016-04-01 22:14
If you are using custom biomes, you will trip on a bug in a standard CB API, likely caused by TC not updating the standard Biome enum within CB properly.  This is ultimately a bug in CraftBukkit/Spigot (or, an incompatibility between TC and them) - the call that is failing is a standard CB API call - nothing funky on our part: it's not bypassing API or anything - just standard ChunkSnapshot stuff. In any case, catching the exception is an option to work-around the bug (so long as you don't want biome information in the render, like grass color shading and the like), but the true fix is either in CB or in TC (probably the later, since it is the one hacking CB with custom biomes).  I can make it not break, but I cannot 'fix' it, as the broken ChunkSnapshot.getBiome() call means we lose biome information (which will screw up grass, water, and leaf shading, among other things).

**Comment by Rasor1911** [comment] 2016-04-02 14:19
New build of dynmap fixes this problem, had the same issue with the biome bundle pack. It's fixed now.
https://github.com/webbukkit/dynmap/commit/27dc1d4a0b2a3e0d1048af208f4716a431795c5b

**Comment by mikeprimm** [comment] 2016-04-02 14:34
@Rasor1911 Cool - thanks for the verify!

Other folks: Give latest dynmap dev build a try - worked on a work-around last night, and I think it should be working now.

**Comment by bloggy** [comment] 2016-04-04 08:33
I can not find any new dev build. The latest I could find is: Dynmap v2.3-alpha-1 (and this version does not include the fix)

**Comment by bloggy** [comment] 2016-04-04 19:00
But NOW I have a new bug! 
Since updating to the latest dev build + terrain control this gets spammed in the console:

[WARN]: Ignoring unknown attribute 'generic.armorToughness'

**Comment by FedUpWith-Tech** [comment] 2020-07-28 18:26
Duplicate of #1908, fixed in later builds of TerrainControl

**Closed by FedUpWith-Tech** 2020-07-28 18:26 UTC
Labels: Duplicate, Not Dynmap related
