### ISSUE TITLE
1.15.2 fullrender isnt rendering anything

### ISSUE THREAD

**Issue by SokuNoWa** [webbukkit/dynmap#2772] opened 2020-01-28 17:41 UTC
hey guys I have done /wb fill and when i do fullrender is just says 100 tiles rendered and then says render complete. I am on 1.15, what is going on?

**Comment by 32Mikey** [comment] 2020-02-17 05:24
This is happening to me as well. I was told it's just a bug related to 1.15.2. You'll just have to wait for a fix. Hopefully, me replying will bump it up and get this issue some attention considering fully rendering a map is literally impossible if fullrender doesn't work.

**Comment by ghost** [comment] 2020-02-18 15:43
me too!

**Comment by mvcutter** [comment] 2020-02-23 01:12
Same!

**Comment by snail-world** [comment] 2020-02-29 00:51
Same!

**Comment by FedUpWith-Tech** [comment] 2020-07-31 18:45
Duplicate of #2760
fixed in a later version

**Closed as completed by FedUpWith-Tech** 2020-07-31 18:45 UTC
Labels: Bug, Fixed, Duplicate
