### ISSUE TITLE
Dynmap black holes at map

### ISSUE THREAD

**Issue by Theprim0** [webbukkit/dynmap#2664] opened 2019-11-24 09:55 UTC
Im running Dynmap without the internal web server, and have WorldBorder already filled (/wb fill), then dynam fullrender, and when the flat map is finished, there are still black holes in it. The black holes appears depending on the zoom you have on it.

Map: 8000x8000
Here a screenshot: https://imgur.com/avazih7

![mapa_bug](https://user-images.githubusercontent.com/13757003/69492948-db9cc380-0ea8-11ea-9875-315a8e1c5a83.png)

**Comment by ThybeVB** [comment] 2019-11-26 19:27
Having this issue aswell on my server
```
Paper 1.14.4 (226)
WorldBorder (1.9.10)
```
 Any help would be appreciated!

**Comment by Tsoccerguy3** [comment] 2019-12-01 00:34
you will need to run the server startup 1 time with this switch , spigot or paper --forceUpgrade

Update tp dynmap beta 6 and purge your maps , you have chunks in 1.14.4 and a older version . not a good idea to update the server on the fly . you will suffer a big TPS hit

**Comment by ThybeVB** [comment] 2019-12-15 19:17
I have done this, but to no avail

**Comment by PotcFdk** [comment] 2020-03-08 14:30
I'm not sure if this, or any of the similar issues related to this (#2485 #2755 and some others) are the issue that I'm observing, but your description fits my case best, so I decided to comment here.
I'm having similar issues:

![grafik](https://user-images.githubusercontent.com/3160048/76164643-d1998a80-6150-11ea-90ff-6a3298ee74e4.png)

For me, it's only on the surface map, only that one rectangular black outline, and the most interesting aspect, I assume: **it's only in the zoomed-out tiles**. When I zoom in to the lowest level, all the chunks show up fine:


![grafik](https://user-images.githubusercontent.com/3160048/76164675-0574b000-6151-11ea-8e20-0895cff7b6ff.png)

![grafik](https://user-images.githubusercontent.com/3160048/76164682-14f3f900-6151-11ea-8133-ddd68776a7cd.png)

My current assumption is that this was caused by me pausing the render and/or restarting the server while it was rendering (which took like two nights total).
Dynmap seems to have messed up some of the zoom-out tiles. They are not _forgotten tiles_: they exist - but they have transparent lines missing inside them:

![grafik](https://user-images.githubusercontent.com/3160048/76164827-40c3ae80-6152-11ea-9f6a-40c80679b732.png)

I tried to get it to re-generate the zoomout tiles using the [initial-zoomout-validate](https://github.com/webbukkit/dynmap/blob/v3.0/forge-1.12.2/src/main/resources/configuration.txt#L226) configuration, but it seems to do nothing.

When I manually delete the wrong zoomout tiles from the database and then run updaterender _exactly where the black spots are_, it seems to regenerate it correctly, at least sometimes. When the coordinates are not _exactly where the black spots are_, it will not fix the tiles.

Is there a proper way to regenerate only the zoom-out tiles?

Version is forge-1.12.2.

**Comment by Titaniumtown** [comment] 2020-10-06 19:31
I'm also having this issue! 1 year later lol.

**Comment by Aaron2550** [comment] 2020-11-14 11:12
I think i know where these square-like black rings come from. Example: https://stronghold.host/media/9LSzLd1u.png
When you use `/dynmap pause all` to pause a fullrender and then restart the server it will happen. Which is super annoying when its near the worldborder, because then a radius render from 0, 0 will prolly take as long as another fullrender...

Another Example where it was so big i coudnt fit it all on my screen. Where the ring gets thinner in the bottom right i tried two `/radiusrender 10000`s https://stronghold.host/media/5emRJVkk.png

**Comment by Inventatorul1** [comment] 2021-01-14 12:46
I have the same issue!

**Comment by AmkSoft** [comment] 2021-05-18 12:20
I have the same issue: fresh install Server+Clear Dynmap (no internal server)  + fullrender+ radiusrender. Map save to HTML/directory/file.
Random chunks are missing from the map (black holes) on different zoomlevels on different maps. 
Maximum zoom mostly to be ok (overworld), but not the Nether and in The End thwere are also random missing chunks in full zoom.
I have this issue for past year and on till now

Running Spigot: 1.16.5
Dynmap version:  core=3.1-457, plugin=3.1-457

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:25
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-12-17 18:25 UTC
Labels: Bug, Render Issues
