### ISSUE TITLE
Wood logs rendered incorrectly with texturepack

### ISSUE THREAD

**Issue by velnias75** [webbukkit/dynmap#3693] opened 2022-02-28 05:16 UTC
**Issue Description:** *Wood logs are rendered incorrectly with texture pack. The upside of the log is rendered, instead of the side*
*The texturepack uses CTM and works perfekt ingame.*

* **Dynmap Version:** *dynmap version 3.4-beta-1-752*
* **Server Version:** *Paper version git-Paper-215 (MC: 1.18.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/m22jjM8K*
* **Server Host (if applicable):** *Selfhosted*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack: https://drive.google.com/file/d/1rcx7iNq9qaqigEzgfws05Iy_0YN_-Aq6/view?usp=sharing*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

![Screenshot_20220228_055924](https://user-images.githubusercontent.com/4481414/155927831-86cb71b1-98ca-4af5-8321-08ed315ff961.png)

**Comment by generrosity** [comment] 2022-02-28 06:59
Dumb question - are you using a texture pack? There are a bunch of blocks I don't quite recognize

**Comment by velnias75** [comment] 2022-02-28 07:09
> Dumb question - are you using a texture pack? There are a bunch of blocks I don't quite recognize

Yes, I've linked it in the section **Other Relevant Data/Screenshots**

**Comment by JurgenKuyper** [comment] 2022-02-28 10:33
it could be the resource pack, as the default dynmap renders them correctly: https://dynmap-setup.jurgenmk.nl/?worldname=world_res&mapname=surfacesvh2&zoom=4&x=122&y=64&z=-111

**Comment by velnias75** [comment] 2022-02-28 10:41
Do they also render properly if they are connected, not single?

**Comment by JurgenKuyper** [comment] 2022-02-28 10:44
Affirmative: https://dynmap-setup.jurgenmk.nl/?worldname=world&mapname=surfaced&zoom=4&x=107&y=64&z=-111

**Comment by velnias75** [comment] 2022-02-28 10:47
So I need to check the texture pack.
The pack uses CTM a lot so please don't close this bug too early, since in the running game there are no problems.

**Comment by JurgenKuyper** [comment] 2022-02-28 10:49
only CTM V1.1 is supported, the ctm_compact type is not supported, maybe that is what is clashing with it?

**Comment by generrosity** [comment] 2022-02-28 18:23
yup - happy to keep open for a bit. unfortunately dynmap isn't coded with optifine (which is closed source)

hopefully, its just the one type of log affected, and so possibly an easy fix?

**Comment by velnias75** [comment] 2022-03-01 07:24
I've checked the texturepack for errors, but couldn't find any, **but** it seems that all types of log are affected.
I've attached the `*.properties`-files of spruce and jungle logs as example.

[jungle_log_top.properties.txt](https://github.com/webbukkit/dynmap/files/8159550/jungle_log_top.properties.txt)
[jungle_log.properties.txt](https://github.com/webbukkit/dynmap/files/8159551/jungle_log.properties.txt)
[spruce_log_top.properties.txt](https://github.com/webbukkit/dynmap/files/8159552/spruce_log_top.properties.txt)
[spruce_log.properties.txt](https://github.com/webbukkit/dynmap/files/8159553/spruce_log.properties.txt)
.

**Comment by generrosity** [comment] 2022-03-01 22:38
Its not errors, but what the base block looks like. Try the resource pack without Optifine - it might be similar.

Unfortuantely, dynmap doesn't support Optifine texture packs

**Comment by velnias75** [comment] 2022-03-01 22:41
dynmap seems to support almost all other optifine features and how should I *disable* the Optifine part?

**Comment by generrosity** [comment] 2022-03-01 22:47
I was suggesting to try in your MC client to view the texturepack without optifine mod... just incase it presented the same log texturing. Its a good base comparison if nothing else, and could only take a minute to try?

Im not sure what optifine features you mean - CTM1 is supported, as are normal texture packs. No other Optifine features are present afaik?

**Comment by velnias75** [comment] 2022-03-01 22:53
Currently I'm the maintainer of the texture pack, so I know how it looks like without Optifine 😸 

At least the logs are not using any sophisticated CTM features as you can see in the attached files.
Overlays aren't working and I removed them in the TP for dynmap to avoid log spam.

**Comment by generrosity** [comment] 2022-03-02 01:15
Ah cool 😁 I hoping there might have been some insight that we could have gotten from in, but if its different I suppose its just acting borked.

Unfortunately I can only suggest maybe some tips or workarounds in simplifying the resource pack so it looks better.

Like, I see that there are opensource CTM mods out there but I have no idea how quickly those standards change - it would be awesome if we had someone who could provide the CTM algorythms but currently most people don't use texturepacks let alone CTM specific ones and tends to generate more issues than creating awesome dynmap imagery.

I'd love to provide a CTM texturepack to bundle with dynmap 😆 just the simplier random rotations and variations stuff, but it really needs the support behind it

sorry - ramble off

**Comment by generrosity** [comment] 2022-03-06 21:30
Before I forget again - if you have the pack set up to work 'without optifine', there is an option in dynmap to turn CTM off. That might be another good workingaround so things dont look weird while things are being looked into

**Comment by JurgenKuyper** [comment] 2022-08-11 16:45
closing this issue because we couldn't reproduce from our end.

**Closed as completed by JurgenKuyper** 2022-08-11 16:45 UTC
Labels: Texture Errors
