### ISSUE TITLE
Black bands on dynmap

### ISSUE THREAD

**Issue by CyOze** [webbukkit/dynmap#2861] opened 2020-04-09 21:33 UTC
Hey, I have black bands on my dynmap ? Why ?
![IMG_20200409_232932](https://user-images.githubusercontent.com/59838095/78942699-7e518980-7aba-11ea-975f-f5e07230478b.png)

**Comment by Taxick** [comment] 2020-04-10 13:58
Hi, 

Sorry for the replay! I did not have a fix for the problem. But I have a similar problem!

![2020-04-10_15-48-53](https://user-images.githubusercontent.com/14352329/78995875-a33e0f00-7b43-11ea-80d5-5f15b9cc2776.jpg)

I have tried to delete the files with: "/dynmap purgeworld world" 

and then i run: "/dynmap purgeworld world"

But it still not show correctly up: you can also see the map here: https://map.wubcraft.dk

**Comment by colaman90** [comment] 2020-05-23 09:12
I have extacly the same error.

we tried: Delete all Tiles, make a --forgeupgrade with paper to load and convert all chunks again - just to be sure.

Then we done a fullrender for the world and everything works well until a few days. Since a week or something we see new black blocks on the dynmap.

![dynmap_error](https://user-images.githubusercontent.com/61457390/82726737-59217f00-9ce6-11ea-992d-279f620d2b70.JPG)

**Comment by Fuueloner** [comment] 2020-05-24 21:44
I think I have the same too. Even after deleting all data about tiles and using fullrender these black figures appear again and again. (using dynmap 3.0-beta-10 with vanilla paper 1.15.2)
![image](https://user-images.githubusercontent.com/55409654/82765500-1bc10c80-9e20-11ea-99f7-13efc036cd21.png)

**Comment by colaman90** [comment] 2020-05-27 15:06
We figured out, that if you use an old paper version like 1.15.2 build 213 the black bands will get correctly updated /rendered. I dont know if this problem could be a problem of paper..

**Comment by Fuueloner** [comment] 2020-05-29 03:36
Yes. I have changed Paper's build to the latest available so this issue is fixed. Thank you much for your feedback, colaman90!

**Comment by FedUpWith-Tech** [comment] 2020-07-31 19:28
Duplicate of #2485

**Closed as completed** 2021-12-17 18:42 UTC
Labels: Duplicate
