### ISSUE TITLE
WorldPainter: Dynmap won't render Leafs. (with fullrender)

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3104] opened 2020-08-19 16:18 UTC
**Issue Description:** *The dynmap does not render leafs (all sorts of leafs) when fullrendering by itselfs. Although, it does render all the leafs when I personally load in the chunks (by flying over them), and dynmap renders those.
Sample screen: https://gyazo.com/b1b5353831543f7952c2380b4372e4ca. As you can see, the place where I stand, leafs are visible. All the rest of the forest is rendered without leafs, making only the logs visible. (bit more black)*

* **Dynmap Version:** *Dynmap-3.1-beta-3-spigot*
* **Server Version:** *spigot 1.16.1 build.*
* **Pastebin of Configuration.txt:** *https://justpaste.it/3fh9k (sorry, pastebin was down). But its a default config without much edits.*
* **Server Host (if applicable):** *Syntexhosting - The Netherlands*
* **Pastebin of crashlogs or other relevant logs:** *(no crash caused)*
* **Other Relevant Data/Screenshots:** *https://gyazo.com/b1b5353831543f7952c2380b4372e4ca (same as above)*
* **Steps to Replicate:** *(Sorry I don't understand this question. No issue like this has occoured*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2020-08-19 16:23
What version was this map made on?

**Comment by ghost** [comment] 2020-08-19 16:25
> What version was this map made on?

This map was made on Worldpainter, which I had no problems with for years. Ingame the leafs are all fine. Its just the dynmap problem. The worldpainter map was rendered with the option 1.13+ (and supports 1.16)

**Comment by ghost** [comment] 2020-08-19 16:27
I am now seeing the config option "Transparent leafs" which may be the solution. If this works im so sorry for wasting your time, and me being once again stupid ;3

EDIT: Didn't help.

**Comment by FedUpWith-Tech** [comment] 2020-08-19 16:29
Duplicate of #3046

World painter breakes leaves and some grass textures, we are working on redoing the chunk loading engine to fix this but no eta

**Comment by ghost** [comment] 2020-08-19 17:04
Alright sorry, must have missed that one in my search for a duplicate. 
I understand theirs no eta, but are we speaking of days? Weeks? Months? Because I would like to have a fix for shit matter.

**Comment by FedUpWith-Tech** [comment] 2020-08-19 17:07
I can't say. Its not the biggest priority right now and the dev doesn't have a bunch of time to work on super large fixes/plugin rewrites right now. Could be next week or next year

**Comment by bloggy** [comment] 2021-02-25 19:08
Same issue here. Leaves not being rendered on a worldpainter map. Still no fix for this?

**Comment by Mint-101** [comment] 2021-05-07 02:49
I need a fix for this. Anybody?

**Comment by Mint-101** [comment] 2021-05-07 18:48
I actually found a way to fix this. It's not perfect but if you load in some chunks on your Minecraft client Dynmap will fix the leaves. Eventually, when your map has been fully loaded by players there will be no more invisible leaves. It's a scuffed solution but for many, it's just going to have to do.

EDIT: I was, unfortunately, wrong but I did learn something else. Some of my Dynmap custom trees rendered correctly although most didn't. I do not have the time to go more in-depth with this and test different custom trees to see which ones render, but it seems to me that trees with matching log and leaf types will render correctly.

**Comment by itsconnorgillespie** [comment] 2021-05-30 21:14
Bump. Having the same issue. The map artist for my server uses WorldPainter and practically every tree has no leaves. I don't have a solution and the solution provided by @Mint-101 didn't really seem to work. It would be really appreciated if this could be fixed since our server uses WorldPainter for literally every build ... _Here is a [screenshot ](https://i.imgur.com/S4cucvT.png)if anyone needed it._

**Comment by leivaa21** [comment] 2021-07-08 18:59
Bump. I have the same issue and I dont know how to fix it, some news?

**Comment by FedUpWith-Tech** [comment] 2021-12-21 22:39
Pre-1.18 here is the workaround/fix for this:
WorldPainter/EarthMC maps has many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage.
This is a result of how worldpainter generates maps and is not an issue with Dynmap, luckily there is a fix.

1. Download the WorldBorder plugin: [WorldBorder](https://www.spigotmc.org/resources/worldborder.60905/)
2. Pause Dynmap: `/dynmap pause all` 
3. Run worldborder with the force flag: `/wb [worldname] fill [freq] [pad] [force]` 
- `[worldname]` is the name of your world folder
- `[freq]` is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag
- `[pad]` how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated.  The default is 208, I recommend setting this to 0 for EarthMC
- `[force]` This must be set to true
4. Wait for worldborder to finish
5. Unpause Dynmap `/dynmap pause none`, you may have to restart the fullrender using `/dynmap fullrender [worldname]`

As of right now there is no workaround for 1.18 but we are investigating a more permanent fix than the force fill hack.

**Comment by bloggy** [comment] 2022-02-14 15:11
Still no solution for 1.18.x ?

**Comment by JurgenKuyper** [comment] 2022-02-14 15:12
> Still no solution for 1.18.x ?
did you do what FedUpWithTech said in the comment above yours? that is the fix for this.

**Comment by bloggy** [comment] 2022-02-14 15:15
Yeah he says:
"As of right now there is no workaround for 1.18 but we are investigating a more permanent fix than the force fill hack."

**Comment by JurgenKuyper** [comment] 2022-02-14 15:16
no, there hasn't been one, the dev is still busy with optimising the dynmap code, and fixing textures and such.

**Comment by mikeprimm-triva** [comment] 2022-02-14 15:49
Hey - do we have a good reproduce on this on current 3.4 SNAPSHOT?   I'll be happy to look at this, but I need a current code reproduce, since I'm not seeing this in any scenarios that I test with.  If this is about WorldPainter created maps, if you could give me a download of a world data (or just a portion of one) that exhibits the problem (I'm not going to screw around with old WorldPainter versions and such to reproduce this... just no time for that...)

**Comment by mikeprimm** [comment] 2022-02-22 01:11
No response on request for sample which exhibits problem - closing as unreproducable until this changes.

**Closed as completed by mikeprimm** 2022-02-22 01:11 UTC
Labels: Bug, Workaround available, Render Issues
