### ISSUE TITLE
Black spaces where modded blocks should be

### ISSUE THREAD

**Issue by Gartosz** [webbukkit/dynmap#3122] opened 2020-09-11 17:30 UTC
**Issue Description:** *Dynmap shows Chisel, Chisel&Bits and Flatcoloredblocks(and probably some more) mods blocks as a black space.*

* **Dynmap Version:** *Dynmap-3.0-RC3-forge-1.12.2.jar + DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar*
* **Server Version:** *magma 1.12.2 HEAD-ade7751*
* **Pastebin of Configuration.txt:** *default*
* **Server Host (if applicable):** *Google Cloud*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/PwvbuFrk*

**Comment by FedUpWith-Tech** [comment] 2020-09-11 17:32
Duplicate of #3112

**Closed as completed by FedUpWith-Tech** 2020-09-11 17:32 UTC
Labels: Duplicate, Mod specific, Support Question

**Comment by Gartosz** [comment] 2020-09-11 17:35
Thanks :)
