### ISSUE TITLE
AFK not showing on Dynmap

### ISSUE THREAD

**Issue by SullyTheUnusual** [webbukkit/dynmap#628] opened 2012-02-28 21:51 UTC
The Essentials AFK is not showing up on Dynmap.  I thought this might be a VanishNoPacket issue, so I disabled the Essentials hook in its config and dynmap still won't report AFK status.

I'm not sure if this could be related, but I didn't like the fact that HeroChat hijacked the /afk command from essentials so I disabled the alias in HeroChat's plugins.yml.

**Comment by Psy-Virus** [comment] 2018-12-02 14:03
Duplicate of #450

**Closed by Psy-Virus** 2018-12-02 14:03 UTC
Labels: Duplicate, Listed Feature
