### ISSUE TITLE
Dynmap doesnt save dmap changes

### ISSUE THREAD

**Issue by mmuziek** [webbukkit/dynmap#2823] opened 2020-03-23 23:10 UTC
Well i worked about a hour or 2 on making the maps look great and configurating them all.
Sadly dynmap doesnt save it so once the server restarts its back what it was before.

Can someone please tell me how to fix that or save it as i lost all my work...
i changed all maps names icons locations 
i removed some maps and appended others
everything is back what it  was.....

**Comment by FedUpWith-Tech** [comment] 2020-08-01 02:00
Duplicate of #1936

**Closed as completed by FedUpWith-Tech** 2020-08-01 02:00 UTC
Labels: Bug, Duplicate, Marker Issues
