### ISSUE TITLE
Custom Foliage Doesn't Render Correctly

### ISSUE THREAD

**Issue by gabehxd** [webbukkit/dynmap#3156] opened 2020-10-23 23:19 UTC
**Issue Description:** Custom biomes with custom foliage colors fail to show foliage colors properly on dynmap.

* **Dynmap Version:** Dynmap-3.1-beta4-spigot
* **Server Version:** Paper-244 (1.16.3)
* **Pastebin of Configuration.txt:** https://pastebin.com/d2xqxNJg
* **Server Host (if applicable):** Self hosted Ubuntu instance.
* **Other Relevant Data/Screenshots:** 
![image](https://user-images.githubusercontent.com/22406854/97060807-6b2f7400-1549-11eb-98f4-483cb9782c61.png)
![image](https://user-images.githubusercontent.com/22406854/97060844-91551400-1549-11eb-95d2-0806a5810c9b.png)
![image](https://user-images.githubusercontent.com/22406854/97060860-9ade7c00-1549-11eb-982d-19153422b84a.png)

* **Steps to Replicate:** Install [Wild Worlds](https://www.planetminecraft.com/data-pack/wild-worlds-32-new-biomes/) onto a singleplayer world and transfer onto a paper server then fullrender the world.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by mathvicot15** [comment] 2020-11-29 13:43
Same problem for me, Im on Paper latest version and dynmap doesn't render custom grass and leaves color in my world generation datapack. 

![Capture d'écran](https://user-images.githubusercontent.com/37654294/100543546-0b676f80-3251-11eb-978c-d38d30150685.png)

![Capture d'écran 2](https://user-images.githubusercontent.com/37654294/100543545-0aced900-3251-11eb-980a-b85142c1dfa5.PNG)

**Comment by FedUpWith-Tech** [comment] 2021-08-20 16:12
Duplicate of #3438

**Comment by FedUpWith-Tech** [comment] 2021-08-20 16:13
Linking that one rather than this one due to activity

**Closed as completed by FedUpWith-Tech** 2021-08-20 16:12 UTC
Labels: Duplicate
