### ISSUE TITLE
[Collection] Fullrender not rendering all chunks on pregenerated non-world painter maps

### ISSUE THREAD

**Issue by CannonBoomBoom** [webbukkit/dynmap#2485] opened 2019-05-21 15:53 UTC
![image](https://user-images.githubusercontent.com/22482596/58111103-70e79400-7bb6-11e9-8a93-b0ee0255c32f.png)
I have pre-rendered the whole 10k x 10k map, and I have let the "fullrender" command run for the past couple of days. However, I am still seeing un-rendered chunks.

Version is off of your FTP: "Dynmap-3.0-SNAPSHOT-spigot.jar | 2019-05-18 22:31 | 5.4M"

**Comment by MonstahGames** [comment] 2019-05-21 16:20
I have this issue too, but for me it's random tiles scattered around the map, for you it seems to have a pattern.
Strange!

**Comment by HarryFry** [comment] 2019-05-22 15:02
I had this issue as well. I seemed to be caused by letting dynmap run while using WorldBorder to fill in the world. I solved it by first filling the world with WorldBorder and then installing dynmap and starting the full render.

**Comment by ph1lt0r** [comment] 2019-05-30 16:20
I am having the same exact issue with this, only it's on the isometric map, not the top down map. Not using world border or anything like that.

**Comment by mikeprimm** [comment] 2019-06-05 03:49
Dynmap doesn't generate chunks, and can only render those that have been properly generated.   Unless you can confirm by visiting the chunks with a real player, versus assuming the WB version you are using is working right, and then render and confirm that the known-visited chunks aren't rendering, you're probably chasing a WB and/or spigot problem.

**Comment by mikeprimm** [comment] 2019-06-06 12:22
This probably will not help, but the latest dev build (208 or later) at https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar fixes as issue where chunks that were not fully generated in 1.14.x could be rendered (sometimes resulting in seeing chunks without trees or with incomplete lighting data, for example).  For what you guys are seeing, this will not necessarily be better - could be viewed as 'worse' - but it is all indicative that there might be issues with the state of chunks being driven to be generated by WB.  As I said above, visit chunks that you think are in error with a player (and run 'dynmap radiusrender N' when you get there), and see what happens: if the chunk renders properly, the state of the chunk was at issue and your player being present drove it to finish generating properly (and the chunk was either never generated, or was not completely/properly generated by WB and/or spigot) - dynmap cannot fix this, it can only show you the problem exists.

**Comment by CannonBoomBoom** [comment] 2019-06-07 12:04
Thanks Mike for looking into this.  I will test it out once I am home from work and have time!

**Comment by TNTUP** [comment] 2019-06-09 13:35
Same issue here but without worldborder. It DOES happen when the server restarts, leaving black bars/squares or whatever. Been like 5-6th time I reset the entire flat/surface renders then restarting the render. Both servers are on 1.12.2 and 1.13.2, all using the same version of Dynmap version 3.0-SNAPSHOT-208. Last time I updated was June 7, noticed it got updated today so trying this one though. https://i.qcfb.ca/20190609093004.png

Wasn't an issue with previous builds of dynmap for 1.12.2 (1.13.2 wasn't released in that time)

**Comment by roopekoo** [comment] 2019-06-11 15:42
I have also this problem.
Using paper 1.14.2, Dynmap-3.0 Build 215, and Worldborder 1.9.10
I tried to updaterender the area that was black and only a tiny area around me have been rendered of the black tiles.
Player needs to be in the chunk for dynmap to render it correctly. Might be caused by worldborder's fill.

**Comment by TNTUP** [comment] 2019-06-12 12:06
Those black lines are happenning when the server restarts. Again without WorldBorder https://i.qcfb.ca/20190612080534.png

I hope I gave reproduction steps correctly. Keep the good work Mikeprimm and contributors!

**Comment by mikeprimm** [comment] 2019-06-12 12:34
It's less about WB than it is about knowing that the chunks in question are fully generated: Dynmap doesn't drive chunk generation (and I've had so many problems with the Spigot chunk APIs since 1.13 that I've moved away from using them, as well), which also means that I will skip rendering chunks if they are:
1) Not fully generated
2) Not 1.13.x or later format (as driving them to be migrated is essentially a different path in the chunk generation logic)

The best test to see if one of these conditions is the case is to move or TP a player to a chunk that you see rendering as black.  Once you've done this, rerender the part of the map including the chunk (doing a 'dynmap radiusrender 20' using the player who has visited the chunk, while they are still there, is easy way to do this).  If the chunk now renders, the issue is one of the above.  I cannot currently vouch for the WB fill function - particularly on 1.14.x - but I can say that, when chunks aren't being generated fully, dynmap is one of the only ways to see that that is happening...

The current code has an 'experimental' option (don't use this without backing up you world data first) that, for 1.13.2 and 1.14.x, will try to drive the chunk generation logic when a older chunk format is found.  You can set the 'migrate-chunks' setting in configuration.txt to 'true', and rerun a fullrender - this should result in downlevel chunks being loaded (driving their migration logic to 1.13+) and allowing them to be rendered.  This is a 'one time only' requirement - if it works for you, turn the option back off once you've completed a fullrender on all your worlds, as the logic will no longer be needed (no new or future chunks will have the old format, and you should have already migrated the old ones).  See https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L472

**Comment by TNTUP** [comment] 2019-06-12 12:38
No issues with 1 and 2 you've mentionned. It happens (myself) when the server restarts, leaves black lines. Needed to go there and radiusrender, is pretty annonying. it didn't happen in 1.12.2 before. Updated all my 1.12.2 servers and 1.13.2 servers with Dynmap v3.0-beta-4. Should I create another issue because my case happens on server restarts or /dynmap reload? Let me know and I'll move my comments on another issue since this one seems to be caused by WB.

Edit: This is the 10th time I reset the entire dynmap tiles, https://i.qcfb.ca/20190623044552.png As soon the server restarts, theres a chance seeing black lines. 

Also, some of the renders are broken,

- Doing /dynmap radiusrender on an already rendered tile(s), nothing happens
- Enabled playermove option while moving on an already rendered tile(s), nothing happens
I think... Thinking downgrading to the last good known working build of Dynmap 1.12.2 (atleast for my 1.12.2 servers, but that won't fix that issue on 1.13.x servers)

**Comment by roopekoo** [comment] 2019-06-25 16:26
The issue with these black squares can be fixed when you force fill all the chunks in worldborder. "/wb world fill 20 208 true"
Takes some time but after filling and fullrender, the black squares disappear.
So this issue seems to be caused by WB's some how broken filing process creating in finished chunks.

**Comment by mrskizzex** [comment] 2019-09-04 12:21
Chiming in to say : me too. I first used wb to fill 2000 blocks, then i installed dynmap and let it run fullrender of the map. Here is the result.
![image](https://user-images.githubusercontent.com/11503128/64254177-23055a80-cf1f-11e9-8e82-1745428dfb36.png)

**Comment by JupiterSnarl** [comment] 2019-09-08 20:02
I have this same issue on a world we've had for a couple years that isn't yet fully explored. The problem appeared after they changed the way the game renders chunks. (1.13 or 14. I can't remember)

I tried updaterender but I haven't tried fill because we don't want to reveal unexplored areas. 
Is there anyway to fix this without filling the unexplored map?

I was thinking about running purgemap but I think that will make us have to re-explore right? Woudl purgemap + updaterender bring back the explored world?

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:08
Renaming for better management since this issue still persists

**Comment by FedUpWith-Tech** [comment] 2021-12-27 15:05
Hi all! I think @mikeprimm finally has fixed this issue in the snapshot builds 611+ and should be included in the v3.3-beta-4 release.

If you follow along the discussion of  #3565 Mike had to implement a custom light engine to add lighting data to chunks that don't get generated with it using pre-generation plugins and the like. I believe that fix has also fixed this issue.

Unfortunately, I don't have an easy way of testing this aside from spending time pregenerating a bunch of maps and seeing if this behavior is replicated at all. If anyone on this issue still has dynmap and can test the new beta4 release I would be most appreciative.

**Comment by jascotty2** [comment] 2022-01-04 00:39
A cursory test with radiusrender shows promising results - several problem areas cleared up perfectly!
I'm going to continue with an overnight fullrender, but so far v3.3 seems to resolve this issue.

[Edit] - Update on this, the fullrender went flawlessly! The missing chunks that have been an issue for years are all filled in! Works great! ^.^

**Comment by JurgenKuyper** [comment] 2022-08-11 12:53
closing this issue because feedback provided shows that builds after 611 contain the render fix requested.

**Closed by JurgenKuyper** 2022-08-11 12:53 UTC
Labels: Render Issues, World Conversion
