### ISSUE TITLE
Tiles with old DataVersion (or Status: spawn) not rendered

### ISSUE THREAD

**Issue by chrysn** [webbukkit/dynmap#3200] opened 2020-11-25 07:30 UTC
**Issue Description:** Dynmap does not render chunks that have old data versions (eg. 1343 = 1.12.2), and for recent versions (eg. 2567 = 1.16.1) only renders their status property is "full", not "spawn" (as displayed in mcaselector's "edit chunk" menu)

* **Dynmap Version:** 3.1-beta5-431 (but also observed with beta 2)
* **Server Version:** paper 1.16.4 build 288 (but also observed with 1.16.1)
* **Pastebin of Configuration.txt:** default with these changes: http://paste.debian.net/1174212/
* **Server Host (if applicable):** selfhosted
* **Pastebin of crashlogs or other relevant logs:** no error messages seen
* **Other Relevant Data/Screenshots:** A screenshot comparison has been attached, showing dynmap's render next to mca selector's view which indicates that the actual content of the chunks is already there: ![r 0 -2](https://user-images.githubusercontent.com/442326/100195195-471fd380-2ef7-11eb-8676-cf98e837ed31.png)
* **Steps to Replicate:** To replicate such a world, the only realistic way is to start a server in an old version, explore some, upgrade and then render. Once the world is there, repeated runs of dynmap (ie. removing all of the plugin, installing it again and running fullrender creates the same issue)

 [x] *I have looked at all other issues and this is not a duplicate*  
 [?] *I have been able to replicate this*: Yes on the dynmap side, no on recreating such a world from scratch (it'd take a lot of time and probably doesn't contribute to the issue).

A thing I noted about the chunks in version 2567 with status=spawn (those stay black) is that they also have the cavemask properties set -- but it seems from the chunks I've inspected with mcaedit that this is the case for all chunks in that status, so it's not much of a criterion.

Please let me know if I can provide any further information, should split this up between old-datavesion and status-spawn (no differences in effect visible) or this is out of scope for a bug report and would better be rephrased as a feature request.

**Comment by TixTux** [comment] 2021-01-27 22:52
Still the same in 1.16.5. No way to render old/coverted maps until now
Dynmap v3.1-beta-7

**Comment by FedUpWith-Tech** [comment] 2021-08-20 16:01
Duplicate of #2282

**Closed as completed by FedUpWith-Tech** 2021-08-20 16:01 UTC
Labels: Duplicate
