### ISSUE TITLE
Rendering issue 

### ISSUE THREAD

**Issue by insanegyros** [webbukkit/dynmap#3109] opened 2020-08-27 05:46 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:**
I have a problem with fullrender and radiusrender. It is unable to render something...normal? I have a render running for 3 days in a row now, latest log *(07:07:51[INFO] [dynmap] Radius render of map 'povrch' of 'world' in progress - 429500 tiles rendered (261,34 msec/tile, 264,91 msec per render))* said I rendered 429500 tiles on a 10000x10000 pregenerated world and yet the map is rendered like this.
![obrazek](https://user-images.githubusercontent.com/34373776/91387892-81b19b80-e836-11ea-9242-62bacfb45cd3.png)

When I tried radiusrender, the same thing. Only difference is, when the radius is smaller, the map actually generates something, but it has to be <50. And when player joins and render is going on and isn't paused, the CPU will flatline at 100%. Updaterender does absolutely nothing even tho my world is pre-rendered already.

* **Dynmap Version:** 3.1beta3a-409
* **Server Version:** Spigot 1.16.2
* **Pastebin of Configuration.txt:** https://pastebin.com/K2rxuAhD
* **Server Host (if applicable):** Hostify.cz
* **Pastebin of crashlogs or other relevant logs:** None.
* **Other Relevant Data/Screenshots:** 
![obrazek](https://user-images.githubusercontent.com/34373776/91389114-f259b780-e838-11ea-8275-494e61d3d5f5.png)
* **Steps to Replicate:** Launch server > pregenrate map > launch fullrender > profit

 [X] *I have looked at all other issues and this is not a duplicate*  
 [XXXXXXXXXX] *I have been able to replicate this*

**Comment by TeknosQuet** [comment] 2020-08-27 14:49
I think it might be a bug because I have the same issue. It's not exactly the same as yours but it's still weird rendering nevertheless.
![Screenshot_19](https://user-images.githubusercontent.com/40285364/91457615-25f10d80-e84a-11ea-940a-0edccba33a98.png)
![Screenshot_20](https://user-images.githubusercontent.com/40285364/91457641-30130c00-e84a-11ea-8675-db1bef116972.png)
As you can see with those two images, there's an obviously weird pattern going on that shouldn't happen. This doesn't actually occur in the world and is more of a visual bug.
![Screenshot_21](https://user-images.githubusercontent.com/40285364/91457926-8d0ec200-e84a-11ea-8f1f-d3dc231aad4c.png)
If we compare the second image of the Dynmap and the image on the client, they look totally different.

Dynmap ver. 3.1beta3a 409
Paper 1.12.2

**Comment by FedUpWith-Tech** [comment] 2020-09-01 18:21
@TeknosQuet your issue is unrelated as leaves are a separate process in world generation than chunks. Your issue is related to world generation and the custom map you use. Gyros issue is related to world conversion between versions.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 16:26
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 16:26 UTC
Labels: Duplicate

**Comment by TeknosQuet** [comment] 2021-08-20 16:29
Oops my bad. I didn't know better. Thanks
