### ISSUE TITLE
Markers.yml & Favicon

### ISSUE THREAD

**Issue by KentBrought** [webbukkit/dynmap#3790] opened 2022-07-04 06:38 UTC
**Issue Description:** Sometimes the dynmap won't start because of this issue.

* **Dynmap Version:** 3.2-beta-1-470
* **Server Version:** Paper version git-Paper-"e04368045" (MC: 1.16.5)
* **Pastebin of Configuration.txt:** https://pastebin.com/KBwJpL2M
* **Server Host (if applicable):** Pebblehost
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/kLCUcm5f
* **Other Relevant Data/Screenshots:** https://pastebin.com/5wjjMrnk
* **Steps to Replicate:** I tried manually removing a marker that had no name that was located at 0,0. I also tried copying over part of the base markers.yml file but that didn't seem to work. I also am not sure with how to get a custom favicon. Thanks again.

**Comment by JurgenKuyper** [comment] 2022-07-04 06:45
That marker is the spawn marker set visible in configuration.txt, you have an indentation problem in the markers yml, also, changing the favicon is done by editing the web/images/dynmap.ico file.

**Comment by KentBrought** [comment] 2022-07-04 18:44
Where exactly is the indentation problem? I tried using the tool that the console suggests whenever I got the error, but I don't understand where it's talking about. 
Whenever I changed the web/images/dynmap.ico file is just changes it to the empty icon symbol: 
![image](https://user-images.githubusercontent.com/63319015/177200634-b9b9c03f-880e-4423-824f-b721e26843c8.png)
Thanks!

**Comment by JurgenKuyper** [comment] 2022-07-04 19:10
aparently your yml got changed, it is valid now, restart to see. the dynmap icon needs to be an ico, not a png

**Comment by KentBrought** [comment] 2022-07-04 20:22
Okay, the markers.yml file got fixed! But the dynmap icon doesn't seem to be working. Currently I do have it as a .ico file labeled as dynmap/web/images/dynmap.ico 
Thank you!

**Comment by JurgenKuyper** [comment] 2022-07-04 20:26
but is it an actual ico or did you change the extension?

**Comment by KentBrought** [comment] 2022-07-04 20:28
I just used an online .png to .ico converter. Is there something more that I have to do for it?

**Comment by JurgenKuyper** [comment] 2022-07-04 20:36
as far as I know it needs to be a real ico, could be the online converter just altered the extension, this one in this zip works: 
[dynmap.zip](https://github.com/webbukkit/dynmap/files/9041919/dynmap.zip)
extract and place it in the web/images folder, then start the server, it should show like this: 
![image](https://user-images.githubusercontent.com/45831568/177214186-f42eacdb-f26e-435e-8962-59ebd6345525.png)

**Comment by KentBrought** [comment] 2022-07-05 01:49
I just tried that and it didn't seem to work. It still shows the same default thing as before.

**Comment by JurgenKuyper** [comment] 2022-07-05 08:41
is there any log in the f12 console about the loading of the icon? 
could be it is a pebblehost issue, not sure, but the icon works for me.

**Comment by KentBrought** [comment] 2022-07-05 16:16
It does show this in the console: 
![image](https://user-images.githubusercontent.com/63319015/177372276-92bd2f28-e758-4836-98af-a1dcf8eaa5a6.png)

**Comment by JurgenKuyper** [comment] 2022-07-05 16:33
Did you check the file permissions? (The file should have the same user:group as the one that runs the Minecraft server

**Comment by KentBrought** [comment] 2022-07-05 21:54
I'm not sure what you mean.

**Comment by JurgenKuyper** [comment] 2022-07-06 19:23
you can try to backup and delete the web folder and let dynmap regenerate them

**Comment by KentBrought** [comment] 2022-07-09 04:05
It still didn't work.

**Comment by JurgenKuyper** [comment] 2022-07-17 10:38
did you change the name at all and check whether the user that runs the dynmap server can access the ico file?

**Comment by JurgenKuyper** [comment] 2022-08-11 08:48
closing comment due to no reply, and inability to reproduce on my end.

**Closed as completed by JurgenKuyper** 2022-08-11 08:48 UTC
Labels: Answered, Support Question
