### ISSUE TITLE
Markers Disappearing after Dynmap reload or server restart

### ISSUE THREAD

**Issue by Nick2253** [webbukkit/dynmap#2242] opened 2018-05-29 17:53 UTC
I believe my issue is similar to #2145.

Using DynMap 2.6 Beta 1 and Forge 14.23.3.2655.

I'm seeing this same error with Markers disappearing, but even a server restart isn't fixing this.  When I check the files in the dynmap directory, it doesn't look like Dynmap is writing out any of the marker information.  The "markers" directory is empty, markers.yml is empty (but for what I think is the default structure),  and web/tiles/_markers_/marker_world.json just has the spawn in it.

Permissions seem to be all correct, and I'm not seeing anything in the log about any Dynmap errors.  I see clearly where the area is created, but when I reboot the server, the area is gone.

I noticed that the markers.yml file looks like a JSON file.  If I delete my markers.yml file, this is what is recreated:

```
icons: {
    }
sets:
    markers:
        hide: false
        circles: {
            }
        deficon: default
        areas: {
            }
        label: Markers
        markers: {
            }
        lines: {
            }
        layerprio: 0
playersets: {
    }
```

**Comment by achencraft** [comment] 2018-05-30 16:15
I have the same problem :'(

**Comment by thiefa** [comment] 2019-01-10 20:54
Got the same Issue too..

i use Bytecart for railway transportation, thus having about 30 Markers for the Stations, never had an issue on older versions.
since im on 1.13.2 and Dynmap3+ i deleted my worlds tiles folder to re-render. 
at the first starts dynmap brought errors because of the marker file, so i deleted it aswell, as i thought there might have been updates to Dynmap that arent going well thogether with old markers.txt.

so while dynmap was rendering, i was redoing the station markers, they showed up on dynmap for a while, then they disapeared, exept a few.
checking the markers.txt, i figured out those stations where still written in the markers.txt, while newly created stations pop up in dynmap, but dosent get written to the markers file.. so after a brief moment, they disapear again.

as a workaround i cloned an marker, and edited it to fit for the next place i needed one.. made that for about 10 markers, then i reloaded dynmap. nothing more poped up...

same goes if i do markers with /dmarker add


i did a restart, and had that damn error  about markers.txt again. 
as recomended i checked with the yaml checker, ---> no errors in markers.txt
double and trippel checked that i didnt had same marker tags or anything.. all fine.. so deleted all markers down to 10, restartetd again...
dynmap works.. tryed to add markers via command --> markercount ingame was going up (not given special names, so just marker_x) added up to 15, but again just poped up quick in dynmap and no entry in the markers.txt. 

really hope for an idea on how to get that working again...

**Comment by achencraft** [comment] 2019-01-11 09:35
Hi, 
I have fond a solution, but the bug always is active.

When I'm in the game, i can add markers (no limit for the number) with for example the command : `/dmarker update id:marker-4 icon:BUS_L3`.
I add all markers that I want...

But, at the end, I don't use `/reload` or `/dynmap reload` !!! NEVER !!!
You can just stop your server with `/stop`

After you turn it on and your markers are present on the map.

I hope that can help you

Cordially
Sorry for my english XD

**Comment by thiefa** [comment] 2019-01-11 20:39
Hi achencraft, 
thanks for your reply.

i tried it, but with my bad luck im always having, it dosent work on mine..

Spend 4! hours doing all the markers, had them for some time, but after some time i was back on the in markers.txt written ones.. 
next time ill try whatever in smaller time slices, thats for sure! :(


my dynmap sits on [pia.hopto.org/dynmap](url)

**Comment by achencraft** [comment] 2019-01-12 15:59
Hi, 
actually, we have 12 markers :
- 5 tramway stops
- 6 bus stops
-1 one icon for the christmass tree which is on my city (strasbourg, France)

During the christmass period, last month, I had 15 markers + these 12 = a total of 27 markers.
I regularly add and remove markers on the map in according to events in my city.

Have a good day
Cordially

**Comment by FedUpWith-Tech** [comment] 2020-07-28 21:04
Duplicate of #1936

**Closed** 2020-07-28 21:05 UTC
Labels: Duplicate, Marker Issues
