### ISSUE TITLE
Markers disappearing after page reload

### ISSUE THREAD

**Issue by gioporta** [webbukkit/dynmap#1956] opened 2016-06-01 23:13 UTC
This is with Dynmap Forge v2.2 for MC 1.7.10

Whenever I create markers with `dmarker add` they show up on the web map, but after reloading they disappear again. They don't seem to save to markers.yml and even after reloading the Dynmap configuration and restarting the server, they refuse to show up.

Oddly enough, they still show on `dmarker list` - just never on the map.

Seems to be the same issue as #552, #795, and #1283

**Comment by smmmadden** [comment] 2016-06-07 04:50
same issue in MC 1.9.4 Spigot with Residence 4.1.4.0 and other plugins.  Creating the marker lines sows up on the map but is a) not updating the marker.yml file, b) not able to find examples of each command string. and c) how does one identify/change the colors for each type supplied..

**Comment by jewome62** [comment] 2016-06-17 20:49
:+1:

**Comment by dwa1275** [comment] 2016-06-22 19:18
ive noticed this as well, you might notice that after time the marker will show back up on the map, this is do to an area in the config for when the map a "refreshes" or logs the changes over night, after messing with markers, and them not showing up I had seen that I had placed ALOT of markers and they all showed after a day, had to remopve a bunch

**Comment by jewome62** [comment] 2016-06-25 18:45
I modify directly the files markers.yml, But someone have the yaml structure? for the circle, for the square, etc ?

**Comment by darkllama23** [comment] 2016-07-06 01:27
I have the same problem running Spigot 1.10 with only Dynmap and CommandLogger. Markers never show on the the map, markers.yml, or marker_world.json. But they do show up in /dmarker list. I been editing marker_world.json but like above, I do not know the correct structure.

**Comment by Tennik** [comment] 2016-07-07 22:20
I also have the same problem with Dynmap-2.2-forge-1.7.2
And I don`t know how to be...
I find an alternative way in modifying the file marker_World.json (in dynmap\web\tiles\_markers_\ folder). But this is so sad...

**Comment by Tennik** [comment] 2016-07-07 22:59
Oh man... I have installed DynmapCBBridge mod, then i removed open and close brackets in markers{} and added new markers into file markers.yml like this:
`markers:
            City:
                icon: queen
                markup: false
                label: MyCity
                z: 3495.0
                world: World
                y: 65.0
                x: 60.0
layerprio: 0
...`
After this I restarted my server. And it works now! Markers do not disappear anymore! And now I can add new markers with commands! Its a kind of magic)
May be it will be useful for someone with such problem.

**Comment by cmisztur** [comment] 2016-10-26 14:51
I was messing with the config while server was running and I believe that screwed me up.  I then restarted the server and markers.yml started updating.

**Comment by Vilzu45** [comment] 2018-07-07 17:05
How can you type it to the markers.yml? do you have to add the coordinates manually?

**Comment by FedUpWith-Tech** [comment] 2020-08-15 07:23
Duplicate of #1936

**Closed** 2021-08-19 23:44 UTC
Labels: Bug, Duplicate
