### ISSUE TITLE
Dynmap spamming an exeption to console - dynmap v3.0-beta-10-257

### ISSUE THREAD

**Issue by filasik** [webbukkit/dynmap#2886] opened 2020-04-18 13:12 UTC
Hello, I'm using beta 10 dynmap on my paper spigot 1.15.2 (git-Paper-193 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT))

is there a newer build solving this issue? The error is repeating every minute and yesterday i saw an error with player leave event - but its somehow fixed. Thanks to dev for amazing work :-)

`[15:09:48 WARN]: [dynmap] Task #602465 for dynmap v3.0-beta-10-257 generated an exception
java.lang.IllegalArgumentException: Length of Base64 encoded input string is not a multiple of 4.
at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:267) ~[patched_1.15.2.jar:git-Paper-193]
at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:246) ~[patched_1.15.2.jar:git-Paper-193]
at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:232) ~[patched_1.15.2.jar:git-Paper-193]
at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.getSkinURL(BukkitVersionHelperGeneric.java:569) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.<init>(DynmapPlugin.java:604) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$3$1.run(DynmapPlugin.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-193]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-193]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1246) ~[patched_1.15.2.jar:git-Paper-193]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-193]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-193]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-193]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by RobinWhitfield** [comment] 2020-04-21 16:04
Potentially a duplicate of #2883

**Comment by En0tS** [comment] 2020-04-22 04:43
> Potentially a duplicate of #2883

Yeah, there is a lot of issues with this error, maybe you will help to fix it?

**Comment by ice-fly** [comment] 2020-04-30 05:21
On latest version of paper. Issue not occurring. Guessing its a config error.

**Comment by FedUpWith-Tech** [comment] 2020-07-31 19:41
Duplicate of #2883
fixed in later version

**Closed as completed by FedUpWith-Tech** 2020-07-31 19:41 UTC
Labels: Bug, Fixed, Duplicate
