### ISSUE TITLE
Web files are not matched with plugin version: All files need to be same version (undefined) - try refreshing browser cache (shift-reload)

### ISSUE THREAD

**Issue by realGretix** [webbukkit/dynmap#3804] opened 2022-07-18 18:20 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I tried hosting dynmap on my vps with apache2 and sqlite but after setting everything up with this guide https://github.com/webbukkit/dynmap/issues/2609 and copying web folder files to website directory dynmap gives me error like in the title*

* **Dynmap Version:** *3.4-beta-3-774*
* **Server Version:** *paper 379 1.18.2*
* **Pastebin of Configuration.txt:** *https://pastebin.com/s2a8Vi4T*
* **Server Host (if applicable):** *Contabo*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/LKKJy3Jk*
* **Other Relevant Data/Screenshots:** *![image](https://user-images.githubusercontent.com/62449290/179575911-8f30bf06-c56a-423d-a1a0-f91cee7015f3.png)*
* **Steps to Replicate:** *Setting everything like in my configuration file and copying web folder files to apache2 web directory*

 [*] *I have looked at all other issues and this is not a duplicate*  
 [*] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment] 2022-07-18 18:22
that guide is not entirely proper, we adapted it to ours and added it to the wiki: https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/
changes are to the web entry of configuration.txt and the need of installing php-fpm and php-mysqli, always check the error.log of apache2

**Comment by realGretix** [comment] 2022-07-18 18:27
well i have this in error.log https://pastebin.com/AKJdYmbp

**Comment by JurgenKuyper** [comment] 2022-07-18 18:29
PHP Warning:  file(dynmap_config.php): failed to open stream: No such file or directory in /var/www/mapa.geoplay.pl/standalone/configuration.php . 
it cannot find that file, check that you did the proper settings according to the guide on our wiki, and the php modules are installed, then check that all the files have the right user:group so apache2  can read them.

**Comment by realGretix** [comment] 2022-07-18 18:36
i set the permissions and downloaded php modules but still it's not working. And the file surely is in correct detination
![image](https://user-images.githubusercontent.com/62449290/179579507-5ac915ab-0294-456c-88c2-470dfbbd7ffb.png)

**Comment by realGretix** [comment] 2022-07-18 18:47
so what do i do?

**Comment by JurgenKuyper** [comment] 2022-07-18 18:55
check that you did the proper settings according to the guide on our wiki, you didn't answer on that so I guess that the web part especially of the configuration.txt is still improper, then restart the mc server, shut it down, re-upload the web files and try

**Comment by realGretix** [comment] 2022-07-18 19:02
everything is like in the tutorial

**Comment by JurgenKuyper** [comment] 2022-07-31 10:43
then I don't know what is wrong, because I did the tutorial many times, and it always worked out for me, could be something is wrong wit a proxy or sth.

**Comment by JurgenKuyper** [comment] 2022-08-19 15:12
closing this issue because we cannot reproduce the sircumstances in which this error arises.

**Closed as not planned by JurgenKuyper** 2022-08-19 15:12 UTC
Labels: Answered, Support Question

**Comment by OstojaOfficial** [comment] 2022-10-21 15:01
I am experiencing the same issue with my Nginx setup. For some reason file dynmap_config.php did not generate.

**Comment by OstojaOfficial** [comment] 2022-10-21 15:04
> PHP Warning: file(dynmap_config.php): failed to open stream: No such file or directory in /var/www/mapa.geoplay.pl/standalone/configuration.php . it cannot find that file, check that you did the proper settings according to the guide on our wiki, and the php modules are installed, then check that all the files have the right user:group so apache2 can read them.

Its actually looking for dynmap_config.php not configuration.php. The error message is saying that it tried to open file dynmap_config.php while running configuration.php.

**Comment by OstojaOfficial** [comment] 2022-10-21 15:40
I fixed my issue. For anyone experiencing this issue in the future. Read the guide, you are unable to use SQLite if your web server is not on the same machine as your minecraft server.
https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/#setting-up-the-web-server-thats-on-the-same-server-as-the-minecraft-server

**Comment by JurgenKuyper** [comment] 2022-10-21 15:42
It should still work, if the nginx module for SQLite is installed most likely

**Comment by OstojaOfficial** [comment] 2022-10-21 15:44
> It should still work, if the nginx module for SQLite is installed most likely

Are you sure it will? How does the webserver connect to the SQLite DB?

**Comment by JurgenKuyper** [comment] 2022-10-21 16:01
I don't really know, but you might use a symlink over ssh to connect to the file? But idk how SQLite handles multiple connections to a file

**Comment by OstojaOfficial** [comment] 2022-10-21 16:15
> I don't really know, but you might use a symlink over ssh to connect to the file? But idk how SQLite handles multiple connections to a file

NFS might work. But best solution is MySQL in this case.
