### ISSUE TITLE
Apostrophe problem

### ISSUE THREAD

**Issue by Luysita** [webbukkit/dynmap#2364] opened 2018-10-18 11:43 UTC
Hello,

When I use /dmarker add, the apostrophe is not showing properly in the map, although in the marker is just fine.
This doesn't happen when using signs though.
Am I doing something wrong?

Dynmap version: core=3.0-beta-1-129, plugin=3.0-beta-1-129

![2018-10-18-12-37-1131-i86b38mgak](https://user-images.githubusercontent.com/4097013/47151881-f4649e00-d2d2-11e8-9372-acb2b63b20cb.png)
![2018-10-18-12-38-1132-1hqdnjujww](https://user-images.githubusercontent.com/4097013/47151882-f4fd3480-d2d2-11e8-922e-33eb4cfe37ac.png)

**Comment by SebRomu** [comment] 2018-11-03 17:01
I too have this problem, they worked fine before the 1.13 compatible versions.

**Comment by WELTEINZ** [comment] 2018-11-08 14:05
I can confirm the Problem.

**My setting:**
Paper 1.13.2 dev 417
Dynmap v3.0-beta-2
DiscordSRV 1.16.4

**Comment by generrosity** [comment] 2018-12-03 21:32
It looks like the config file converts the apostrophe to prevent malware input, and then at the presentation of the web it is re-encoded again.

If you can try with a backtick ` a curly quote, or a double quote that would be useful to confirm, and possibly a quick workaround?

**Comment by mikeprimm** [comment] 2018-12-06 02:05
Just tried this with latest dev build, and it looks like it works.  Please give it a try and let me know if you see the same.  https://dynmap.us/builds (3.0 SNAPSHOT files)

**Comment by dotterian** [comment] 2018-12-14 13:37
Didn't work for me.
Here you can see that I'm using latest version of dynmap (downloaded it 3 mins prior to this comment)
![2018-12-14 16-32-07](https://user-images.githubusercontent.com/6250486/50006216-08203e00-ffbe-11e8-9eaa-fe246f4391e5.png)
Here's part of `markers.yml` (utf-8 encoded)
![2018-12-14 16-31-39](https://user-images.githubusercontent.com/6250486/50006257-330a9200-ffbe-11e8-98e9-a27c8c05c47d.png)
And here's what I see on map
![2018-12-14 16-31-07](https://user-images.githubusercontent.com/6250486/50006295-59c8c880-ffbe-11e8-8347-7908bfeaf01c.png)

Should I perform some additional actions, like, remove my web folder (or some parts of it, because I don't want to rerender whole 5 gigs of map)?

**Comment by mikeprimm** [comment] 2018-12-14 14:02
Are you running internal server, or using Apache or the like (external)?

**Comment by dotterian** [comment] 2018-12-14 16:21
@mikeprimm I'm using internal server that comes with plugin.

**Comment by mikeprimm** [comment] 2018-12-15 00:48
What do you get with markup=true on same marker?

**Comment by SebRomu** [comment] 2018-12-30 16:40
Sorry for the long delay in getting back to you.

Setting markup=true seems to fix the issue.

Is there an easy way to set this when making/editing markers within Minecraft, or is it only available when editing the markers.yml file directly?

**Comment by deadtom76** [comment] 2019-01-28 02:16
Same issue here. Setting markup=true fixes the problem.

**Comment by eightbitx** [comment] 2019-03-04 01:54
I have a plugin that adds and deletes markers automatically. I have quite a few (https://alttd.com/map/valley/ - uncheck "players" and "markers" so you only see warps)... is this something that can be added to the regular config so that markup can always be true?

**Comment by miiichael** [comment] 2019-11-02 09:32
This issue might be a dupe of #2288?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:55
Duplicate of #2288

**Closed by FedUpWith-Tech** 2020-07-28 22:55 UTC
Labels: Duplicate, Marker Issues
