### ISSUE TITLE
Markers dissapearing

### ISSUE THREAD

**Issue by robertoccu** [webbukkit/dynmap#2829] opened 2020-03-25 12:52 UTC
Hi!

We are using in our server dynmap (version: core=3.0-beta-10-257, plugin=3.0-beta-10-257) with PaperSpigot (version 143, 1.15.2) and we are having a very frustrating problem: our markers and areas disappears without errors in console, without restarting the server and without using the plugin anymore after placing the marker. Sometimes (with areas) we type the commands and never appears.

Any idea of what could be happening?

I could give us the information that request me.

**Comment by FedUpWith-Tech** [comment] 2020-08-01 01:58
Duplicate of #1936

**Closed as completed by FedUpWith-Tech** 2020-08-01 01:58 UTC
Labels: Duplicate, Marker Issues
