### ISSUE TITLE
chunkgenerated trigger

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#3529] opened 2021-11-15 18:47 UTC
**Issue Description:** *Some chunks are not included during rendering. Only with a subsequent full or radiusrender these areas are rendered.*

* **Dynmap Version:** *Dynmap version: core=3.2.1-531, plugin=3.2.1-531*
* **Server Version:** *Paper version git-Paper-378 (MC: 1.17.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/j8SFHqY2*
* **Other Relevant Data/Screenshots:** *
![55](https://user-images.githubusercontent.com/2832339/141836445-2bd64c76-eca2-4932-9919-95b3901fc7e6.PNG)*
* **Steps to Replicate:** *Use my render triggers and explore new chunks.*

**Comment by FedUpWith-Tech** [comment] 2021-11-23 01:38
Duplicate of #2075

**Closed as completed by FedUpWith-Tech** 2021-11-23 01:38 UTC
Labels: Duplicate
