### ISSUE TITLE
Dynmap for RAID servers

### ISSUE THREAD

**Issue by thunderai** [webbukkit/dynmap#2733] opened 2019-12-27 22:38 UTC
I'm looking for a new ability. The ability for dynmap to just display the map 'YOU' have explored. Thus hiding everything else you dont know about. I'd also like to add a Fog of War delay where the map doesn't update for chunks you haven't been in recently. 

is this doable?

**Comment by mikeprimm** [comment] 2020-01-12 23:52
It is possible, but would be quite a bit of work - and would have some practical limits.  Specifically, it'd be impractical to restrict visibility below the level of a 'map tile' (that is, a single rendered PNG/JPEG file), since those are pre-rendered and showing different versions for different people's explored areas would essentially mean rendering potentially dozens of copies of the tiles (technically possible, but given how much problem folks have with how big rendered maps can be as it is, I just don't think this would be workable).  Something more akin to 'you can see/not see' on a map tile grain vs a 'block' or 'chunk' grain would be more practical, as then the data needed per user would be just used to control whether a given tile was or was not visible, versus affecting how the tile was drawn on a per-user basis.

**Comment by mitchellcrazyeye** [comment] 2020-01-13 16:31
I also like this idea, feel like it would need some type of user based login that's tied to your in game username so you can see the map you explored. I like the idea of it being tile-based also, I'm already dealing with 1 1/2 million tiles on my world alone, so cutting down duplicates would be nice. Overall, would love this as a feature!

**Comment by thunderai** [comment] 2020-01-13 16:46
> I also like this idea, feel like it would need some type of user based login that's tied to your in game username so you can see the map you explored. I like the idea of it being tile-based also, I'm already dealing with 1 1/2 million tiles on my world alone, so cutting down duplicates would be nice. Overall, would love this as a feature!

There already is a user account system in place, which is helpful.

**Comment by FedUpWith-Tech** [comment] 2020-07-31 18:34
Duplicate of #1934

**Closed as completed by FedUpWith-Tech** 2020-07-31 18:34 UTC
Labels: Duplicate, Feature Request
