### ISSUE TITLE
Dynmap lighting is broken.

### ISSUE THREAD

**Issue by FajnB** [webbukkit/dynmap#2930] opened 2020-05-12 18:11 UTC
When setting brightness in settings files the ambient setting is behaving unusually.
Previously it was pretty much equal brightness change within all 0-15 numbers.
In last version (3.0beta-10) there is an issue when from 0-9 it is very subtle change in brightness and from 10-15 it is very distinguishable one. It literally looks like it has moved from linear function to some sort power function.
I ve been able to notice it, cos after updating my custom lightnings just screw up and darkened. At first a thought that it does not work what so ever, because even bright presets provided by plugin it self were dark and minor changes in values yelled no changes in brightness of the render (at that time I did not noticed any change in brightness of render, that is hos subtle the change is). But now I just noticed that if I changed the value to 15 it just somehow became full bright, so I begun testing that and here it is. In the latest update there is some change which made the brightness calculation different in such way that even presets are not correct. That means that every single custom lightning is changed and wrong (as long as there is Ambient as a option).
Please fix that, because this is really annoying to have like 5 possible/usable values.

Edit:
Nther and End are not affected by any lightning effect.

**Comment by mikeprimm** [comment] 2020-07-01 05:46
Not clear on what you mean by 'custom lightings' - those are client settings, not server settings, so not clear how you'd expect Dynmap to know about those.  The lighting code is based off of the lighting data provided by the MC worlds object, and hasn't changed in a very long time.  15 is full brightess in MC, so not clear on how that would be a surprise.  The light levels in the lightings.txt are still the standard 0-15 levels in MC, and are similarly scaled based on the lighting data provided by the vanilla MC code.

**Comment by FajnB** [comment] 2020-08-02 07:58
Sorry for not answering, i thought that this question would not be answered and I stopped watching it.
So about the bug. I set up a lighting in for the neher map to be much brighter so I could se on the map where thinks are but for some reason after updating to 3.0beta-10 this is no longer the case, the lighting absolutely ignores what is set in lightings.txt so my nether is on default lightning no matter what I set.

**Comment by FajnB** [comment] 2020-08-11 20:24
Thanks and sorry.

**Comment by skerit** [comment] 2020-12-02 14:07
It seems to me like the ShadowHDLighting is completely ignoring the `ambientlight` level? No matter what I set it too, the result is always the same.

**Comment by FajnB** [comment] 2021-01-04 10:13
It seems that this issue is just non relevant as there is no response nor fix yet.

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:50
Duplicate of #2195

**Closed as completed by FedUpWith-Tech** 2021-12-17 18:50 UTC
Labels: Duplicate
