### ISSUE TITLE
shut down

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#3318] opened 2021-03-21 22:49 UTC
**Plugin Version:** dynmap v3.1-457
**Server Version:** Paper version git-Paper-553 (MC: 1.16.5)

sometimes the server does not shut down completely and ends here:
....more
[22:34:10] [Server thread/INFO]: [Vault] [Economy] Essentials Economy unhooked.
[22:34:10] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.2.4+5723-e3bfc64
[22:34:10] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[22:34:10] [Server thread/INFO]: [dynmap] Disabling dynmap v3.1-457
[22:34:10] [Server thread/INFO]: [dynmap] Unloaded 11 components.
**[22:34:10] [Server thread/INFO]: [dynmap] Stopping map renderer...**

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:57
Duplicate of #3434

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:57
Linking that thread as it has more information

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:57 UTC
Labels: Duplicate

**Comment by seema84** [comment] 2021-08-20 17:24
i am not sure if it is really the same problem

**Comment by seema84** [comment] 2023-07-16 14:46
the problem still exists (Paper Build - 1.20.1 and dynmap v3.6-899)

**Comment by seema84** [comment] 2023-11-27 17:25
Could this possibly be opened again?

I'm not sure if it's because of dynmap or the hoster/docker. My hoster uses docker containers for the Minecraft server. And sometimes it just happens that the container closes before the server is completely shut down. And this happens at exactly this point.

**Comment by JurgenKuyper** [comment] 2023-11-27 17:38
each plugin is only given 10 seconds to shutdown, if it takes longer, it just gets killed, especially apparent with sqlite as it is not fast, we recommend moving to mysql as that is really hard to corrupt, which is not the case with sqlite

**Comment by seema84** [comment] 2023-11-27 19:17
So it never takes 10s for me. Even if it takes 1-3s (for dynmap), the problem described happens.

**Comment by seema84** [comment] 2024-02-06 14:42
Can you open the issue again or should I create a new one?
