### ISSUE TITLE
Lag spikes using paper

### ISSUE THREAD

**Issue by masmc05** [webbukkit/dynmap#3723] opened 2022-03-26 08:54 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *
Paper has async chunk loading, that is performed by special threads, not by the server's thread, so planing chunk load blocks main server's thread and waits for paper's thread's response, causing lag spikes
Bellow is the spark profiler's report, and the code of paper that I think causes lag spikes, (because of paperweight i'm not sure if it's really it, but it should be the same logic, net.minecraft.server.level.ChunkMap)

Would be cool to implement better support for paper (maybe will help if "hard fork" will ever happen)
* **Dynmap Version:**  core=3.4-beta-2-761, plugin=3.4-beta-2-761
* **Server Version:** git-Purpur-1586 (MC: 1.18.2)
* **Pastebin of Configuration.txt:** *https://pastebin.com/CNDes9Up*
* **Server Host (if applicable):** *Contabo vps with pterodactyl*
* **Other Relevant Data/Screenshots:** *
![image](https://user-images.githubusercontent.com/63639746/160231624-21242f90-6c6c-4e36-a2fd-7d742cce886a.png)
![image](https://user-images.githubusercontent.com/63639746/160231581-10ad0c37-eef8-435e-a8e5-203402f426ca.png)
*
* **Steps to Replicate:**
1. Use paper, the core that is more than 90% used for 1.18.2 ([source](https://minidigger.github.io/paperstats/#1.18.2 ))

 [x] *I have looked at all other issues and this is not a duplicate*  (only until start of 2020, you have lots of closed issues)
 [x] *I have been able to replicate this*

**Comment by masmc05** [comment] 2022-03-26 10:32
saw https://github.com/webbukkit/dynmap/issues/2345 now, and idk if it's a dublicate or not, since there it unclear if it was implemented and now is broken, or it still wasn't implemented

**Comment by mastermc05** [comment] 2022-03-27 06:05
if you don't see your world in worlds.txt, then execute `dmap worldset worldname title:<label>`, where label is a custom name for the world, like "Overworld", then your world will appear in worlds.txt 
after that, search for all `perspective: <name>_<resolution>` and change resolution to a better one, and save worlds.txt
and finally, restart the server, purge rendered data, and redo a fullrender for the world
resolutions are: (resolution-explanation, higher scale, better quality in zoom, more lags from render)
vlowres - very low resolution (scale:2)
lowres - low resolution (scale:4)
medres - medium resolution (scale:8)
highres -high resolution (scale:16)

**Comment by generrosity** [comment] 2022-03-27 08:13
It wasn't implimented, it was placed in the [Feature Request Megathread](https://github.com/webbukkit/dynmap/issues/3461#issuecomment-902376617) as either it needs someone more specific to help impliment it (also as we don't have a paper-specific-build but that is easier to set up) or isn't high on the feature list as we only really have one in-their-free-time dev.

**Comment by mikeprimm** [comment] 2022-03-27 14:22
A paper specific fork is beyond unlikely, and would not be supported.   I can see if we could conditionally handle a subclass of the version specific code (which we need to do because the Spigot/Paper API is quite inadequate and has long standing bugs that prevent its use - specifically around the disfunction of the 'no-generate' behavior in the chunk APIs since 1.13.2, and the perpetual lack of NBT access), but it will be a question as to whether it is worth the extra testing and support on our part.

**Comment by masmc05** [comment] 2022-03-27 17:00
I think it's worth it, because most servers use paper, or paper forks, a lot more than spigot, and in that case, it's only a question should be this code run on server, or async on your threads, so I can see 1 simple solution:
1. store a static final boolean variable if paper is available
2. the callables that on paper would need to wait for paper threads, are stored in a variable
3. if it's paper, the callable runs on the same thread, if it's not, the callable is sent to scheduler 

That would add like 2-3 lines of code in such places, just need someone who knows where that wait can happen

**Comment by masmc05** [comment] 2022-03-27 17:43
or, after seeing the code, seems like not that easy

**Comment by mikeprimm** [comment] 2022-03-27 19:47
Yep - it isn't.  And it needs to be split so that the dependency on classes defined in Paper doesn't cause class loader errors when loading/resolving the methods/classes referring to them.   Can be done, but isn't anything like '2-3 lines of code'

**Comment by mikeprimm** [comment] 2022-03-27 19:49
BUT, if you wanna do a PR that is tested and functional on all Paper and Spigot releases since 1.10.2, I'll be happy to accept it ;)

**Comment by masmc05** [comment] 2022-03-28 07:01
> BUT, if you wanna do a PR that is tested and functional on all Paper and Spigot releases since 1.10.2, I'll be happy to accept it ;)

well, i might try if on my easter school holiday i'll have free time, i really like this plugin so i think it will be an useful experience to make that pr

**Comment by masmc05** [comment] 2022-03-28 07:03
but even if i'll make it, i think i would make it only for latest version, but without breaking old versions, i don't think i'll have enough time to make for all versions

**Comment by FedUpWith-Tech** [comment] 2022-04-05 15:06
Going to go ahead and close this now since while it is not wanted behavior it is expected and "not a bug"

**Closed as completed by FedUpWith-Tech** 2022-04-05 15:06 UTC
Labels: Answered, Support Question

**Comment by masmc05** [comment] 2022-04-09 13:17
> Going to go ahead and close this now since while it is not wanted behavior it is expected and "not a bug"

oh, yeah, also my pr fixed this, so totally good
