### ISSUE TITLE
Black stripes

### ISSUE THREAD

**Issue by AshKiano** [webbukkit/dynmap#3246] opened 2021-01-16 21:55 UTC
Hi, 
I have a problem with black stripes and black tiles on my dynmap. I have fully generated world by worldborder plugin and 3 times rendered a dynmap and they are still there. Link: http://panda.hostify.cz:49102
How can I repair this?
Thanks

**Comment by masterX244** [comment] 2021-01-19 09:06
worldborder has a issue when it gets paused and resumed by a server reboot. Due to how 1.13+ does its chunkgen it skips a stripe of partially generated ones. those cause the renderbugs. Only fix is them getting loaded fully. (either with a player or with a different method of chunkloading, player can be bot-ed to teleport-sweep across the map)

For future pregeneration use the chunky plugin since that handles this case correctly

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:48
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:48 UTC
Labels: Duplicate
