### ISSUE TITLE
Black banner on zoom out view

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [webbukkit/dynmap#2853] opened 2020-04-07 06:31 UTC
Server version
```
[INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```
Dynmap version
```
Dynmap-3.0-beta-10-spigot.jar
```

This is the problem tile, 1Mbps so wait after zoom until download  
http://americansdyg.imdo.co:22780/index.html?worldname=world&mapname=flat&zoom=1&x=1552&y=64&z=322

![image](https://user-images.githubusercontent.com/10773245/78636426-e3e71f80-78da-11ea-913a-eacd0432565e.png)

But when zoom in,
![image](https://user-images.githubusercontent.com/10773245/78636448-ee091e00-78da-11ea-874c-fb9467715df8.png)

The black zoom level is `&zoom=1`, and there is still many black tiles after zoom in,  
keep zoom in, the black will all disappears at `&zoom=4` .

Same issue seems https://github.com/webbukkit/dynmap/issues/2664
@PotcFdk

**Comment by D0ublek1ll** [comment] 2020-04-14 09:39
Use 
/dynmap fullrender
or fly/tp to the locations in question and use /dynmap radiusrender

**Comment by mhtvsSFrpHdE** [comment] 2020-04-17 04:09
@D0ublek1ll Already did that before but not got a fix,  so finally have submit issue here

**Comment by jounaidr** [comment] 2020-04-27 21:30
Same issue, the tiles appear when zoomed in. I attempted to full render after loading all chunks with WB, however, my server crashed multiple times during both of these which might have triggered this problem? (Also have tried full render a few more times fully without crashing after, and even radius render of the same length of the WB, and the black lines still persist...)

Before zoom:
![image](https://user-images.githubusercontent.com/52418954/80423806-7f672100-88d8-11ea-8b7c-f35a6cc1990c.png)

After zoom:
![image](https://user-images.githubusercontent.com/52418954/80423887-a1f93a00-88d8-11ea-80fc-79ff147b3887.png)

There is a small outline where the black tiles were but they appear

**Comment by FedUpWith-Tech** [comment] 2020-07-31 19:17
Duplicate of #3182

**Closed as completed** 2021-12-17 18:43 UTC
Labels: Duplicate
