### ISSUE TITLE
Compability with Disguise-Craft

### ISSUE THREAD

**Issue by o0Julia0o** [webbukkit/dynmap#2395] opened 2018-12-03 19:19 UTC
can you make it compatible with: Disguise-Craft: https://dev.bukkit.org/projects/disguisecraft?gameCategorySlug=bukkit-plugins&projectID=37008

On the dynmap your are shown with your normal name + skin.. so you can get unmasked :(

thx

Julia :)

**Comment by Psy-Virus** [comment] 2018-12-03 19:41
This link is also dead. Please update it.

:)

**Comment by Psy-Virus** [comment] 2018-12-03 19:42
Also Disguise-Craft is for 1.8.3. @mikeprimm, What versions are not supported anymore?

**Comment by generrosity** [comment] 2018-12-03 21:12
@Psy-Virus it does look from the builds folder he is compiling against 12.2, 11.2, 10.2, 9.4, and 8.9

Looks like this was released recently for 1.8.8, not 1.8.9 - OP may need to confirm what version they are using too

**Comment by Psy-Virus** [comment] 2018-12-03 22:31
Oops, thought @o0Julia0o wrote that last one :D
Didn't mean u to update anything, @generrosity `~.~`
Read too many names and issues today.... time to sleep.
Good night, community!

**Comment by mikeprimm** [comment] 2018-12-04 16:01
@generrosity has the right list - for Spigot, the list is logically the same (1.8.9 or later, essentially, including 1.13.2).  Paper also seems to work (as a Spigot fork, this is not surprising), but it isn't a routine part of my regression testing.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 02:13
Closing this since DisguiseCraft is no longer maintained and Dynmap will soon not support any version it supports

**Closed by FedUpWith-Tech** 2021-08-20 02:13 UTC
Labels: Mod specific, Feature Request
