### ISSUE TITLE
Moving/Disappearing Marker

### ISSUE THREAD

**Issue by ShaneBeee** [webbukkit/dynmap#2145] opened 2017-10-17 20:23 UTC
I have moved my worlds spawn chunks to a remote island, to prevent players from building near spawn and benefiting from always loaded chunks. 
Now, my ACTUAL spawn is at 0,0 and I have moved the spawn marker to there, yet on reload it pops back up at the remote island.

If i DELETE the spawn marker, it shows that it goes away, yet again on reload it goes away!
If i call up a dmarker list, it shows th spawn one, even though I deleted it.

If i CREATE a new marker, lets call it HOME... it shows up on the map, i click reload, and its gone! It also shows up on the list.

Not really sure what is happening here.

**Comment by SimonOrJ** [comment] 2017-10-24 00:21
It's a known issue.  For the time being, do **not** reload dynmap when working with markers.  It's a mess I had to deal with for months.  Do a server restart instead.

References: #1956 #2091 
Might be related: #1422 #1557 #1936

**Comment by ShaneBolenback** [comment] 2017-10-24 01:40
Duly noted.  Thank you very much for replying!

**Comment by FedUpWith-Tech** [comment] 2020-07-28 18:22
Duplicate of #1936

**Closed by FedUpWith-Tech** 2020-07-28 18:22 UTC
Labels: Bug, Duplicate
