### ISSUE TITLE
Full render shows weird black snakes

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2305] opened 2018-08-27 07:54 UTC
Hey,

For some reason my dynmap shows weird black snake figures.

How could I fix this?

http://mc.villagercraft.nl:8050

**Comment by lukeeexd** [comment] 2018-08-27 09:48
Also getting this 

https://i.imgur.com/06cKlsm.png

**Comment by smmmadden** [comment] 2018-08-27 10:59
which version of server are you running on and which version of Dynmap are you using.  If 1.13 or 1.13.1 make sure you are using the latest alpha version for these releases.  Also if you can get in-game details as to what blocks are present in the black generation, it will help.

**Comment by lukeeexd** [comment] 2018-08-27 11:01
1.13.1 latest alpha version. I've disabled dynmap now I can't get the blocks I'm afraid

**Comment by Sikatsu** [comment] 2018-08-27 11:10
In my case blocks don't matter. Running 1.13. Radiusrender works fine, but takes sooo long to manually go to each place and run a radiusrender.

**Comment by Sikatsu** [comment] 2018-08-27 12:35
Also if you check my spawn and mobarena dynmap, the edges are generated in a weird way. How could I fix this?

**Comment by mikeprimm** [comment] 2018-08-27 18:41
Your map looks like the artifacts of a known issue we've seen with using 'WorldBorder' - and the /wb fill function in particular.  I'm not sure which is at fault - a lot has changed on the internals of world generation with 1.13 - but it appears as though chunks at the edge of the 'normally explored' (or previously explored) areas don't load when requested via the APIs when the load is restricted from causing chunk generation (as it is with dynmap), but they seems to not be recognized as needing more work to be 'finished' by /wb fill, so you wind up with a border of chunk that cannot be loaded by dynmap AND which don't get 'finished' (classically called 'populated' - as in adding trees as such) by /wb fill.  For dynmap's part - all we do is ask to load the chunks, so long as loading them doesn't cause them to be generated, same as we have for several years: if Spigot says 'no', then it doesn't get loaded and we cannot draw it.  If WB is also getting confused as to what/whether those chunks need more work in order to be 'done, then WB and Spigot are kind at an impasse (and dynmap, who only reads world data - it doesn't create it) is not in a position of doing anything.  My money is on a behavior change in Spigot, since clearly 1.13 churned a lot of internals - I'm hoping to find some time to crawl into the Spigot/WB code to see if I can help fix the issue, but I know the solution isn't gonna come from Dynmap.  The other tip-off is that, on the edge of the world, you see chunks with clipped trees - this is VERY new behavior, in that the border chunks in all previous MC versions were loadable (without being generated) but always lacked the 'populated' features, like plants and trees, which can extend outside the border of the chunk itself.

**Comment by Sikatsu** [comment] 2018-08-27 18:51
I did indeed make use of /wb fill.

What I basically did was /wb world2 fill from the console and when it said 100%, I did /dynmap fullrender world2

When I woke up it looked like this with black snakes or however we should name it. 

As for the spawn and mobarena dynmap's, I also used /wb fill but when trying to use /dynmap fullrender on them, it said immediatly "Completed" within the same second. Nothing was rendered so I used radiusrender instead. However, using radius render the borders look weird as you can see.

Now I don't fully understand your message, but if there would be any fix in the future, what would I have to do?

**Comment by mikeprimm** [comment] 2018-08-27 22:39
The trick right now is that those chunks aren't showing as 'loadable without generating', as far as the Spigot API is concerned.  If you fly a character over some of those chunks (inside the 'black snakes'), and then do a render, I suspect they will render (since your character flying within 10 chunks of them will cause them to be generated AND populated by the vanilla code - which itself is not dependent upon the spigot API) - this is what others have seen, and is consistent with the notion that the chunks are only partially generated, not reporting as loadable without being fully generated, and are being overlooked by /wb fill as needing further attention.

**Comment by lukeeexd** [comment] 2018-08-29 12:15
I'm getting them too but didnt do /wb fill. I had done /wb fill on 1.12.2 about a month ago, now I'm getting the snakes on 1.13.1 on latest dynmap https://tws-mc.com/map.html

**Comment by smmmadden** [comment] 2018-08-29 12:32
I agree with Mike on this, this issue was reproducible and was resolved (at least for me) by joining the game, flying to the areas of black blocks and go around the whole area (where no blocks are shown) and force the generated blocks to dynmap.  I had several areas like that and it resolved that snake like issue.

Can you type in **/version** so we see what server/version you are running on and also **/dynmap version** and paste in both results here?  Thanks!

**Comment by lukeeexd** [comment] 2018-08-29 12:34
@smmmadden

**Comment by smmmadden** [comment] 2018-08-29 12:38
Thanks for that, the steps we both outlined should resolve it for you as well.  I'm using the same version of Dynmap (build 88) and PaperSpigot build 187. Previously was on Spigot 1.13.1 builds.

**Comment by lukeeexd** [comment] 2018-08-29 12:45
Will being in spectator work when flying or need to be in survival?

**Comment by smmmadden** [comment] 2018-08-29 12:47
I did mine in survival mode, but just enabled flying for me (/fly).  I'm not sure if spectator mode would be an event that would force generated chunks.  Best way to tell is trying one section and see if the map updates a few minutes after you've done it.

**Comment by mikeprimm** [comment] 2018-08-29 14:19
I'll find some time this weekend to put on my old 'Spigot dev' hat and see if I can run the root cause for this to ground (and hopefully provide a fix - whether to Spigot or to WorldBorder).

**Comment by smmmadden** [comment] 2018-08-29 15:43
excellent, thank you :-)

**Comment by lukeeexd** [comment] 2018-08-29 17:53
More and more keep appearing. I cant get rid of them fast enough lol. There's not even a border on the world when I turned on dynmap

**Comment by lukeeexd** [comment] 2018-09-01 20:28
So I purged my whole dynmap, theres no world border and I'm still getting the black areas https://tws-mc.com:8123/ as you can see around spawn I did a radius render and theres black areas that wont render

**Comment by Psy-Virus** [comment] 2018-09-01 21:29
TL:DR but have you ever been standing in the black spots? Are the chunks generated?

**Comment by Psy-Virus** [comment] 2018-09-01 21:36
Okay, you were standing in the black spots. But usually it takes some time for the zoom tiles to get rendered. They're not as fast as the full zoom in tiles.

**Comment by lukeeexd** [comment] 2018-09-02 18:26
Currently doing a fullrender https://tws-mc.com:8123/ looks like the snake things are still happening

**Comment by mikeprimm** [comment] 2018-09-03 16:30
OK - people with 'black snakes' problems: I believe you can workaround the WB issue by rerunning the /wb fill operation with the force option set to true (e.g. /wb world fill 20 208 true). The bug is tied to the fact that the logic for determining whether a chunk NEEDS to be generated is:

a) not right for 1.13.x, even though it was right for 1.12 and earlier, and
b) leaves the world in a state where a simple fix to the WB fill algorithm (checking for protochunks in a 3 chunk radius) no longer works, meaning the simple fix for WB will not fix you

In any case, the 'force' option tells WB to load every chunk vs assuming it can tell which ones need loading in order to be generated: for chunks already generated, this is harmless - it just generates load and makes the process take longer - but it should both fix the 'black snakes' (if you already have run /wb fill), or avoid it while WB is fixed (if you haven't run /wb fill yet).

**Comment by lukeeexd** [comment] 2018-09-03 16:45
Fixed in latest paper build

**Comment by mikeprimm** [comment] 2018-09-03 17:02
For those looking for more technical details - https://github.com/Brettflan/WorldBorder/issues/101

**Closed** 2018-09-04 02:52 UTC
