### ISSUE TITLE
Glitchy rendering when chunks just beyond a fullrender got created

### ISSUE THREAD

**Issue by masterX244** [webbukkit/dynmap#2766] opened 2020-01-25 10:09 UTC
When a player explores just beyond a fullrendered section there are map-gaps
![grafik](https://user-images.githubusercontent.com/1544922/73119487-fb14a300-3f62-11ea-995f-fd5972026d2c.png)
Tested on 1.15.1 spigot with 3.0-Beta 9

**Comment by ekzhang** [comment] 2020-03-20 17:47
Can confirm this happens in the latest version for 1.15.2.

**Comment by FedUpWith-Tech** [comment] 2020-07-31 18:44
maybe related to #2485

**Comment by FedUpWith-Tech** [comment] 2021-08-20 14:47
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 14:47 UTC
Labels: Duplicate
