### ISSUE TITLE
Weird Render Issue 

### ISSUE THREAD

**Issue by Ayymoss** [webbukkit/dynmap#3003] opened 2020-07-01 20:49 UTC
https://i.imgur.com/vUxGvh3.png
Not sure how else to explain it, like 95% of the render is fine, no issue. But this and another small part of the map looks like that.

Can you fix or tell me how to fix it?

I tried to purge all and re-render the entire world.

Cheers.

**Comment by jacob1** [comment] 2020-07-02 15:58
Also having a similar issue on the 1.16.1 beta. Here is an example of some newly generated chunks:
![dynmap render issue](https://user-images.githubusercontent.com/1139178/86380884-9fa9b800-bc5a-11ea-8452-54d308e35337.png)

I previously re-rendered the whole map after getting the latest 1.16.1 beta, so that's why the right edge of this picture looks fine.

I don't remember the issue happening to this scale in prior versions. I've been seeing this issue just from flying around in creative to generate chunks on a new world.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 23:43
```
This issues is a result of using Paper and not Spigot, paper uses async chunks (enabled by default in the config) which dynmap doesn't have support for. The issue to add support for this is #2345

You can either go back to paper, disable async chunks, wait for async support, or wait for dynmap to do a /dynmap fullrender :P
```
This was my original reply which is wrong. Leaving it in place for history. Editing it so others don't try this.

**Comment by jacob1** [comment] 2020-07-29 02:33
Are you saying this issue only happens in Spigot, or only happens in Paper? I can't tell. I use Spigot, not Paper, and saw this issue.

Async loading support for Paper would be nice, but the status quo of non-async loading used to work.


I've noticed the issue is worst in the overworld flat map, and barely present in other maps such as overworld 3d or nether. My guess is it has to do with the speed of rendering. Mine renders more tiles at once than the default.

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:58
Duplicate of #2075

**Closed as completed** 2021-12-17 18:59 UTC
Labels: Duplicate
