### ISSUE TITLE
Black Concrete Powder not showing on map

### ISSUE THREAD

**Issue by Azza007** [webbukkit/dynmap#2235] opened 2018-05-12 08:26 UTC
One of my players alerted me to an issue with Concrete powder not showing up on the live map. I tried to render the area where it was used again and it didn't work. Below are images of the block in the game and on the Dynmap.
![dynmap error](https://user-images.githubusercontent.com/16065712/39955448-d0f36cbe-5611-11e8-99df-31f38b0e257a.PNG)
![2018-05-12_18 24 22](https://user-images.githubusercontent.com/16065712/39955453-ddced1da-5611-11e8-86c4-e5931da8a541.png)

**Comment by FedUpWith-Tech** [comment] 2020-07-28 17:59
Duplicate of #2120

**Closed by FedUpWith-Tech** 2020-07-28 17:59 UTC
Labels: Duplicate
