### ISSUE TITLE
Dynmap update render issue

### ISSUE THREAD

**Issue by JHarris12345** [webbukkit/dynmap#3032] opened 2020-07-21 04:36 UTC
Update render seems to finish immediately despite there being large corners of the map not fully rendered

**Comment by FedUpWith-Tech** [comment] 2020-07-23 15:00
updaterender only renders loaded chunks not all chunks- you have to run a fullrender to render all chunks

**Comment by TNTUP** [comment] 2020-07-31 09:43
I can confirm on this. ![IMG](https://i.qcfb.ca/20200731054125.png)

That seems to happen with the 3D render view, when the render reaches 1-month render time it stops. See the above screenshot. 

I don't know about JHarris's render time but I can confirm if the render takes too long to render 1month+ it stops.

**Comment by FedUpWith-Tech** [comment] 2020-08-01 21:53
@TNTUP  The render stopping after a month is very unrelated to this so should be its own separate issue. I recommend going to the corner and doing a radiusrender. Since the author didn't reply I'm going to close this but please open a separate issue for the render stopping (albeit that will be a very hard issue to resolve due to the incredibly long render times required to test)

**Closed as completed by FedUpWith-Tech** 2020-08-01 21:53 UTC
Labels: Answered, Support Question
