### ISSUE TITLE
Underwater Lightning Bug

### ISSUE THREAD

**Issue by hanfland** [webbukkit/dynmap#2726] opened 2019-12-24 19:20 UTC
![grafik](https://user-images.githubusercontent.com/59209363/71423581-a2fc2f80-268a-11ea-9d86-9f8801127a9a.png)
Is it a Bug or can i solve that in the settings?

**Comment by Uight** [comment] 2019-12-27 11:58
Same here. For me it happens in lukewarm ocean when the water is deeper than 15 blocks the color gets real bright an you can the ground. First happend in beta 8 and still in beta 9.

**Comment by ghost** [comment] 2019-12-28 11:58
Duplicate of #2702

**Comment by Uight** [comment] 2019-12-28 22:46
![image](https://user-images.githubusercontent.com/46501936/71550258-13c58380-29cc-11ea-9974-8ba349261b21.png)
For me it also only happens to maps that are pre 1.14. It appears to be so if i use the radiusrender but not if i build normal. Can be seen at the ship its normal cause i build there but around it i used radiusrender

**Comment by mpdk** [comment] 2020-01-14 06:17
Same problem here, tried with the new dev build, and still the same

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:26
Linked issue was fixed

**Closed as completed by FedUpWith-Tech** 2021-12-17 18:26 UTC
Labels: Bug, Fixed, Render Issues, World Conversion
