### ISSUE TITLE
Allow Maps to Individually Specify Visibilitylimits, Hiddenlimits, and Center Parameters

### ISSUE THREAD

**Issue by Agentomega** [webbukkit/dynmap#3248] opened 2021-01-19 04:22 UTC
**Feature Description:** Suggest ability to apply/override world visibilitylimits, hiddenlimits, and center on individual maps.

* **Additional context:** My base is predominantly underground (on the overworld), so I determined the x/z min/max and the y-level of my ceiling, and tried adding restrictions to additional maps (so I could have an underground view of just my base).  Was able to specify custom perspective just fine for the Y-value cutoff, but the maps render the entire underground.  I don't want all of the underground visible, since that may reveal resources and other structures to other players, but I also do not want to apply visibilitylimits to the entire overworld, just the underground perspective.  (I doubt this suggestion will make it to the version of dynmap I'm using [Dynmap-2.6-beta-1-forge-1.7.10.jar], but it seems like it'd be a useful feature ongoing.)

**Comment by FedUpWith-Tech** [comment] 2021-08-20 03:23
Duplicate of #2926

**Closed as completed by FedUpWith-Tech** 2021-08-20 03:23 UTC
Labels: Duplicate
