### ISSUE TITLE
Definitely not rendering all chunks

### ISSUE THREAD

**Issue by emiliogon** [webbukkit/dynmap#3007] opened 2020-07-03 14:47 UTC
Hello - first off, this is an impressive tool, especially with how easy it is to install!  However, I'm having persistent issues with map coverage.

**Specs:** Linux, Spigot 1.16.1, available disk space; forced map update when upgraded to 1.16.1; small number of typical plugins (EssentialsX, LuckPerms, Multiverse, WorldGuard, WorldEdit)

This is a map I created years ago with another tool:

![overworld 20130919](https://user-images.githubusercontent.com/21245821/86478400-37211080-bd18-11ea-8de8-3745c41da567.png)

This is what Dynmap has made, despite numerous "fullrender" and "radiusrender" attempts:

![Screen Shot 2020-07-03 at 10 29 23](https://user-images.githubusercontent.com/21245821/86478575-6c2d6300-bd18-11ea-8f44-b1fb905a63c7.png)

See where my character is?  That was empty until I traveled down there and manually issued a render command.

I have set a number of areas to be force-rendered, and most of them are left completely _unrendered_:

```
worlds:
  - name: realm
     fullrenderlocations:
# olympus
       - x: 1940
         y: 64
         z: -816
# funkytown
       - x: 61
         y: 64
         z: 359
# shrooms
       - x: -5995
         y: 64
         z: 2283
# frontier
       - x: -3792
         y: 64
         z: 2283
# village
       - x: -1140
         y: 64
         z: -110
# town south
       - x: 0
         y: 64
         z: 600
# town north
       - x: 0
         y: 64
         z: -600
# town east
       - x: 600
         y: 64
         z: 0
# town west
       - x: -600
         y: 64
         z: 0
```

Note that other map styles seem to be bound to similar areas.  One strange thing is that the flat map style completes fairly quickly, while the surface map style seems to render many, many tiles, yet never seems to show any more than the areas the flat map does.

![Screen Shot 2020-07-03 at 11 02 27](https://user-images.githubusercontent.com/21245821/86480975-17401b80-bd1d-11ea-84fd-07ee3b42c48d.png)

This render is still running, yet the map never seems to change (I have purged the maps, twice):
```[15:05:16] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'realm' in progress - 20400 tiles rendered (117.09 msec/tile, 84.01 msec per render)```
The map above does not look like it has over 20,000 tiles in it.

How can I get Dynmap to render every available chunk without having to traverse them in-game?

UPDATE: ``migrate-chunks: true`` did not seem to change anything, though I did verify it was enabled via the log file.
UPDATE 2: adding ``bigworld: true`` to the world settings didn't change anything.

**Comment by HeavenCrafter** [comment] 2020-07-04 18:09
You're supposed to preload the chunks.

https://www.reddit.com/r/Dynmap/comments/hi70it/an_overly_detailed_post_for_first_time_dynmap/

**Comment by emiliogon** [comment] 2020-07-05 18:14
Hi Heaven, thanks for the response.

From what I understand, preloading generates all the chunks in an area?  I don't think that's what I need, as there are vast areas of this world that have already been explored and built in.  I just want dynmap to show the chunks that already exist, and filling in the bounds of this rather large map would make for a huge increase in disk space.

Strangely, rendering the nether seems to have no such issues; as far as I know, this is the explored bounds of the Nether.

![Screen Shot 2020-07-05 at 14 12 15](https://user-images.githubusercontent.com/21245821/86539341-9d00ca00-bec9-11ea-96fb-5f60dd8487b4.png)

**Comment by retep998** [comment] 2020-07-09 05:15
Since you say you generated a map for your world years ago, it leads me to believe your chunks are in an older format and dynmap is unable to load and render those chunks until a player has been near them for Minecraft to upgrade them.

**Comment by emiliogon** [comment] 2020-07-10 00:04
Ahh, that's what I was wondering.  I thought Spigot's `--forceUpdate` or Dynmap's `migrate-chunks` would have taken care of that.

Do you know if there's a way to upgrade all of the chunks without players?

**Comment by FedUpWith-Tech** [comment] 2020-07-31 22:12
Duplicate of #2282

**Comment by TNTUP** [comment] 2020-08-16 04:24
Can confirm.

**Closed as completed** 2021-12-17 19:00 UTC
Labels: Duplicate
