### ISSUE TITLE
I wrote a more updated wiki to setup for debianwith apache. Includes SSL.

### ISSUE THREAD

**Issue by Eviepayne** [webbukkit/dynmap#2739] opened 2020-01-03 04:56 UTC
update this > Setting-up-Dynamic-Map-with-apache2-under-Debian.md

In order to continue please make sure the following are completed:

* You have apache2 installed.
* Your www-root directory is: `/var/www/html/`.
* You could access your Dynmap-map succesfully through *http://localhost:8123/* or http://local-network-ip:8123
* SSL is properly configured for your domain. We recommend Lets Encrypt, configured automatically with certbot.

This guide will make your dynmap work using http or https.

* To start, navigate to directory `/var/www/`.

Any parts needed for SSL will be identified with a "!"

Now, we need to enable the modules we need. Type in bash:
```bash
    sudo a2enmod rewrite proxy_http
```

Next, we must reverse proxy to dynmap's internal webserver. To do this, make sure you have the following in `/etc/apache2/sites-available/000-default.conf`:
!If you are using SSL, default should be your SSL configuration file. Lets Encrypt's file is 000-default-le-ssl.conf

```apache
    ...

    ProxyRequests off
    ProxyPass / "http://localhost:8123/"
    ProxyPassReverse / "http://localhost:8123/"
    ...
```

Restart apache2 (`sudo systemctl restart apache2`).

You should now be able to access dynmap with `http://domainname.com/` or `https://domainname.com`

**Comment by depwl9992** [comment] 2020-03-04 20:27
I, too, had an issue with the rewrites, alias, and proxy definitions in the 9yo tutorial on making this work. Really just kept getting 404 errors. Confirmed - this works both on http and https.

Are you sure the symbolic link is necessary, though? Assuming that dynmap's internally hosted HTTP server could be proxied to without linking `minecraft/plugins/dynmap/web/` to a different directory, or really, frankly, even caring where that directory is to begin with, I got this to work with only the Proxy directives in the conf files. `/var/www/dynmap/` doesn't even exist as a folder or link in my instance. It just proxies any request on `/dynmap` to `http://localhost:8123`.

**Comment by Eviepayne** [comment] 2020-03-04 20:31
I did leave it there because that's what worked for me but I think you're right. I don't think the symbolic link is necessary.

**Comment by DaNeubi** [comment] 2021-04-28 20:32
I just got it working for my setup.
My setup is a bit more complicated with a reverse proxy in front of the webserver, but this should work just fine without one.

I'm using Let's Encrypt to get my Certificate

This is my dynmap.conf file in `/etc/apache2/sites-available`

You need to edit`<yourdomain>` to your actual domain.

```
<IfModule mod_ssl.c>
        <VirtualHost *:443>

                ServerName <yourdomain>

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
                SSLEngine on

                ProxyRequests   off
                ProxyPass / http://localhost:8123/
                ProxyPassReverse / http://localhost:8123/

                SSLCertificateFile /etc/letsencrypt/live/<yourdomain>/fullchain.pem
                SSLCertificateKeyFile /etc/letsencrypt/live/<yourdomain>/privkey.pem
                Include /etc/letsencrypt/options-ssl-apache.conf
        </VirtualHost>
</IfModule>

<VirtualHost *:80>
        ServerName <yourdomain>

        Redirect permanent / https://<yourdomain>
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =<yourdomain>
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by JurgenKuyper** [comment] 2022-08-11 13:09
closing this since this got implemented in: https://github.com/webbukkit/dynmap/wiki/Dynmap-with-apache2-on-Debian

**Closed as completed by JurgenKuyper** 2022-08-11 13:09 UTC
Labels: Doc improvement

**Comment by Eviepayne** [comment] 2022-08-11 13:32
I just read the article again and this has not been correctly implemented.
its still wildly wrong.

**Comment by JurgenKuyper** [comment] 2022-08-11 13:33
with what then? because it has the info in your initial message in it.

**Comment by Eviepayne** [comment] 2022-08-11 13:37
As I'm reading it now it still says to make the /srv directory.

It literally hasnt changed at all

**Comment by JurgenKuyper** [comment] 2022-08-11 15:03
done, didn't see the differences earlier.
