### ISSUE TITLE
Dynmap fails on Spigot 1.20.3 and 1.20.4

### ISSUE THREAD

**Issue by mischi3f** [webbukkit/dynmap#4042] opened 2023-12-11 17:51 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap errors out on load of Spigot version 1.20.3 and Spigot 1.20.4.*

* **Dynmap Version:** *v3.7-beta-2-923*
* **Server Version:** *spigot-1.20.3 AND spigot-1.20.4*
* **Pastebin of Configuration.txt:** *https://pastebin.com/2f5s0p9F*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/MaSNmxr4*
* **Other Relevant Data/Screenshots:** *the errors began on Spigot update 1.20.3 and continued into 1.20.4*
* **Steps to Replicate:** *update server to 1.20.3 (or .4) and start*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by hiyakake** [comment] 2023-12-12 04:16
I'm the same.

I hope this problem will be resolved as soon as possible.

**Comment by silentlexx** [comment] 2023-12-12 08:54
Same on papper 1.20.4

**Comment by timmclaurin** [comment] 2023-12-12 18:53
Wish there was simply a counter for 'me too'... but here we are. Thanks for all the work on this great tool. 

I have the same issue on Paper 1.20.4-326 but not on paper 1.20.4-319

Again, paper-1.20.4-319 does not have this issue.

**Comment by luftwafflezz** [comment] 2023-12-14 13:45
Can confirm. I'm having the same problem on git-Paper-328 (MC: 1.20.4). It seems to be back.

**Comment by JurgenKuyper** [comment] 2023-12-14 17:13
Dev build for Spigot/Paper with 1.20.4 support available - https://dynmap.us/builds/dynmap/Dynmap-3.7-SNAPSHOT-spigot.jar

**Comment by timmclaurin** [comment] 2023-12-14 17:27
Confirmed working with paper-1.20.4-328

**Comment by mischi3f** [comment] 2023-12-16 19:01
> Dev build for Spigot/Paper with 1.20.4 support available - https://dynmap.us/builds/dynmap/Dynmap-3.7-SNAPSHOT-spigot.jar

Confirmed this works for Spigot 1.20.4. Thank you!

**Comment by luftwafflezz** [comment] 2023-12-17 14:22
@mischi3f Are you going to close the issue then, if it is indeed resolved?

**Closed as completed** 2023-12-17 14:31 UTC
Labels: Bug Report
