### ISSUE TITLE
Slow render can't keep up.

### ISSUE THREAD

**Issue by Jelles** [webbukkit/dynmap#2535] opened 2019-06-30 18:22 UTC
I have a dynmap on my server on 1.14.2 I've done a full render and it's rendered a good amount now. When loading new chunks on the map this is very slow and it doesn't hold up with the player. This may be a bug or I somehow missed a setting.

**Comment by Jelles** [comment] 2019-06-30 19:28
Example of the 3D rendering (not pre loaded)
![image](https://user-images.githubusercontent.com/27337258/60401185-f11df380-9b7d-11e9-9431-75963bcf878b.png)


And here new chunks on the pre loaded map:
![image](https://user-images.githubusercontent.com/27337258/60401191-0c88fe80-9b7e-11e9-97e2-77a33bfe54fe.png)

**Comment by Jelles** [comment] 2019-06-30 19:29
Server has an i5-7400 and 8 GB of ram.

**Comment by ghost** [comment] 2019-07-02 17:03
Don't know what you are talking about as dynmap seems to work perfectly fine on 1.14.3. Check out this render just from [half an hour of running](https://i.imgur.com/BLVdOmc.png). Now after letting it render overnight the whole world is rendered.

**Comment by ghost** [comment] 2019-07-02 17:03
PaperSpigot 1.14.3 on i7-2600 with 16 GB of ram.

**Comment by Jelles** [comment] 2019-07-03 23:31
Thanks for your reply @Speentie8081 how do you load your map does this go automatically or do you manually do this and if so how do you do this?

**Comment by ghost** [comment] 2019-07-04 15:21
I ran a full render of the world after letting WorldBorder generate all the chunks, the only issues i'm having has to do with lighting.

**Comment by Jelles** [comment] 2019-07-04 16:51
And for a regular survival server do I have to run the full render every time new chunks get loaded? Because my server can't even render 1 player generating new chunks on the map and a full render takes ages so in order to update the dynmap is there no other way to do so? @Speentie8081

**Comment by ghost** [comment] 2019-07-04 19:53
/dynmap updaterender (world) 
This only works after WorldBorder has generated all the chunks for the world and you've run a full render. It's almost instant but the one time full render takes almost a week.

**Comment by ghost** [comment] 2019-07-06 14:11
I also have been experiencing this issue and after investigating the issue I found that PaperLib is outdated.
PaperLib has not yet been updated to 1.14 and that's why WorldBorder was not loading chunks correctly.
In my modified version of WorldBorder I replaced all use of PaperLib with direct paper api access.
The benefit is now all chunks are loaded correctly and map is full on dynmap, but only on PaperSpigot.
My modified version of WorldBorder is only compatible with PaperSpigot, not Spigot or CraftBukkit.
[WorldBorder modified to support Paper 1.14.3 + Dynmap 1.14.3](https://ci.skorrloregaming.com/view/dynmap/)

[Before using modified WorldBorder](https://i.imgur.com/JEJTqeI.png)
[After using modified WorldBorder](https://i.imgur.com/F7wJTcq.png)
The only issue remaining for me is an unknown lighting issue that none of my friends can reproduce.

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:10
Duplicate of #2075

**Closed as completed by FedUpWith-Tech** 2021-12-17 18:10 UTC
Labels: Render Issues
