### ISSUE TITLE
Sign Mark can't be removed.

### ISSUE THREAD

**Issue by ShulkerSakura** [webbukkit/dynmap#3090] opened 2020-08-15 06:14 UTC
I set "enablesign: true" in the configuration and placed a sign with [dynmap] in the first line in Minecraft. It successfully created a sign in dynmap, but when I removed the sign, the mark on the dynmap has not been removed.
![Screenshot_20200815-141417](https://user-images.githubusercontent.com/50770360/90306614-a1c19080-df01-11ea-8970-c66c0bf0384e.png)

**Comment by FedUpWith-Tech** [comment] 2020-08-15 20:44
Duplicate of #2473

**Closed as completed** 2020-08-15 20:44 UTC
Labels: Bug, Duplicate
