### ISSUE TITLE
Black (unloaded) chunks on the map with a pattern

### ISSUE THREAD

**Issue by DelighteDev** [webbukkit/dynmap#2755] opened 2020-01-18 04:49 UTC
I am new to WorldBorder and Dynmap.
I pre generated a 5k x 5k world with worldborder then did a /dynmap fullrender.

It is showing me these blank chunks in a pattern, like this:
![image](https://user-images.githubusercontent.com/60025955/72658775-d0af6c80-39db-11ea-80d9-3d64af90c1f0.png)

I am running latest dynmap 3.0 beta 9 (Do I downgrade version?), on paper 1.14.4.

Open to any suggestions, please help! This map looks so unpolished :/
(Already tried going to those chunks to see if its a problem with the pre generation, the chunks are totally fine. The problem is on Dynmap's end. )

**Comment by johncsuti** [comment] 2020-01-20 07:20
You can try to downgrade and let us know if that helps. If not you may want to try building in an un-rendered area and see if that makes it render.

**Comment by HenrikoMagnifico** [comment] 2020-07-13 09:19
Can confirm that this still occurs using any kind of chunk-pregeneration plugin with Dynmap, even on 1.16.1 using the latest build of PaperMC.

**Comment by FedUpWith-Tech** [comment] 2020-07-31 18:40
Duplicate of #2485

**Closed as completed** 2021-12-17 18:28 UTC
Labels: Duplicate
