### ISSUE TITLE
Dynmap not rendering certain ~~chunks~~ areas.

### ISSUE THREAD

**Issue by OskarZyg** [webbukkit/dynmap#2822] opened 2020-03-23 09:54 UTC
![image](https://user-images.githubusercontent.com/56176746/77304202-01699600-6cec-11ea-9a04-c4a446254bdc.png)

This is what happens when I try to render this file. Worst of all, even when I remove these files, it still has this 'black hole'. Since this happened after I removed all tiles, I am making this an issue.

**Comment by mhtvsSFrpHdE** [comment] 2020-04-07 06:03
Try zoom in and see if it can display the tiles?  
That would be another problem that I ever meet.

Then check the chunks are actually generated, for example,  
if player not walk through a chunk, it will not generate.

**Comment by OskarZyg** [comment] 2020-04-08 15:04
Those chunks are generated, I used WB (world border) and every chunk within a 5000 block radius is loaded. Thanks for helping!

**Comment by mhtvsSFrpHdE** [comment] 2020-04-09 15:48
@OskarZyg 
https://github.com/webbukkit/dynmap/issues/2853

Is your problem related to zoom? My is a zoom problem.

**Comment by OskarZyg** [comment] 2020-04-09 21:49
Not really, however after deleting the files a second time, there's much less of these.
This may not be conclusive as I still haven't finished rendering.

**Comment by SihasJ** [comment] 2020-04-28 13:32
![Annotation 2020-04-28 184934](https://user-images.githubusercontent.com/37244367/80491992-0ec80f00-8981-11ea-83e4-69943c0840e9.png)

I'm having a similar issue. Not sure if this will help but the black square pattern reminds me of the loading square when you create a new world in single player... (introduced in 19w02a - 1.14 snapshot onwards)

> Added a **loading animation when loading a world**.
> Visualizes the **rendering of the spawn chunks**.

from [https://minecraft.gamepedia.com/Java_Edition_19w02a](url)

I used MCPaper 226, world border /wb fill 2500, dynmap v3.0-beta10 /dynmap fullrender

![Annotation 2020-04-28 190519](https://user-images.githubusercontent.com/37244367/80493703-5ea7d580-8983-11ea-82c3-494e497cdadb.png)

Here's the surface view if it helps...

**Comment by OskarZyg** [comment] 2020-05-08 17:41
I moved my server to new hardware for performance reasons, and (again) removed all the generated tiles, and then made the full render again. No improvements. However, I have noticed a lighting glitch around these areas.

Image for reference:
![image](https://user-images.githubusercontent.com/56176746/81432694-4d1cb580-915b-11ea-8e5b-f7e895a7bd43.png)
![image](https://user-images.githubusercontent.com/56176746/81432713-560d8700-915b-11ea-981c-5f14cffc0c7a.png)
My dynmap is located [here](http://oskarsmc.ddns.net:8125) in case anyone is interested in seeing this for themselves.

**Comment by OskarZyg** [comment] 2020-05-18 13:34
![image](https://user-images.githubusercontent.com/56176746/82218870-72a47e80-9914-11ea-9d61-ca745637b233.png)
Just proof that this is NOT a problem with chunks. This new thing reappeared after I purged the render and ran dynmap fullrender again.

**Comment by OskarZyg** [comment] 2020-05-18 13:39
I actually remember this happening on an old 1.13.2 server (my first server) with a similar shape (square and long rectangle going down). That server didn't use worldborder so it cant be its fault.

**Comment by pizzanakin** [comment] 2020-05-19 06:41
I seem to have a similar problem with my dynmap:
![image](https://user-images.githubusercontent.com/27926950/82292991-168d3900-99ac-11ea-8f0c-85246468fb5a.png)
![image](https://user-images.githubusercontent.com/27926950/82293028-2c9af980-99ac-11ea-87e4-98643da6c9c4.png)

It worked fine initially, because I used to have the whole map rendered without any issues. Then I also switched to a different server. That's when the issue started.

After transferring the dynmap files, the map started showing these black spots. I deleted all the tile files, and started a new render. But that didn't solve anything. The pictures are the result of that second render.

Note: The black spots appear on all zoomed levels, even when I'm zoomed in all the way

You can view the map here: https://www.libercraft.net/dynmap/

**Comment by OskarZyg** [comment] 2020-05-19 09:30
Now that @pizzanakin has mentioned it, I remember that this only started happening after I moved the server to my main PC, and then back to my server. Dynmap does appear to update these areas if there is some kind of trigger to update chunks. It is in the config, but by default it sets to players placing/destroying blocks and piston activity. My old 1.13.2 server still had the issue but it had never been moved.

**Comment by FedUpWith-Tech** [comment] 2020-07-31 19:00
Duplicate of #2485

**Comment by OskarZyg** [comment] 2020-08-07 22:53
I have found that filling with worldborder with "force" set to true results in a fix, however this is an inconvenience as it took my main pc ~5hours to get ~2000 radius. I know these chunks have existed before, and the rendering issues do not occur in chunks, but rectangular areas.

**Closed as completed** 2021-12-17 18:34 UTC
Labels: Duplicate
