### ISSUE TITLE
MySQL Support Not Working on Java 16

### ISSUE THREAD

**Issue by Chocolate1Donut** [webbukkit/dynmap#3417] opened 2021-07-02 03:38 UTC
**Issue Description:** *When using Java 16 (and possibly Java 15, but I was unable to test that), MySQL integration fails to intialize and the plugin disables.*

* **Dynmap Version:** *dynmap v3.2-beta-2-483*
* **Server Version:** *Paper 1.16.5 Build 778*
* **Pastebin of Configuration.txt:** *https://pastebin.com/VGKgc1Le*
* **Server Host (if applicable):** *DedicatedMC.io*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/Xv7pcVnG*
* **Other Relevant Data/Screenshots:** *Reinstalled dynmap from scratch and only edited server port and mysql configuration*
* **Steps to Replicate:** *Start the server using the Java 16 JVM and it will throw out the error from the pastebin and disable itself. Switching to the Java 8 or 11 JVM yields expected functionality, with dynmap connecting to the database with no issues.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by tackleza** [comment] 2021-07-13 08:33
[FYI] I'm using Paper 1.17.1 #100
Java 16 & Dynmap 3.2-Snapshot-4 with MySQL is working fine for me

**Comment by ThisIsTenou** [comment] 2021-07-13 10:44
May I ask where you got Snapshot 4 from? I only see a Beta 1  &  2 for version 3.2.
 

 
Anyways, I can confirm the reported error message, though the plugin seems to work (at least to some extent) anyways. I wasn't yet able to test it more extensively.
 

 
Imo the error should still be addressed, as I could very well imagine it leading to at least a degradation of the plugins functions or reliability.

**Comment by Chocolate1Donut** [comment] 2021-07-13 17:25
> [FYI] I'm using Paper 1.17.1 #100
> Java 16 & Dynmap 3.2-Snapshot-4 with MySQL is working fine for me

Would also like to know where you found that build. This bug is only thing holding me back from moving server to 1.17.

**Comment by ottocorrect** [comment] 2021-07-31 16:47
Is your mySQL integration still working @tackleza ? For everyone else I can confirm that I am running 1.17.1 with Paper Build #138 and Java 16 and my console is running the same error and not launching Dynmap. Since it's 1.17 I can't revert to Java 15 or lower so unfortunately Dynmap is the only plugin not working for me with this new update.

**Comment by tackleza** [comment] 2021-07-31 17:41
Hello, please check this site and find the newest version that work
http://mikeprimm.com/dynmap/builds/dynmap/

I did't test it. So please try it by yourself
Still not working? please let me know

**Comment by tackleza** [comment] 2021-07-31 17:49
**remove**

**Comment by tackleza** [comment] 2021-07-31 18:02
@Chocolate1Donut Did you still have a problem?
Please check your Firewall that your Minecraft server can connect to MySQL Host. I think this problem is not a dynmap fault
many user failed because of this

**Comment by Chocolate1Donut** [comment] 2021-07-31 18:29
Yes, i still have this issue. In fact, it randomly started giving me the same error when using any Java version which forced me to switch to filetree storage, so you are right, it could be a host error. I will try the newest jar from that build server and report back with results

**Comment by Chocolate1Donut** [comment] 2021-08-01 23:49
> @Chocolate1Donut Did you still have a problem?

Still have same exact issue. Using latest dynmap-spigot build from that link you sent. Will not initialize mysql storage on java 11 or 16 now. Same error as before.

**Comment by Chocolate1Donut** [comment] 2021-08-01 23:55
It is unlikely this is a firewall issue considering I have multiple other plugins utilizing DedicatedMC's databases and they work perfectly.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 01:30
Likely duplicate of #3451 going to close this one for centralized tracking

**Closed as completed by FedUpWith-Tech** 2021-08-20 01:30 UTC
Labels: Duplicate, Bug Report
