### ISSUE TITLE
Very spotty tile generation as players explore

### ISSUE THREAD

**Issue by Syampuuh** [webbukkit/dynmap#3580] opened 2021-12-29 05:25 UTC
**Issue Description:** As players move through the world, DynMap is *very* slow to fill in tiles, resulting in a very spotty and incomplete map over time. The world is pregenerated to a large extent, so I cannot just do a fullrender without spoiling unexplored regions to players. Is there either a. configuration settings to improve the responsiveness of tiles or b. a way to fill in only tiles where players have explored? 

* **Dynmap Version:** *dynmap-version*
* **Server Version:** MC 1.18.1, Forge 39.0.9
* **Pastebin of Configuration.txt:** [https://pastebin.com/5SETL3z2](https://pastebin.com/raw/JNxuP15m)
* **Server Host (if applicable):** Bloom.host; server's map can be seen at http://104.247.112.163:8123/

 [ x ] *I have looked at all other issues and this is not a duplicate*  
 [ x ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-12-29 14:44
Duplicate of #2075

**Closed as completed by FedUpWith-Tech** 2021-12-29 14:44 UTC
Labels: Duplicate
