### ISSUE TITLE
Command: /dynmap reload produces error.

### ISSUE THREAD

**Issue by NullCase** [webbukkit/dynmap#2463] opened 2019-03-28 07:21 UTC
template is ugly.

### Version: 

git-Paper-584 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Dynmap version: 

core=3.0-beta-3-160, plugin=3.0-beta-3-160

### To produce:

Change config. Save changes.
Type command /dynamp reload

### Error:

```
28.03 03:25:45 [Server] WARN [dynmap] processWorldEvent(WORLD_LOAD,org.dynmap.bukkit.helper.BukkitWorld@6c11b92) - exception
28.03 03:25:45 [Server] INFO java.lang.NullPointerException: null
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.helper.v113_2.BukkitVersionHelperSpigot113_2.getWorldBorder(BukkitVersionHelperSpigot113_2.java:177) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.helper.BukkitWorld.getWorldBorder(BukkitWorld.java:245) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.MarkersComponent.addUpdateWorld(MarkersComponent.java:258) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.MarkersComponent.access$000(MarkersComponent.java:23) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.MarkersComponent$1.worldEvent(MarkersComponent.java:67) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.common.DynmapListenerManager.processWorldEvent(DynmapListenerManager.java:71) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:903) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:870) ~[?:?]
28.03 03:25:45 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-584]
28.03 03:25:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-584]
28.03 03:25:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-584]
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:231) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1403) ~[?:?]
28.03 03:25:45 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:962) ~[?:?]
```

**Comment by VaiTon** [comment] 2019-04-27 14:17
@NullCase Could you please give us the value returned by `/worldborder get` in your minecraft world?

**Comment by NullCase** [comment] 2019-09-04 06:19
@VaiTon 

`04.09 02:24:48 [Server] INFO The world border is currently 7000 blocks wide`

**Comment by FedUpWith-Tech** [comment] 2020-07-29 00:28
Assuming this is fixed in a later release- please open a new issue if this persists.

**Closed by FedUpWith-Tech** 2020-07-29 00:28 UTC
Labels: Bug Report

**Comment by FedUpWith-Tech** [comment] 2020-07-29 00:29
Duplicate of #2440
