### ISSUE TITLE
I can't open the DynMap website when the Synology WebStation is active

### ISSUE THREAD

**Issue by Atten007** [webbukkit/dynmap#3756] opened 2022-05-12 17:00 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Hi folks, I wanted to have a dynamic map overview for my Minecraft: Java Edition Server, so I installed DynMap. But when the Synology web station is active, DynMap crashes and it's also visible in the logs. Can someone fix this asap?*

* **Dynmap Version:** *3.4-beta3*
* **Server Version:** *PaperMC 1.18.2 build 333*
* **Pastebin of Configuration.txt:** *https://pastebin.com/jWSYsiCh*
* **Server Host (if applicable):** *I'm selfhosting*
* **Pastebin of crashlogs or other relevant logs:** *None*
* **Other Relevant Data/Screenshots:** *None*
* **Steps to Replicate:** *1. Open and activate the web station on your Synology NAS,<br>2. Restart the docker container with the Minecraft server in it,<br>3. DynMap will crash when the Synology WebStation is active.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment] 2022-05-12 17:14
This is not anything dynmap can and will fix, it might be the Nas thinks your docker uses too much ram and kills it, anyhow that is not their intended usecase

**Comment by sizquirt** [comment] 2022-05-13 12:57
Minecraft & NAS do not mix well. refrain from using NAS while running a server or if you really need just turn it off for a bit while you use NAS

**Comment by JurgenKuyper** [comment] 2022-05-24 13:08
closing this comment as the problem is not due to dynmap. if you need further help on another part of dynmap, feel free to open another issue tracker.

**Comment by sizquirt** [comment] 2022-05-25 07:04
> closing this comment as the problem is not due to dynmap. if you need further help on another part of dynmap, feel free to open another issue tracker.

It is fixable and it is related to dynmap. It can get a performance fix or something related to stop this issue

**Comment by JurgenKuyper** [comment] 2022-05-25 07:09
this leans to the unsupported hardware side. you can slow down the rendering by increasing the renderinterval, and decreasing the tiles-rendered-at-once, decreasing and removing the # of parallelrendercnt might help too. but because dynmap needs to render the tiles initially, it needs more ram than normal plugins. also check how much ram you have allocated and how much is free. you can also "pregenerate" the tiles on your own pc, disable the render triggers, and upload the tiles to the web/tiles of dynmap. this way only the webserver is using the ram.

**Closed as completed** 2022-06-13 15:41 UTC
Labels: Answered, Won't fix, Not Dynmap related
