### ISSUE TITLE
Black spots after several full renders plus worldguard/preciousstones not displaying

### ISSUE THREAD

**Issue by LadyAnimeYuki** [webbukkit/dynmap#3285] opened 2021-02-16 19:12 UTC
1.15.2 running spigot
Dynmap has black spots after running several full renders and even physically going on the map to the areas. Any way to force it to load those? ( I did try the force radius render and it didn't help )

Also looking for a way to display preciousstones or worldguard areas on the map but I cannot find a plugin for it. Attempted Dynmap-worldguard 1.2 to no affect, as well as the other dynmapPS 1.0.0 and Dynmap-PreciousStones all to the same end... :/ 

Dynmap Verision 3.1
server.pro host
I have looked at all other issues and this is not a duplicate, though similar issues are listed about the black spots
I have been able to replicate this

**Comment by Tsoccerguy3** [comment] 2021-03-02 04:22
My best guess is that you still have chunks of an older minecraft version in your map . You could force the map upgrade , which is a lot faster than flying around opening the chunks , see here how to do this for Spigot and Paper , https://www.spigotmc.org/ . Then fix the maps lighting with https://github.com/bergerhealer/Light-Cleaner , do a /cleanlight world command

Also you may try /dynmap pause all /dynmap purgeworld [Name of world]

WE and FAWE while in certain configurations dont automatically fix light levels , cleanlight can help

**Comment by LadyAnimeYuki** [comment] 2021-03-02 08:26
Thanks but it's not an older version as this is a fresh server. I will try the light cleaner but even flying over them does not load them on the dynmap. Thankfully there are only a couple small areas. :)

________________________________

**Comment by Tsoccerguy3** [comment] 2021-03-02 20:00
How was the map made . Vanilla , Forge , World Painter etc .. There may be litt;e errors in the chunks . If they are corrupted they can be reset , cleanlight is a good option . Just stand in the dark area and type /cleanlight and then /dynmap radiusrender 25 to test if the areas fixed in your map . If it works then you know there were light errors in the chunk

**Comment by LadyAnimeYuki** [comment] 2021-03-02 20:17
Vanilla then I added all the plugins dynmap was one of the first considering I knew it would take a long time to render the map. Testing cleanlight today fingers crossed that fixed it. They are only spots near spawn so it might have been something glitchy in the beginning. Thank you for the help

________________________________

**Comment by LadyAnimeYuki** [comment] 2021-03-04 20:48
I attempted light cleaner but it will not unpack the jar. I tried an older version but to the same result. :/ Maybe I should delete the entire thing and rerender it?
________________________________

**Comment by Tsoccerguy3** [comment] 2021-03-10 20:24
Sorry for being presumptuous , on the use of plugins . you will need these 2 plugins put them in your spigot or paper server /plugins directory.

https://ci.mg-dev.eu/job/BKCommonLib/ , get the current BKCommonLib jar file , todays update name is https://ci.mg-dev.eu/job/BKCommonLib/lastSuccessfulBuild/artifact/target/BKCommonLib-1.16.5-v3-SNAPSHOT-1023.jar

https://ci.mg-dev.eu/job/Light-Cleaner/ , get the current Light-Cleaner , 
https://ci.mg-dev.eu/job/Light-Cleaner/lastSuccessfulBuild/artifact/target/LightCleaner-1.16.5-v1.jar

Reboot your server , the plugins install them selves . Nothing to unzip

Go into the game log on to the server , either type /cleanlight world , for resetting the light on your map or stand in the dark area and just type /cleanlight to do 10 chunks around you . you can also type /cleanlight [radius] to cover a bigger area .

**Comment by LadyAnimeYuki** [comment] 2021-03-11 00:03
I do already have those installed. I did attempt cleaning the spots individually and while it appeared to work in the game the dynmap updated only when zoomed in. When zooming out the spots were occasionally still there and I would get error messages about not being able to clean the light. I'm happy enough with it as is because the dark spots are not anywhere near my spawn or towns now. Thank you for the help :)
________________________________

**Comment by Tsoccerguy3** [comment] 2021-03-11 20:47
some times the browser cache needs to be refreshed to see updates . If its on the server side if the chunk is in use or has not been written to disk it may show up after a save .

example : our server was moved to a new hub . The whole server compressed is 18 GiGs , this includes the dynmap images . This is to much useless data , I purged all the dynmap images this shrinks the server compressed to 3.6 gigs . Thats a lot of images at different resolutions , If something interupts the rendering or files are locked the may not get updated . I use custom compiled code for all our plugins and that includes Paper 1.16.5 . All the server code is in constant updates because of bugs . If your are using the posted plugins and server more than likely your server is going to be buggy.

Even the server I maintain with the latest code base may have bugs not yet found . On our server dynmap posted below you can see that there are a few black shadows . This happens from the use of World Edit or FAWE because the lighting does not get updated , open chunks etc... . You can see that I assumed that the lighting was ok since the last render , I was wrong to assume this and should have run /cleanlight world , before the render . Now I'm in the same spot you are in and need to update those dark lines (shadows) today
There is a list of things that need to be done in order to get a perfect render . To save server resources turn off some block update triggers in your config . If you have a specific question , ask

http://81.19.208.15:25666/

**Comment by Stechi** [comment] 2021-04-26 12:58
I have the same issue and it seem like this mostly happens on renders (both update and full) around active players.
My suspicion is that dynmap tries to load chunks at the same time as the server, but can't because of a file lock or something similar, so it renders chunks as not generated.

The only workaround I have for the moment is setting _fullrenderplayerlimit_ and _updateplayerlimit_ to 1 so it pauses, when players are online,
and only start radiusrender, when nobody is in the area or via console.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:05
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:05 UTC
Labels: Duplicate
