### ISSUE TITLE
Default webpage-title not sanitized against color codes if server.properties motd is altered.

### ISSUE THREAD

**Issue by depwl9992** [webbukkit/dynmap#2751] opened 2020-01-13 21:28 UTC
Embedded color codes in the server.properties motd using the unicode section sign (\u00A7) are translated out to rcon as plain text, as well as to the dynmap browser window title.

`motd=\u00A74_,-\u00A7c\='\=\u00A76-,_\u00A7e,-\=\u00A7fUnknown Server\u00A7e\=-,\u00A76_,-\u00A7c\='\=\u00A74-,_`

displays the HTML title:

`§4_,-§c='=§e-,_§fUnknown Server§e_,-§c='=§4-,_`

where I should see:

`_,-='=-,_A Minecraft Server_,-='=-,_`

While use-name-colors=false, I don't expect this to have any effect, as this is a global server configuration (only visible pre-login), and not anything to do with specific players. And of course, I could fix this with configuration.txt, though this has a high potential of breaking continuity if either the motd or the configuration's webpage-title override is changed later.

That said, it may be possible to group with similar symptoms to #2288, and could be brute-force-solved with an equivalent of the PHP function:

```
$color_codes = array("§0","§1","§2","§3","§4","§5","§6","§7","§8","§9","§a","§b","§c","§d","§e","§f","§k","§l","§m","§n","§o","§r");
str_replace($color_codes,"",$webpage-title);
```

Running Dynmap-3.0-beta-9-250 on CraftBukkit git-Spigot-037559e-e8cb2f5.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:58
Duplicate of #2288 
Set `markup=true` on each marker with an offending character to fix

**Closed as completed by FedUpWith-Tech** 2020-07-28 22:58 UTC
Labels: Duplicate, Marker Issues
