### ISSUE TITLE
Dynmap Reload command breaks dynmap

### ISSUE THREAD

**Issue by Jerasaurus** [webbukkit/dynmap#3469] opened 2021-08-23 06:34 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *core=3.2-beta-2-483, plugin=3.2-beta-2-483*
* **Server Version:** *Paper 1.17.1 Build 180*
* **Pastebin of Configuration.txt:** *https://pastebin.com/VLrkCp9X*
* **Self Hosted.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/7Y8sy8be*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*
* Start server/dynamp and verify its working
* (optional) make configuration changes to .txt (breaks without config changes aswell)
* do /dynmap reload
* errors seen in console

 [ X] *I have looked at all other issues and this is not a duplicate*  
 [ X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-08-23 15:24
Duplicate of #3350

**Closed as completed by FedUpWith-Tech** 2021-08-23 15:24 UTC
Labels: Duplicate
