### ISSUE TITLE
Maybe Java 16 not supported?..

### ISSUE THREAD

**Issue by molor** [webbukkit/dynmap#3377] opened 2021-05-31 18:30 UTC
* **Dynmap Version:** *below*
* **Server Version:** *git-Paper-753 (MC: 1.16.5)*

```
> dynmap reload
[21:26:32] Reloading Dynmap...
[21:26:32] [dynmap] Disabling dynmap v3.1-457
[21:26:32] [dynmap] Unloaded 5 components.
[21:26:32] [dynmap] Stopping map renderer...
[21:26:33] [dynmap] Disabled
[21:26:33] [dynmap] Enabling dynmap v3.1-457*
[21:26:33] Enabled plugin with unregistered PluginClassLoader dynmap v3.1-457
[21:26:33] [dynmap] Starting Scheduled Write Job (markerAPI).
[21:26:33] Error: DynmapBlockState updated after arrays generated
[21:26:33] java.lang.Exception: Stack trace
[21:26:33]      at java.base/java.lang.Thread.dumpStack(Thread.java:1377)
[21:26:33]      at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:121)
[21:26:33]      at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:104)
[21:26:33]      at org.dynmap.bukkit.helper.v116_4.BukkitVersionHelperSpigot116_4.initializeBlockStates(BukkitVersionHelperSpigot116_4.java:110)
[21:26:33]      at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:853)
[21:26:33]      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:26:33]      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[21:26:33]      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[21:26:33]      at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253)
[21:26:33]      at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595)
[21:26:33]      at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039)
[21:26:33]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:26:33]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:26:33]      at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[21:26:33]      at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788)
[21:26:33]      at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[21:26:33]      at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437)
[21:26:33]      at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[21:26:33]      at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[21:26:33]      at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[21:26:33]      at java.base/java.lang.Thread.run(Thread.java:831)
[21:26:34] Error occurred while enabling dynmap v3.1-457 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[server.jar:git-Paper-753]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[server.jar:git-Paper-753]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[server.jar:git-Paper-753]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:25) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:879) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Paper-753]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[server.jar:git-Paper-753]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[server.jar:git-Paper-753]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253) ~[?:?]
        at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Paper-753]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Paper-753]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[server.jar:git-Paper-753]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[server.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[server.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[server.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[server.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[server.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[server.jar:git-Paper-753]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:26:34] [dynmap] Disabling dynmap v3.1-457
[21:26:34] [dynmap] Unloaded 0 components.
[21:26:34] [dynmap] Disabled
[21:26:34] Dynmap reloaded
```

**Comment by Joo200** [comment] 2021-05-31 20:20
make sure your .jar-file in your plugins folder is valid and restart your server. reloading dynmap doesn't work with an updated .jar-file.

**Comment by molor** [comment] 2021-05-31 20:28
> make sure your .jar-file in your plugins folder is valid and restart your server. reloading dynmap doesn't work with an updated .jar-file.

I'm know it and I'm not touching the jar, I'm modified only world settings file. Before updating to latest Paper and Java 16, /dynmap reload was worked

**Comment by FedUpWith-Tech** [comment] 2021-05-31 22:40
Dynmap reload isn't a recommended command ever, it has unreliable behavior and breaks things more often than fixes

**Comment by elpocoburrito** [comment] 2021-06-08 01:05
Got the same issue; steps taken:
installed Dynmap and rebooted server; 
1. changed port in config file
2. map quality from highres to vlowres
3. jpg compression (jpg90 to jpg85)
4. `/dynmap reload`
I'm pretty sure a server reboot will fix it but i can't reboot right now since users are online. It's no big issue, just figured i'd provide context for the error to occur.

**Comment by Drc-DEV** [comment] 2021-06-25 19:16
Use Plugman and do /plugman reload dynmap, it works fine that way.

**Comment by mikeprimm** [comment] 2021-07-08 21:32
Dupe of #3350

**Closed as completed by mikeprimm** 2021-07-08 21:32 UTC
Labels: Support Question
