### ISSUE TITLE
Custom Water Colours Not Working Properly

### ISSUE THREAD

**Issue by linkikari** [webbukkit/dynmap#3364] opened 2021-05-15 02:34 UTC
I have a resource pack that changes the water colours in different biomes, however the colours on the map aren't what they should be:
<img width="1080" alt="Screen Shot 2021-05-15 at 12 21 07 pm" src="https://user-images.githubusercontent.com/80310069/118345609-05ecb000-b579-11eb-93a0-bf1288239c56.png">
<img width="1080" alt="Screen Shot 2021-05-15 at 12 22 13 pm" src="https://user-images.githubusercontent.com/80310069/118345613-0a18cd80-b579-11eb-9493-586a998727ed.png">
<img width="1080" alt="Screen Shot 2021-05-15 at 12 21 27 pm" src="https://user-images.githubusercontent.com/80310069/118345615-0edd8180-b579-11eb-89f8-ea09029511cc.png">
<img width="1080" alt="Screen Shot 2021-05-15 at 12 21 47 pm" src="https://user-images.githubusercontent.com/80310069/118345618-10a74500-b579-11eb-99dd-fde91b44f412.png">
I've had this working on 1.12 but using it on 1.16 (the pack itself has been updated) has weird colours. I assume this is dynmap still applying the vanilla colours over the top but I'm not sure. Any help would be appreciated.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:16
Duplicate of #3438

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:16 UTC
Labels: Duplicate
