### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by Arrandirs** [webbukkit/dynmap#2443] opened 2019-02-11 15:07 UTC
Hello !
I own a server that was created from a vps.
The vps is divided into several parts. Each part = 1 minecraft server. The problem is that each server has a port.
A port = 1 server
This is how the servers are differentiated by the vps to connect the players to the corresponding server.
The problem is that you need an unused port to start the dynmap.
What to do since you need an unused port for the dynmap but I can not create a port assigned to the right server without using it by this server.

**Comment by smmmadden** [comment] 2019-02-11 17:11
Hi @Arrandirs - Every server whether it be a VM, Physical or Logic Server will need a port for Dynmap to communicate on via the web.  

This is the same requirement for the server itself (minecraft-server.jar, paper spigot, spigot, etc). as they also need their own ports.  Without this distinction you will not be able to properly configure the Minecraft environment.

**Comment by Arrandirs** [comment] 2019-02-11 17:13
what should I do ?
I do not know how to create a port on VPS connected to my server without using it ..

**Comment by Arrandirs** [comment] 2019-02-11 17:16
If i set the port of my server, the dynmap generate bugs and said he could not generate the map because the port is used.. :/

**Comment by smmmadden** [comment] 2019-02-11 17:18
you don't create ports, you add the port to your firewall to allow traffic to use it.

**Comment by Arrandirs** [comment] 2019-02-11 17:23
how can i do it ? I'm not very good with that :/

**Comment by smmmadden** [comment] 2019-02-11 17:30
This is not the right place to get help setting up a server.  Search google or yahoo to find information about configuring VPS and managing IPs, Ports and Security.  There are tons of docs out there for this.

**Comment by Arrandirs** [comment] 2019-02-11 17:31
to resume, i just need to add the port of my current server to my firewall. I add the same port than the port of my server and the ip of the vps and it's ok ?

**Comment by smmmadden** [comment] 2019-02-11 17:35
we don't know how you set your server up nor should we.  So it isn't right for anyone to tell you if that's all that's needed or not.  

If you are doing this for a first time, then you'll need to read about how to setup a secured Virtual Private Server on your own as this site is for issues with Dynmap not working and what you're reporting is an issue with your server not being correctly setup.

**Comment by Arrandirs** [comment] 2019-02-11 17:54
[18:52:56] [Server thread/ERROR]: [dynmap] Failed to start WebServer on address 127.0.0.1:25566 : Address already in use

**Comment by Arrandirs** [comment] 2019-02-11 17:55
i try to found help to internet AND the support of the vps. Before, coming here. I'm not the "kikoo lol" who coming without searching by himself. If you can't help me, said that. But do not send me on my own to configure your plugin.

**Comment by smmmadden** [comment] 2019-02-11 18:55
You error is specific to YOUR SERVER and has nothing to do with the plugin.  

Again, if you are to host your own servers, it comes with these types of challenges that are best suited elsewhere and not on this site.  I host my own servers (8 of them) and do not have any issues with IP's, ports or this plugin.  I understand you are new at this, but free support to configure your servers is not an option here.

**Comment by Arrandirs** [comment] 2019-02-11 18:59
so where i'm supp to go if internet don't give to me the answers, you don't want to give me an answers and the vps host don't want to give me answers.. ?

**Comment by smmmadden** [comment] 2019-02-11 19:09
Not trying to be difficult or unhelpful - I've said what you need to do and if you can find it on google or other search engines, that's not for me to fix.  I googled this before telling you where to get info, and I came up with 48 million matches.  So there is help there - you have to take the time to find it and learn how to do it - or don't host your own servers which is what many people do because of security, networking and overall maintenance costs.
![image](https://user-images.githubusercontent.com/10309346/52586814-763e8100-2e06-11e9-920a-53ca4123550a.png)

**Comment by Arrandirs** [comment] 2019-02-11 19:10
where am I supposed to have gone? The vps host told me to go to dynmap support for help. The dynmap support tells me to go on the internet.
If I post a request for help here, it is that I have already searched before on the internet ..
Internet explains few things. The little that is explained on the internet is explained for experienced users! People who do not know anything (or few things) have no chance of coming up with this kind of thing.
I need to display my map on the internet, this plugin is supposed to be able to do it, if it is not marked nowhere to do for vps. WHAT SHOULD I DO ? as the support tells me to search on the internet (which I have not done well, of course ;) ).

**Comment by smmmadden** [comment] 2019-02-11 19:20
your first post stated that you own the VPS and you are setting up the server.  Not that you are hosting your minecraft server with another hosting company and unable to get the server to work.  These are two separate types of issues.  If you were hosting on your computer in your home or business - you do need to lookup and lean how to create VPS's for Minecraft or any other application.

If the VPS host provided you with space (drives) to run your minecraft server own, then you need to tell them which ports to open (expose in firewall to allow traffic).  The port(s) listed in the server.properties file and the port(s) listed in the configuration.txt file (Dynmap).  Most hosts will SECURE (lock/deny) ALL PORTS unless you tell them which ones to open.

**Comment by Arrandirs** [comment] 2019-02-13 17:59
Like i excepted, there is not firewall here.

**Comment by Arrandirs** [comment] 2019-02-13 18:01
On my VPS* So the problem is not here. So 
to be calmer hoping to have a good time for any non-aggressive response, what should I put in the config document.
The ip of vps, the dedicated IP of the server? The ip of the server?
The port I have to put is which one? If I put one of the server, it marks me:
[dynmap] Failed to start WebServer on address 127.0.0.1:25566 : Address already in use

**Comment by Arrandirs** [comment] 2019-02-13 18:20
To rectify, every ports are by default open ^^

**Comment by Psy-Virus** [comment] 2019-02-13 19:43
First of all: Raging doesn't help anyone! @smmmadden was just trying to help and told you what bascis you have to know to get some help here.

This also is not a discussion forum. It is a bug tracker. For Support and general discussion, please head over to https://forums.dynmap.us.

Server setups were discussed probably several hundred times here. You just have to checkout the closed issues.
`[dynmap] Failed to start WebServer on address 127.0.0.1:25566 : Address already in use`

This error tells you that the port is already in use. Just try other ports until you find one that's working.
And always check it by browsing http://{SERVERIP}:{SERVERPORT} and not the Loop Back address `127.0.0.1`. Make sure to not use https because, as far as I know, the Jetty Webserver doesn't support https; or it's not activated in the Dynmap setup.

That been said, you now have all the information you need to setup your server. Everything else you may need for this problem is easy to find on Youtube and Google itself. There are dozens of tutorials out there.

But if you still need a hand to carry you step by step through the setup, feel free to visit https://forums.dynmap.us and I'll be happy to help you, when I find the time. :)

!Closing because not a bug and problem should be resolved!

**Closed by Psy-Virus** 2019-02-13 19:43 UTC

**Comment by rautamiekka** [comment] 2019-02-13 19:46
Maybe this'll bring closure:

If you're on Linux, shut down the 'Mc' Server and use this command to figure out which process is already using that port:

```bash
{ sudo ss -tulpn || sudo netstat -tulpn } | grep :25566
```

**Comment by Arrandirs** [comment] 2019-02-13 19:59
okey i will try :D

**Comment by Arrandirs** [comment] 2019-02-13 20:04
i try the command on the vps and the 'mc' server but i have some bugs. The command produces no response.

**Comment by rautamiekka** [comment] 2019-02-13 20:09
> i try the command on the vps and the 'mc' server but i have some bugs. The command produces no response.

Ok, try them 1 by 1 to see why they fail:

```bash
sudo ss -tulpn
sudo netstat -tulpn
```
I'm suspecting your installation lacks the packages for both commands.

**Comment by Arrandirs** [comment] 2019-02-13 20:36
root@vps383AUTO:/home/Eternum# sudo -l ss -tulpn
bash: sudo: command not found
root@vps383AUTO:/home/Eternum# ^C
root@vps383AUTO:/home/Eternum# sudo netstat -tulpn
bash: sudo: command not found
root@vps383AUTO:/home/Eternum#

**Comment by Arrandirs** [comment] 2019-02-13 20:37
root@vps383AUTO:~# sudo netstat -tulpn
-bash: sudo: command not found
root@vps383AUTO:~#

**Comment by Arrandirs** [comment] 2019-02-13 20:38
```shell
root@vps383AUTO:~# sudo netstat -tulpn
-bash: sudo: command not found
root@vps383AUTO:~#
```

**Comment by Arrandirs** [comment] 2019-02-13 20:39
the result is the same for both commands on every server.

**Comment by Psy-Virus** [comment] 2019-02-14 15:54
https://www.howtogeek.com/124950/htg-explains-why-you-shouldnt-log-into-your-linux-system-as-root/

**Comment by Arrandirs** [comment] 2019-02-15 09:45
I watched your link carefully.
I did not find any answers thanks to your link.
To answer the question above. I found what the port is used for.
My Linux server is a VPS that has three ports: a main server, a secondary server and a bungeecord that binds all three! Now, I do not understand why I can not update the same port as my main server on the dynmap?

**Comment by rautamiekka** [comment] 2019-02-15 11:22
Odd, you shouldn't have any problems with using `sudo` as `root`.

Yeah, get yourself a non-`root` user and don't use the `root` unless absolutely necessary and install `sudo` to elevate when needed.

Try those commands without the `sudo` part since that seems to be the problem.

**Comment by Arrandirs** [comment] 2019-02-18 18:09
Hello i try to follow your expectations, but the dynmap still don't load. 
Actually, i try a different port: xxx.xxx.xxx:25568
But in the console, this is what i have: 
 [19:06:49 INFO]: [dynmap] Loaded 14 lightings.
[19:06:49 INFO]: [dynmap] Web server started on address 127.0.0.1:25568
When i go on the web, i try to connect to using: http:127.0.0.1:25568 or http:xxx.xxx.xxx:25568 
but none of them load the map..

**Comment by rautamiekka** [comment] 2019-02-18 18:24
> Hello i try to follow your expectations, but the dynmap still don't load.
> Actually, i try a different port: xxx.xxx.xxx:25568
> But in the console, this is what i have:
> [19:06:49 INFO]: [dynmap] Loaded 14 lightings.
> [19:06:49 INFO]: [dynmap] Web server started on address 127.0.0.1:25568
> When i go on the web, i try to connect to using: http:127.0.0.1:25568 or http:xxx.xxx.xxx:25568
> but none of them load the map..

Did you even try those commands after installing `sudo` ?

**Comment by Arrandirs** [comment] 2019-02-18 18:25
I have some problems to install sudo :/ i will retry with sudo !

**Comment by rautamiekka** [comment] 2019-02-18 18:26
> I have some problems to install sudo :/ i will retry with sudo !

If you don't copypaste what you tried and what the output is, you can't be helped. Copypaste the whole text without leaving a single thing out. Although, I'm not sure if the repo owners allow that much text ...

**Comment by Arrandirs** [comment] 2019-02-18 18:44
this is what i have with the command you send to me ! 
oot@vps383AUTO:~# ss -tulpn
Netid State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
tcp   LISTEN     0      128               *:22                            *:*                   users:(("sshd",pid=177,fd=3))
tcp   LISTEN     0      100       127.0.0.1:25                            *:*                   users:(("master",pid=299,fd=13))
tcp   LISTEN     0      128       127.0.0.1:6010                          *:*                   users:(("sshd",pid=2616,fd=9))
tcp   LISTEN     0      128              :::22                           :::*                   users:(("sshd",pid=177,fd=4))
tcp   LISTEN     0      100             ::1:25                           :::*                   users:(("master",pid=299,fd=14))
tcp   LISTEN     0      128             ::1:6010                         :::*                   users:(("sshd",pid=2616,fd=8))
tcp   LISTEN     0      128              :::25565                        :::*                   users:(("java",pid=363,fd=83))
tcp   LISTEN     0      128    ::ffff:127.0.0.1:25566                        :::*                   users:(("java",pid=1169,fd=40))
tcp   LISTEN     0      50     ::ffff:127.0.0.1:25568                        :::*                   users:(("java",pid=1169,fd=133))
root@vps383AUTO:~#

**Comment by Arrandirs** [comment] 2019-02-18 18:44
> oot@vps383AUTO:~# ss -tulpn
Netid State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
tcp   LISTEN     0      128               *:22                            *:*                   users:(("sshd",pid=177,fd=3))
tcp   LISTEN     0      100       127.0.0.1:25                            *:*                   users:(("master",pid=299,fd=13))
tcp   LISTEN     0      128       127.0.0.1:6010                          *:*                   users:(("sshd",pid=2616,fd=9))
tcp   LISTEN     0      128              :::22                           :::*                   users:(("sshd",pid=177,fd=4))
tcp   LISTEN     0      100             ::1:25                           :::*                   users:(("master",pid=299,fd=14))
tcp   LISTEN     0      128             ::1:6010                         :::*                   users:(("sshd",pid=2616,fd=8))
tcp   LISTEN     0      128              :::25565                        :::*                   users:(("java",pid=363,fd=83))
tcp   LISTEN     0      128    ::ffff:127.0.0.1:25566                        :::*                   users:(("java",pid=1169,fd=40))
tcp   LISTEN     0      50     ::ffff:127.0.0.1:25568                        :::*                   users:(("java",pid=1169,fd=133))
root@vps383AUTO:~#

**Comment by Arrandirs** [comment] 2019-02-18 19:12
I know the owner doesn't allow to post here.. But i have no response on internet (yeah i'm not a programmer, like you can see x) ) and i search since 3 weeks now.. is it more than boring.. ! :(

**Comment by Psy-Virus** [comment] 2019-02-18 19:48
It's not the problem to post here. We just don't want to have support discussions here, like I said before. This is a bug tracker not a support forum (The support forum is https://forums.dynmap.us ). I only didn't lock the thread because it starts to look interesting and that we didn't have this kind of problem before.

It looks like your MC Server is listening to an IPV6 address.
And that your server is running on IPV6 only. 

To recapitulate all this:
You're sitting at home on your PC and your server is somewhere else, right?
When you try to reach Dynmap, you're using the IP address of your Server, right?

You can't reach Dynmap via the LoopBack address (127.0.0.1) of your server. You need the external IP address of your server. It should be an IPV6 address.
Take a look at this for a basic know how: https://www.youtube.com/watch?v=aor29pGhlFE

Please give us the output of the command `ifconfig`

**Comment by Arrandirs** [comment] 2019-02-18 19:59
when i try to reach dynmap, i try to use the i address of the server yes !

**Comment by Arrandirs** [comment] 2019-02-18 19:59
i will watch your link :) thx !

**Comment by Psy-Virus** [comment] 2019-02-18 20:03
Well the Youtube link is and explanation about ipv6 not an how to about how to fix the ip stuff with your server.

**Comment by Arrandirs** [comment] 2019-02-18 20:48
No problem, i will watch after ipv6 on google x) but you want i give you the output of the command `ifconfig`. What do you except ?

**Comment by Arrandirs** [comment] 2019-02-18 20:57
I put the ip of the vps, is it what do you mean ? :D

**Comment by Psy-Virus** [comment] 2019-02-18 21:06
> What do you except ?
I expect you to give us the information we need to help you. Otherwise you will have to search somewhere else for help.
If you fear to get hacked, make a backup, shutdown the server and learn the basics before you try advanced stuff.

**Comment by Arrandirs** [comment] 2019-02-18 21:08
this is the ip of the vps: 54.36.68.208

**Comment by Psy-Virus** [comment] 2019-02-18 21:08
I wanted the output of `ifconfig`

**Comment by Arrandirs** [comment] 2019-02-18 21:11
sorry if I was offended, I wanted to be more useful
Where is the "ifconfig" you want ? 
I feel really bad and I do not understand

**Comment by Psy-Virus** [comment] 2019-02-18 21:12
It's a console command, like the `ss -tulpn` command.

**Comment by Arrandirs** [comment] 2019-02-18 21:14
`root@vps383AUTO:~# ifconfig
-bash: ifconfig: command not found
root@vps383AUTO:~# ss -tulpn
Netid State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
tcp   LISTEN     0      128               *:22                            *:*                   users:(("sshd",pid=177,fd=3))
tcp   LISTEN     0      100       127.0.0.1:25                            *:*                   users:(("master",pid=299,fd=13))
tcp   LISTEN     0      128       127.0.0.1:6010                          *:*                   users:(("sshd",pid=8704,fd=9))
tcp   LISTEN     0      128       127.0.0.1:6011                          *:*                   users:(("sshd",pid=8969,fd=9))
tcp   LISTEN     0      128       127.0.0.1:6012                          *:*                   users:(("sshd",pid=9315,fd=9))
tcp   LISTEN     0      128       127.0.0.1:6013                          *:*                   users:(("sshd",pid=7907,fd=9))
tcp   LISTEN     0      128              :::22                           :::*                   users:(("sshd",pid=177,fd=4))
tcp   LISTEN     0      100             ::1:25                           :::*                   users:(("master",pid=299,fd=14))
tcp   LISTEN     0      128             ::1:6010                         :::*                   users:(("sshd",pid=8704,fd=8))
tcp   LISTEN     0      128             ::1:6011                         :::*                   users:(("sshd",pid=8969,fd=8))
tcp   LISTEN     0      128             ::1:6012                         :::*                   users:(("sshd",pid=9315,fd=8))
tcp   LISTEN     0      128             ::1:6013                         :::*                   users:(("sshd",pid=7907,fd=8))
tcp   LISTEN     0      128              :::25565                        :::*                   users:(("java",pid=363,fd=83))
tcp   LISTEN     0      128    ::ffff:127.0.0.1:25566                        :::*                   users:(("java",pid=1169,fd=40))
tcp   LISTEN     0      50     ::ffff:127.0.0.1:25568                        :::*                   users:(("java",pid=1169,fd=133))
`

**Comment by Arrandirs** [comment] 2019-02-18 21:15
` root@vps383AUTO:~# Netid State      Recv-Q Send-Q Local Address:Port               Peer Address:Port
-bash: Netid: command not found
root@vps383AUTO:~# tcp   LISTEN     0      128               *:22                            *:*                   users:(("sshd",pid=177,fd=3))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      100       127.0.0.1:25                            *:*                   users:(("master",pid=299,fd=13))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128       127.0.0.1:6010                          *:*                   users:(("sshd",pid=8704,fd=9))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128       127.0.0.1:6011                          *:*                   users:(("sshd",pid=8969,fd=9))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128       127.0.0.1:6012                          *:*                   users:(("sshd",pid=9315,fd=9))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128       127.0.0.1:6013                          *:*                   users:(("sshd",pid=7907,fd=9))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128              :::22                           :::*                   users:(("sshd",pid=177,fd=4))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      100             ::1:25                           :::*                   users:(("master",pid=299,fd=14))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128             ::1:6010                         :::*                   users:(("sshd",pid=8704,fd=8))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128             ::1:6011                         :::*                   users:(("sshd",pid=8969,fd=8))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128             ::1:6012                         :::*                   users:(("sshd",pid=9315,fd=8))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128             ::1:6013                         :::*                   users:(("sshd",pid=7907,fd=8))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128              :::25565                        :::*                   users:(("java",pid=363,fd=83))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      128    ::ffff:127.0.0.1:25566                        :::*                   users:(("java",pid=1169,fd=40))
-bash: syntax error near unexpected token `('
root@vps383AUTO:~# tcp   LISTEN     0      50     ::ffff:127.0.0.1:25568 `

**Comment by Arrandirs** [comment] 2019-02-18 21:27
root@vps383AUTO:~# ifconfig
-bash: ifconfig: command not found

**Comment by Psy-Virus** [comment] 2019-02-18 21:27
The thing is, `ss -tulpn` tells us that your server is listening to ipv6 addresses. but you gave us an ipv4 address. And ifconfig is not found, what's kinda weird because usually it's a base packet, that's installed by default. I would talk to the VPS provider's support about your problem, as we just can't help you if you're not able to provide us the needed information, be it through restrictions of your service provider or your lack of knowledge. :(

Tell them, what you try to achieve, ask what kind of network structure they have and how you could setup the whole thing.

I think it's a bunch of ipv6 machines behind some ipv4 addresses that communicate via a NAT network or it's some weird tunneled network. This or that way, you definitely have to speak to the vps support, as we can't look into your server and see what's maybe wrong....

What else you could try to get a feeling for linux and networking under linux, would be to setup an own "vps". A virtual computer with "Ubuntu" as operating system for example.
If you're interested, check out this video: https://www.youtube.com/watch?v=QbmRXJJKsvs

**Comment by Arrandirs** [comment] 2019-02-18 21:30
I will (rere)mp the support of my vps to found a solution ! I will send to you the informations they will give to me !

**Comment by Psy-Virus** [comment] 2019-02-18 21:31
Sounds good.
