### ISSUE TITLE
Dynmap render finished, but map is still incomplete.

### ISSUE THREAD

**Issue by Prxmium** [webbukkit/dynmap#2537] opened 2019-07-04 21:40 UTC
Map URL: 8.48.33.15:8123

I've been trying to finish the render on my map for a day or so now, but the same incomplete chunks are still incomplete every time the render finishes.

I've tried using updaterender, but it just finishes immediately, only updating 1 tile.

configuration.txt: https://pastebin.com/HGWnAKpf
custom-normal-lowres.txt: https://pastebin.com/4uifnRYu
worlds.txt: https://pastebin.com/V6t2Eq38
/ver **_Paper version git-Paper-123 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)_**

/ver dynmap **_dynmap version 3.0-beta-4-213_**

Fresh startup log: https://pastebin.com/32n5yECu

**Comment by DmitryRendov** [comment] 2019-07-05 09:24
the same issue for me using 1.14.3 spigot, wb 1.9.10 and latest dynmap snapshot...
seems it might be related to WB itself, not dynmap.

**Comment by ghost** [comment] 2019-07-06 14:11
I also have been experiencing this issue and after investigating the issue I found that PaperLib is outdated.
PaperLib has not yet been updated to 1.14 and that's why WorldBorder was not loading chunks correctly.
In my modified version of WorldBorder I replaced all use of PaperLib with direct paper api access.
The benefit is now all chunks are loaded correctly and map is full on dynmap, but only on PaperSpigot.
My modified version of WorldBorder is only compatible with PaperSpigot, not Spigot or CraftBukkit.
[WorldBorder modified to support Paper 1.14.3 + Dynmap 1.14.3](https://ci.skorrloregaming.com/view/dynmap/)

**Comment by WeltensiedlerDE** [comment] 2019-07-08 01:53
Wgy you not rading allready opened issues before posting the same issue again?
https://github.com/webbukkit/dynmap/issues/2522

**Comment by roopekoo** [comment] 2019-07-17 11:36
Duplicate of #2522

**Closed as completed** 2019-07-19 23:29 UTC
