### ISSUE TITLE
Custom resource pack error

### ISSUE THREAD

**Issue by IvIercenary** [webbukkit/dynmap#2082] opened 2017-04-08 20:31 UTC
[16:29:00 INFO]: [dynmap] Loading resource pack conquest1112.zip
[16:29:05 ERROR]: [dynmap] Exception during render job: world=Kyfre, map=org.dynmap.hdmap.HDMap@83c07d7
[16:29:05 WARN]: java.lang.ArrayIndexOutOfBoundsException: 22528
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.combineSubimageFromImage(TexturePack.java:896)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.makeShulkerSideImage(TexturePack.java:1076)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.patchShulkerImages(TexturePack.java:1104)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.processDynamicImage(TexturePack.java:1344)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.<init>(TexturePack.java:852)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePack.getTexturePack(TexturePack.java:683)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePackHDShader.getTexturePack(TexturePackHDShader.java:57)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePackHDShader.access$000(TexturePackHDShader.java:22)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePackHDShader$ShaderState.<init>(TexturePackHDShader.java:128)
[16:29:05 WARN]:        at org.dynmap.hdmap.TexturePackHDShader.getStateInstance(TexturePackHDShader.java:323)
[16:29:05 WARN]:        at org.dynmap.hdmap.HDMapManager.getShaderStateForTile(HDMapManager.java:136)
[16:29:05 WARN]:        at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1088)
[16:29:05 WARN]:        at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[16:29:05 WARN]:        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:708)
[16:29:05 WARN]:        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)
[16:29:05 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190)
[16:29:05 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)
[16:29:05 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:29:05 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:29:05 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[16:29:05 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[16:29:05 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:29:05 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:29:05 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by SimonOrJ** [comment] 2017-04-10 09:44
Duplicate of #2067

**Comment by FedUpWith-Tech** [comment] 2020-07-28 16:33
Fixed in #2109

**Closed by FedUpWith-Tech** 2020-07-28 16:33 UTC
Labels: Duplicate, Fixed, Support Question
