### ISSUE TITLE
Dynmap link on Spiget API is broken 

### ISSUE THREAD

**Issue by ElektroVirus** [webbukkit/dynmap#3705] opened 2022-03-06 15:23 UTC
[x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

Hey! I tried to use Dynmap on Spigot server running on [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) with Spiget-API but it does not work as expected, please take a look at this issue I wrote about two weeks ago:
https://github.com/itzg/docker-minecraft-server/issues/1378

Especially take a look at these messages in the previous issue:
https://github.com/itzg/docker-minecraft-server/issues/1378#issuecomment-1059689213 
and https://github.com/itzg/docker-minecraft-server/issues/1378#issuecomment-1059972836.

If you need more information, I'll be happy helping you. I left the asked template information empty for now since it probably does not matter but if you want, I can provide it.

Thank you!

**Comment by JurgenKuyper** [comment] 2022-03-06 15:36
duplicate of #3638

**Closed as completed by JurgenKuyper** 2022-03-06 15:36 UTC
Labels: Bug Report

**Comment by itzg** [comment] 2022-03-06 16:58
Thanks @JurgenKuyper ! I'll address it on the container side by providing the download page for the user to visit.
