### ISSUE TITLE
Special Characters in Markers on Dynmap

### ISSUE THREAD

**Issue by 0fEfF2Dto4KoNAVZu8cb5** [webbukkit/dynmap#2740] opened 2020-01-03 23:06 UTC
We are adding some markers on our server Dynmap, and when this command is run: 
/dmarker add "Chris + Aida's Home" icon:house
the marker shows up as [this](https://imgur.com/a/jdiHRa2).

**Comment by ghost** [comment] 2020-01-12 19:14
Duplicate of #2288 . Workaround is to set `markup=true` in markers config for each marker that has a single quote.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:57
Duplicate of #2288 
Set `markup=true` on each marker with an offending character to fix

**Closed as completed by FedUpWith-Tech** 2020-07-28 22:57 UTC
Labels: Duplicate, Marker Issues
