### ISSUE TITLE
Strange black grid gaps on a migrated world

### ISSUE THREAD

**Issue by infinitephantasm** [webbukkit/dynmap#2777] opened 2020-01-30 17:28 UTC
![image](https://user-images.githubusercontent.com/23409983/73473990-4e1b9b00-4353-11ea-8ad3-a720b1836dd8.png)

there are these weird gaps in my world after doing a fullrender. this doesn't look like this when ingame, but there's just large grid-like gaps all around the map, except for in places i've actually been to after migration. if it matters, this was on a Multiverse-loaded world. is this normal, or is something just really wrong?

server is running on paper build 80 on 1.15.2, on the latest snapshot build (this also occurred on beta10).

**Comment by ghost** [comment] 2020-02-01 06:31
I have this same issue. Original spigot version was 1.12.2, and upgraded my server to the latest spigot build at the time (1.15.1). Used dynmap 3.0 beta 9. Tried using the latest version, same issue.

Edit: I don't have a fix, but I do think I have an idea of why they're appearing. If you migrated from an older version of Minecraft, you'll know that Mojang completely remade all of the textures. My guess is when dynmap loads the resource pack, it notices that the textures are different, and tries to re-render everything.

It's really more of an educated guess. I've never actually taken a look at Dynmap's source code.
![Capture](https://user-images.githubusercontent.com/57119109/73589534-d063a680-449c-11ea-92ad-5130c0be9632.PNG)

**Comment by baconwaifu** [comment] 2020-02-01 17:11
It's likely a chunk format issue. Minecraft 1.12 -> 1.13 updated the chunk format. Spigot has a startup flag `--forceUpgrade` to trigger a full conversion of the world to the new format; Not sure about paper.

After the upgrade is complete, re-run `/fullrender` and it should be fixed. (also, you can remove the flag once the world's been converted)

**Comment by ghost** [comment] 2020-02-02 17:55
@baconwaifu Created a test server from an image of the server that was migrated. Still had the same issue. Any other ideas?

**Comment by ghost** [comment] 2020-02-05 12:37
I think I found an answer, but I haven't tested it yet. In the dynmap config, there is a "migrate chunks" option at the very bottom. Back to what baconwaifu said, it might work. I'll try it when I get the chance and update @infinitephantasm on it.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 23:15
Duplicate of #2282

**Closed as completed by FedUpWith-Tech** 2020-07-28 23:15 UTC
Labels: Duplicate, Render Issues, World Conversion
