### ISSUE TITLE
Compatibility with blocks from Underground Biomes 

### ISSUE THREAD

**Issue by Aldaz108** [webbukkit/dynmap#3134] opened 2020-09-22 18:46 UTC
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Currently Underground Biomes which adds a lot of different rock and mineral types do not render in worlds causing large patches of black/lava areas on the map. Example --> http://116.202.55.212:25566/# *

* **Additional context:** *EDIT: Extra info, may not be Underground Biomes but Biomes O'Plenty? Seems like Gravel and different dirt types are effected. Thinking about this could tie in with Serene Seasons and Biomes O plenty mods causing the issue I'm getting.

**Comment by FedUpWith-Tech** [comment] 2020-09-22 18:50
Duplicate of #3112

**Closed as completed by FedUpWith-Tech** 2020-09-22 18:50 UTC
Labels: Duplicate
