### ISSUE TITLE
Forge 1.16.4 crash with dynmap

### ISSUE THREAD

**Issue by BugmanBugman** [webbukkit/dynmap#3190] opened 2020-11-21 20:32 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Honestly have no idea what happened. The server just crashed out of no where.*

* **Dynmap Version:** *dynmap-version*
* **Server Version:** *forge 1.16.4*
* **Pastebin of Configuration.txt:** https://hatebin.com/dmahsiomzs
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://hatebin.com/qhgfqodmec*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** Not sure

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this* haven't yet but i disabled it

**Comment by FedUpWith-Tech** [comment] 2021-08-20 16:05
Duplicate of #3231

**Closed as completed by FedUpWith-Tech** 2021-08-20 16:05 UTC
Labels: Duplicate
