### ISSUE TITLE
Error when reloading server (or) plugin

### ISSUE THREAD

**Issue by AllPlayed** [webbukkit/dynmap#2439] opened 2019-02-04 16:15 UTC
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [ ] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [ ] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
When I try to reload the plugin, when a Maps load, it appears this message.
You have the error log on Additional Information

## Reproduce Steps
1. Error on plugin and server reload

## Additional Information
Full error log https://pastebin.com/fkLmJTeM

**Comment by FedUpWith-Tech** [comment] 2020-07-29 00:23
Duplicate of #2440

**Closed by FedUpWith-Tech** 2020-07-29 00:23 UTC
Labels: Bug, Duplicate, Won't fix
