### ISSUE TITLE
fullrender not fully rendered...

### ISSUE THREAD

**Issue by Dragon-Knight** [webbukkit/dynmap#2869] opened 2020-04-12 19:11 UTC
Hello, please help with my problem.

There is a very old world version beta 1.7.2 (years 2010-2011), with an approximate radius of 5000 blocks, which was converted by the "--forceUpgrade" command.
When I try to make a complete map for this world, I get only a fragment of the map where the players were. Moreover, if you go abroad the rendered map, a new world is NOT generated there, but the old one is loaded and after that it appears on the map.

![изображение](https://user-images.githubusercontent.com/13180639/79077434-725c0680-7d0a-11ea-9e2b-12d83f55a42f.png)

``>dynmap fullrender world_b172_normal
[21:55:02] [Server thread/INFO]: Full render starting on world 'world_b172_normal'...
[21:55:17] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' in progress - 100 tiles rendered (148,21 msec/tile, 112,52 msec per render)
[21:55:31] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' in progress - 200 tiles rendered (142,59 msec/tile, 109,18 msec per render)
[21:55:43] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' in progress - 300 tiles rendered (133,62 msec/tile, 101,22 msec per render)
[21:55:56] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' in progress - 400 tiles rendered (130,17 msec/tile, 98,34 msec per render)
[21:56:07] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' in progress - 500 tiles rendered (123,57 msec/tile, 91,62 msec per render)
[21:56:10] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'world_b172_normal' completed - 519 tiles rendered (121,47 msec/map-tile, 89,21 msec per render)
[21:56:58] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'world_b172_normal' in progress - 100 tiles rendered (482,64 msec/tile, 372,65 msec per render)
[21:57:51] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'world_b172_normal' in progress - 200 tiles rendered (438,28 msec/tile, 295,32 msec per render)
[21:58:11] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'world_b172_normal' in progress - 300 tiles rendered (357,35 msec/tile, 237,25 msec per render)
[21:58:34] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'world_b172_normal' in progress - 400 tiles rendered (316,55 msec/tile, 213,53 msec per render)
[21:58:45] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'world_b172_normal' completed - 470 tiles rendered (290,89 msec/map-tile, 198,10 msec per render)
[21:59:14] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' in progress - 100 tiles rendered (289,60 msec/tile, 241,00 msec per render)
[21:59:43] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' in progress - 200 tiles rendered (286,65 msec/tile, 236,00 msec per render)
[22:00:09] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' in progress - 300 tiles rendered (278,12 msec/tile, 228,21 msec per render)
[22:00:34] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' in progress - 400 tiles rendered (268,84 msec/tile, 220,05 msec per render)
[22:00:55] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' in progress - 500 tiles rendered (253,69 msec/tile, 206,49 msec per render)
[22:01:07] [Dynmap Render Thread/INFO]: Full render of map 'cave' of 'world_b172_normal' completed - 570 tiles rendered (238,24 msec/map-tile, 192,42 msec per render)
[22:01:07] [Dynmap Render Thread/INFO]: Full render of 'world_b172_normal' finished.
``

**Comment by D0ublek1ll** [comment] 2020-04-14 09:22
Try loading the chunks manually by going to the positions and type /dynmap render and then /dynmap updaterender

Also, a Radius render might work for you.

**Comment by Dragon-Knight** [comment] 2020-04-14 16:38
Thank you very much for your response.

'radiusrender' behaves exactly the same as 'fullrender'. If you manually move to the black area on the map, the map is rendered automatically without using the render \ updaterender commands. This assumption is that chunks have the status "not rendered" and dynmap ignores them, and when the player gets into this chunk, it changes the status to" rendered " and dynmap immediately displays it. 

I suspect that this is due to the fact that the world is more than 10 years old and there is some incompatibility when converting chunks (--forceUpgrade).

**Comment by promlgxd** [comment] 2020-05-04 17:47
i dont think so, i have the same problem converting from a 1.12.2 world to 1.14.4

**Comment by FedUpWith-Tech** [comment] 2020-07-28 23:16
Duplicate of #2282

**Closed as completed by FedUpWith-Tech** 2020-07-28 23:16 UTC
Labels: Duplicate, Render Issues, World Conversion
