### ISSUE TITLE
Marker From Banner Json

### ISSUE THREAD

**Issue by murat716** [webbukkit/dynmap#3373] opened 2021-05-24 09:16 UTC
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*
I want to create marker from banners. There is a have option for this?

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:16
Duplicate of #2266

**Closed as completed by FedUpWith-Tech** 2021-08-20 00:16 UTC
Labels: Duplicate
