### ISSUE TITLE
Console errors all the time because of incompatibilty?

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#1914] opened 2016-03-17 19:34 UTC
I am using Terrain Control for generating my world. Since the 1.9 update I get these errors spammed in the console:

http://pastebin.com/gQPsVuqk

Are you able to fix it?
I am on latest Spigot 1.9 Dev Build + Latest Terrain Control + Latest Dynmap

**Comment by bloggy** [comment] 2016-03-23 09:59
Any update on this???

**Comment by gbl** [comment] 2016-03-25 12:00
Duplicate of https://github.com/webbukkit/dynmap/issues/1908 ?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 18:26
Duplicate of #1908, fixed in later builds of TerrainControl

**Closed by FedUpWith-Tech** 2020-07-28 18:26 UTC
Labels: Duplicate, Not Dynmap related
