### ISSUE TITLE
layerprio doesn't seem to work

### ISSUE THREAD

**Issue by soopageek** [webbukkit/dynmap#1770] opened 2015-04-23 14:13 UTC
This may very well be a local problem, but just in case it's not, here's a ticket.  I'm at my wits end with this.

No matter what I do, I can't get layerprio to have any effect on the order of layers.  I've tried setting them all to zero. I've also tried setting "Players" in configuration.txt to zero and all of the ones in markers.yml to be a simple ascension of 1 through 5 (current number of layers I'm working with).  No matter what I do, the order of the layers are always the same and changing layerprio has no effect.

This was ocurring for me in dynmap2.1 and still is occuring with 2.2.  I'm running spigot1.8.3

**Comment by wtchappell** [comment] 2016-02-05 18:01
I've discovered this issue too.


The current code calls addToLayerSelector in an arbitrary order, which then tries to look at all marker sets it knows about and re-sort them. Finally, it removes all previous layers and then adds the 'current' set with the new marker. I suspect that the removes aren't working, or that Leaflet (the map JS library being used here) is 'reviving' the old layer in its old position when Dynmap removes and re-adds.

I hacked Dynmap's Javascript to sort the marker sets before ever attempting to add any of them, which seems to work. Unfortunately I'm just sorting alphabetically - it shouldn't be hard to sort by prio as well.

Note that "Players' specifically is an odd duck - it isn't added at the same point as the other Marker sets, and so it tends to end up at the top or the bottom. I haven't looked at fixing it, but presumably it should be sorted with the other sets before ever being added as well.

**Comment by SimonOrJ** [comment] 2016-08-29 19:44
I'm having this issue as well.  It seems like this hasn't been fixed.  Honestly, the marker system is pretty unstable.  Reloading the dynmap makes everything go haywire with it.

**Comment by SimonOrJ** [comment] 2016-08-30 04:40
I've found the issue and a a solution.

# The Solution

Add:
```js
                me.layersetlist[i].layer._leaflet_id = undefined;
```

under this `for` loop in [`map.js:936`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/map.js#L936).  The result will look as follows:
```js
		if(me.options.showlayercontrol != "false") {
			for(i = 0; i < me.layersetlist.length; i++) {
				me.layercontrol.removeLayer(me.layersetlist[i].layer);
				me.layersetlist[i].layer._leaflet_id = undefined;
			}
			for(i = 0; i < me.layersetlist.length; i++) {
				me.layercontrol.addOverlay(me.layersetlist[i].layer, me.layersetlist[i].name);
			}
		}
```

## Caveat

All layer checkboxes will be unchecked even when it's enabled.  You'll need to check and un-check it to actually hide the layer from the map.

# The Issue

This traces all the way back to this part:

in [`map.js:908`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/map.js#L908):
```js
	addToLayerSelector: function(layer, name, priority) {
		var me = this;
		if(me.options.showlayercontrol != "false" && (!me.layercontrol)) {
			me.layercontrol = new DynmapLayerControl();
			/* ... */
		}
		/* ... */
		me.layersetlist.sort(function(a, b) {
			if(a.priority != b.priority)
				return a.priority - b.priority;
			else
				return ((a.name < b.name) ? -1 : ((a.name > b.name) ? 1 : 0));
		});
		if(me.options.showlayercontrol != "false") {
			for(i = 0; i < me.layersetlist.length; i++) {
				me.layercontrol.removeLayer(me.layersetlist[i].layer);
			}
			for(i = 0; i < me.layersetlist.length; i++) {
				me.layercontrol.addOverlay(me.layersetlist[i].layer, me.layersetlist[i].name);
			}
		}
```

All the layers are in order. That's expected and okay, since we want to re-order all the layers.

However, the problem comes with this.  The `DynmapLayerControl()` class extends Leaflet's `L.Control.Layers` object as shown in [`dynmaputils.js:46`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/dynmaputils.js#L46):
```js
var DynmapLayerControl = L.Control.Layers.extend({
    /* ... */
});
```

Everything is alright so far.

If you take a deeper look into Leaflet's data, you'll come across the `L.stamp()` function in [`leaflet.js:56`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/leaflet.js#L56):
```js
	stamp: (function () {
		var lastId = 0, key = '_leaflet_id';
		return function (/*Object*/ obj) {
			obj[key] = obj[key] || ++lastId;
			return obj[key];
		};
	}()),
```

This function seems to keep track of the id of the layers.  As far as I see, it looks like the same layer will carry around the same stamp.

Take a look at `DynmapLayerControl().addOverlay()`, which is the same thing as `L.Control.Layers.addOverlay()` in [`leaflet.js:7650`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/leaflet.js#L7650)
```js
	addOverlay: function (layer, name) {
		this._addLayer(layer, name, true);
		this._update();
		return this;
	},
```

If you look into `this._update()`, you will come across this: [`leaflet.js:7734`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/leaflet.js#L7734)
```js
	_update: function () {
		/* ... */
		for (var i in this._layers) {
			if (this._layers.hasOwnProperty(i)) {
				var obj = this._layers[i];
				this._addItem(obj);
				overlaysPresent = overlaysPresent || obj.overlay;
				baseLayersPresent = baseLayersPresent || !obj.overlay;
			}
		}
	/* ... */
	},
```

`for (var i in this._layers)` means "for every key in object/array", and the objects/arrays are always ordered from lowest to highest number.  Check out what happens before `_update()` is called: `this._addLayer()` in [`leaflet.js:7708`](https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/js/leaflet.js#L7708):
```js
	_addLayer: function (layer, name, overlay) {
		var id = L.stamp(layer);

		this._layers[id] = {
			layer: layer,
			name: name,
			overlay: overlay
		};
		/* ... */
	},
```

If the layer that previously existed gets a new "stamp" or "id", there would be no ordering issues.  However, this will always give the same id for an the layer that has appeared in there before.  I confirmed this hypothesis by adding `console.log(id, name);` at the end of the `_addLayer` function.  The input receives things in the wanted order, but because of the "id" value, the order gets re-ordered by the "id" every time.  Here's the sample console log on refreshing the page:
```js
leaflet.js?_=2.3-2074:7710 16 "Players" // this would be the start of the array.
leaflet.js?_=2.3-2074:7710 21 "World Border" // this after first iteration
leaflet.js?_=2.3-2074:7710 16 "Players"
leaflet.js?_=2.3-2074:7710 21 "World Border" //
leaflet.js?_=2.3-2074:7710 16 "Players"
leaflet.js?_=2.3-2074:7710 22 "Signs"
leaflet.js?_=2.3-2074:7710 21 "World Border" //
leaflet.js?_=2.3-2074:7710 16 "Players"
leaflet.js?_=2.3-2074:7710 23 "Towns"
leaflet.js?_=2.3-2074:7710 22 "Signs"
leaflet.js?_=2.3-2074:7710 21 "World Border" //
leaflet.js?_=2.3-2074:7710 16 "Players"
leaflet.js?_=2.3-2074:7710 24 "Nether Highway"
leaflet.js?_=2.3-2074:7710 23 "Towns"
leaflet.js?_=2.3-2074:7710 22 "Signs"
leaflet.js?_=2.3-2074:7710 21 "World Border" //
leaflet.js?_=2.3-2074:7710 16 "Players"
leaflet.js?_=2.3-2074:7710 24 "Nether Highway"
leaflet.js?_=2.3-2074:7710 25 "Major Roads"
leaflet.js?_=2.3-2074:7710 23 "Towns"
leaflet.js?_=2.3-2074:7710 22 "Signs"
// and so on...
```

However, due to the preserved ids and its usage in the `_update` function, dynmap keeps displaying the weird ordering every single time.

I've forked this to try to resolve this issue.

**Comment by SimonOrJ** [comment] 2016-08-30 06:09
# Solution:
Apply https://github.com/SimonOrJ/DynmapCore/commit/0267607937df2b02b6490eea69d2343ed803a407 and https://github.com/SimonOrJ/DynmapCore/commit/630077e403c65552f75a2af44aea2228ad097cc7

**Comment by Psy-Virus** [comment] 2018-12-06 12:49
This has already been merged. Closing this...

**Closed by Psy-Virus** 2018-12-06 12:49 UTC
