### ISSUE TITLE
Full render getting stuck

### ISSUE THREAD

**Issue by lukeeexd** [webbukkit/dynmap#2320] opened 2018-09-04 11:13 UTC
Running full render and it gets stuck at the same place every time. https://tws-mc.com:8123/ it renders what you see in https://i.imgur.com/be8dFai.png. I've purged the map files 3 times now and everytime it gets stuck in this same place and wont render past what it has rendered now,

Edit: It has now stopped the full render, even though it is not even nearly finished 
Gets stuck here https://i.imgur.com/n0EMDq4.png

Dynmap version: core=3.0-alpha-3-111, plugin=3.0-alpha-3-111
Paper version git-Paper-213 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by smmmadden** [comment] 2018-09-04 12:40
is this on an upgraded <1.13 created world and if so which version?  No one (yet) has announced that upgrading worlds to 1.13.x is supported yet.

**Comment by smmmadden** [comment] 2018-09-04 19:52
that's what I thought it might be.  I don't think we're there yet to say previously generated worlds will be upgraded to newly generated dynmaps for 1.13.1.  It may not be far off, but it isn't there yet unless Spigot, Paper, etc. truly support upgrading older maps.

**Comment by lukeeexd** [comment] 2018-09-04 22:26
Once the server restarted it continued rendering

**Comment by mikeprimm** [comment] 2018-09-06 05:30
I've honestly never tested with Paper - I'll pull it down and see what we can do.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 23:14
Duplicate of #2282

**Closed by FedUpWith-Tech** 2020-07-28 23:14 UTC
Labels: Bug, World Conversion
