### ISSUE TITLE
Minecraft Dynmap Leaves are not working

### ISSUE THREAD

**Issue by HugoNordenswan** [webbukkit/dynmap#2954] opened 2020-05-29 10:24 UTC
Hey! I have started a Minecraft server and i have made a custom map in Worldpainter, then i have added the plugin Dynmap. I run no mods, the server is 1.14.4 (newest version bukkit can support) and i have tried different dynmap versions. But for some reason the leaves in my map are not showing (some are but the vast majority isn't there), they are there in the map but not on dynmap. I got one warning:

[WARNING] Plugin dynmap v3.0-beta-5-218 does not specify an api-version.

But that was it. Can somebody please help me? You will get a free rank on my server if you can solve the problem. Thank you!

Dynmap: http://51.89.50.8:40000/

**Comment by FedUpWith-Tech** [comment] 2020-08-01 02:42
Duplicate of #3046

**Closed as completed by FedUpWith-Tech** 2020-08-01 02:42 UTC
Labels: Duplicate, Support Question
