### ISSUE TITLE
Does not work on Paper?

### ISSUE THREAD

**Issue by EsserGaming** [webbukkit/dynmap#2680] opened 2019-12-05 22:00 UTC
When I tried installing the plugin, the console gave me alot of errors and does not enable. Here's an exsample: (https://drive.google.com/file/d/1-pvVyt8aQa_bygEbAYni2_OwJIistqx_/view?usp=sharing)

also, I am using the latest BETA of Dynmap on 1.14.4

**Comment by fihovi** [comment] 2019-12-07 09:03
Paper is another platform, pretty new, so unfortunately not. At least is not defined in README in section supported platforms besides bukkit & forge

Duplicate of #2665. 
#2670 Should fix this
Try this [https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility](url)
or [https://github.com/SijmenSchoon/dynmap/releases/tag/v3.0-beta-7](url)

**Comment by fihovi** [comment] 2019-12-07 09:42
Duplicate of #2665. 
#2670 Should fix this

**Comment by fihovi** [comment] 2019-12-07 09:44
Try this [https://github.com/SijmenSchoon/dynmap/releases/tag/v3.0-beta-7](url)

**Comment by steveabraham** [comment] 2019-12-11 08:45
Works fine on Paper for us, we’ve used it straight out of the box with Paper for years.

**Comment by Technoguyfication** [comment] 2019-12-11 20:02
Dynmap has worked perfectly for me on Paper for about three months now. Same Dynmap version the whole time. Your log mentions LuckPerms, maybe check and make sure LuckPerms is the correct version. I'm running LP v4.41

![](https://tkno.pw/2YDh2rG)

**Comment by EsserGaming** [comment] 2019-12-14 07:48
Thank you @fihovi!

**Closed as completed** 2019-12-14 07:48 UTC
