### ISSUE TITLE
Dynmap 3.0b5 missing random patches in render

### ISSUE THREAD

**Issue by YourDistrictCongressman** [webbukkit/dynmap#2566] opened 2019-07-29 13:19 UTC
Hi there, I have these random patches of un-rendered area in my dynmap.

Here is a screenshot of the issue: https://imgur.com/a/zaCwjpO

Here is a description of what I've done so far:

Setup:

Installed WorldBorder and Dynmap
Set WorldBorder Radius, then ran "fill" command to pre-render the blocks
Ran Dynmap "fullrender" command

Troubleshooting:

-After noticing missing chunks in map render, ran another map 'fullrender'  this seemed to help decrease the missing render areas, but subsequent fullrenders did not help.
-Read up on different commands, first tried (my world name is MineShaft):
```
/dynmap radiusrender MineShaft -1344 -1912 200
/dynmap radiusrender MineShaft -288 -1904 200
/dynmap radiusrender MineShaft 736 -872 200
/dynmap radiusrender MineShaft -792 -1624 300
```
selecting 4 different points in the black areas, in hopes this command would specifically render the missing areas, this seemed to do nothing despite getting messages saying 'x tiles rendered at x speed', and eventually a 'render complete' message for each command.
-Read up on FullRenderLocations in the world.txt file, added coordinate points in the black areas to this file like so:
```
  #  fullrenderlocations:
  #    - x: -1344
  #      y: 64
  #      z: -1912
  #    - x: -288
  #      y: 64
  #      z: -1904
  #    - x: 736
  #      y: 64
  #      z: -872
  #    - x: -792
  #      y: 64
  #      z: -1624
```
Also set " #enabled: true" in the world.txt file and ran another full render, this also did not help.

The only thing I didn't do so far is restart my server.  Is that required for the fullrender command to pick up on the changes to the world.txt file?

I know I could just teleport or travel to the un-rendered areas, but I want to just render everything automatically, I also want to expand the worldborder radius in the future and would love to work out the kinks in Dynmap.

Is it possible the WorldBorder fill command did not complete 100% successfully?  It ran and completed without errors, and seems to have worked correctly.  Perhaps I will re-run the fill command.

Dynmap version:  Dynmap 3.0 beta 5 (for Spigot)
Minecraft Server: Paper 1.14.4 build 146
OS: Windows 7 Pro x64
CPU: i7-4770k
RAM: 16GB (8gb dedicated to minecraft server in java flags)
Storage: 1tb Samsung Evo 850 NVMe drive

**Comment by FedUpWith-Tech** [comment] 2020-08-01 00:26
Duplicate of  #2485

**Closed as completed** 2021-12-17 18:10 UTC
Labels: Bug, Render Issues
