### ISSUE TITLE
1.15.1 problem

### ISSUE THREAD

**Issue by Axeera** [webbukkit/dynmap#2709] opened 2019-12-20 17:41 UTC
This problem startet to come upp after changing to 1.15.1

![Untitled-1](https://user-images.githubusercontent.com/59096481/71278588-47fbcd00-2358-11ea-90e6-e0c9ba70fc78.png)

**Comment by MitchTalmadge** [comment] 2019-12-21 01:53
Looks like a duplicate of https://github.com/webbukkit/dynmap/issues/2705

**Comment by mikeprimm** [comment] 2019-12-21 02:28
Yep - will discuss on #2705

**Closed as completed by mikeprimm** 2019-12-21 02:28 UTC
