### ISSUE TITLE
Black holes in my dynamp

### ISSUE THREAD

**Issue by Stejs1k** [webbukkit/dynmap#3576] opened 2021-12-23 15:41 UTC
Hello, I have problem with my dynmap, I used chunkpregenerator to generate chunks, but my dynmap is rendered with some weird holes:
![image](https://user-images.githubusercontent.com/84089957/147262510-0b9195c6-5f72-4509-9b17-cc6cc7815c6a.png)

**Comment by FedUpWith-Tech** [comment] 2021-12-23 15:42
Did you leave dynmap running while the chunk pregenerator was running?

**Comment by Stejs1k** [comment] 2021-12-23 15:45
> 

no

**Comment by Stejs1k** [comment] 2021-12-23 15:46
> Did you leave dynmap running while the chunk pregenerator was running?

I had dynmap on, but dynmap generation was off

**Comment by FedUpWith-Tech** [comment] 2021-12-23 16:16
these are either errors in the world generation or errors in fullrender. To me, it seems like errors in the world generation (the pregenerator didn't fully generate edge chunks) and as such dynmap can't fully see them.

I suggest teleporting to each black spot on the map and then doing a `/dynmap radiusrender 100`

**Comment by FedUpWith-Tech** [comment] 2021-12-23 16:21
Duplicate of #2485

**Comment by FedUpWith-Tech** [comment] 2021-12-23 16:23
Going to mark this as a duplicate now since that seems like the most likely candidate. There's no quick solution other than a player visiting all unrendered chunks

**Closed as completed by FedUpWith-Tech** 2021-12-23 16:23 UTC
Labels: Support Question

**Comment by Stejs1k** [comment] 2021-12-23 17:00
didnt helped

**Comment by FedUpWith-Tech** [comment] 2021-12-23 17:55
Have you cleared web cache? Teleporting to those spots and radiusrendering will solve this.
