### ISSUE TITLE
Missing Map When Zoomed Out

### ISSUE THREAD

**Issue by AquaLawng** [webbukkit/dynmap#2865] opened 2020-04-11 14:13 UTC
Does anyone know what causes this? When zoomed all the way out, all areas explored render perfectly except for these 2 black bars. But when you zoom in on them, the map renders and shows what was missing from the zoomed out perspective.

EDIT: Nether is even worse

![Render](https://user-images.githubusercontent.com/61892317/79046138-147dd080-7bdd-11ea-826d-89b7416b332b.png)
![Zoom](https://user-images.githubusercontent.com/61892317/79046141-18115780-7bdd-11ea-9ade-742fb32feb92.png)
![nether](https://user-images.githubusercontent.com/61892317/79046258-e3ea6680-7bdd-11ea-9e46-61f0f14f79d0.png)

**Comment by D0ublek1ll** [comment] 2020-04-14 09:32
/dynmap fullrender <worldname>

It may take a while.

**Comment by ice-fly** [comment] 2020-04-30 05:40
Your render was interrupted and parts of tiles are incomplete do a full render

**Comment by FedUpWith-Tech** [comment] 2020-07-31 19:30
Duplicate of #2485

**Closed as completed** 2021-12-17 18:47 UTC
Labels: Duplicate
