### ISSUE TITLE
Marker names including a ' change it to the HTML code after a while

### ISSUE THREAD

**Issue by NathanCollaert** [webbukkit/dynmap#2481] opened 2019-05-17 18:52 UTC
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [ ] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [ ] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Dynmap markers including a ' in their marker name will after a while change the ' to their HTML code `&#39;`.

## Reproduce Steps
1. Make a marker with a ' in it's name.
2. Wait a couple of minutes and it will change to the HTML code.

**Comment by miiichael** [comment] 2019-11-02 09:35
This issue might be a dupe of #2288? Also, #2364 suggests that setting `markup=true` might help.

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:57
Duplicate of #2288 
Set `markup=true` on each marker with an offending character to fix

**Closed by FedUpWith-Tech** 2020-07-28 22:57 UTC
Labels: Duplicate, Marker Issues
