### ISSUE TITLE
Marker Shows HTML Symbol instead of actual symbol.

### ISSUE THREAD

**Issue by OskarZyg** [webbukkit/dynmap#3145] opened 2020-10-10 09:50 UTC
**Issue Description:** *When special characters are used, for example, an apostrophe, dynmap shows sanitised HTML .*

![image](https://user-images.githubusercontent.com/56176746/95651941-7617ec80-0ae5-11eb-9b40-2408fbd9527a.png)
![image](https://user-images.githubusercontent.com/56176746/95651959-92b42480-0ae5-11eb-9b8e-a0e512c6c73b.png)

* **Dynmap Version:** *core=3.1-beta4-421*
* **Server Version:** *Paper 1.16.3 (shows on other versions too)*
* **Pastebin of Configuration.txt:** *only contains title changes and ports*
* **Server Host (if applicable):** *Self Hosted.*
* **Pastebin of crashlogs or other relevant logs:** *none*
* **Other Relevant Data/Screenshots:** *none*
* **Steps to Replicate:** *Create a marker with an apostrophe or a different special character. *

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2020-10-11 14:32
Duplicate of #2288

**Closed as completed by FedUpWith-Tech** 2020-10-11 14:32 UTC
Labels: Bug, Duplicate, Workaround available
