### ISSUE TITLE
We are having issues putting the character <'> on markers labels.

### ISSUE THREAD

**Issue by mMagenta** [webbukkit/dynmap#2606] opened 2019-09-08 19:59 UTC
Hi! We are having some problems with this character, <'>, when we wanto to write it on a label. The thing is that initially, this apostrophe works fine, but next time you refresh... Gone. 

First:
https://gyazo.com/9533e13bec2e191a3d8bfa1e3512bec9

After refresh:

https://i.gyazo.com/62b76ad66bc8c9299de669891ea71fcd.png

The plugin is on 3.0-beta build. Does anyone know why is it like this? Maybe there is a solution.

Thanks!

**Comment by ghost** [comment] 2019-09-26 18:51
I'm also having this issue (Firefox and IE).

I was also going to mention that colour codes (§4 etc.) from the server name appear as characters in the Dynmap webpage title, where I'm fairly sure they used to be stripped out.

**Comment by miiichael** [comment] 2019-11-02 09:35
This issue might be a dupe of #2288? Also, #2364 suggests that setting `markup=true` might help.

**Comment by ghost** [comment] 2019-11-03 12:42
Setting `markup=true` worked for me.  Is this the permanent solution or will it likely be fixed?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:56
Duplicate of #2288

**Closed as completed by FedUpWith-Tech** 2020-07-28 22:56 UTC
Labels: Duplicate, Marker Issues
