### ISSUE TITLE
Fabric Version

### ISSUE THREAD

**Issue by DraxxisGH** [webbukkit/dynmap#2711] opened 2019-12-21 02:21 UTC
Will a Fabric version of Dynmap be released at any point? Is there any plans for it?

**Comment by mikeprimm-triva** [comment] 2019-12-21 16:06
It came up recently, but I haven't looked in to it - need to see how practical supporting it would be

**Comment by DraxxisGH** [comment] 2020-04-12 00:02
Has there been any progress on this?

**Comment by FedUpWith-Tech** [comment] 2020-07-31 17:16
Duplicate of #2697

**Closed as completed by FedUpWith-Tech** 2020-07-31 17:16 UTC
Labels: Duplicate, Under Consideration, Feature Request
