### ISSUE TITLE
Existing modded Fabric 1.17.1 server is crashing when adding Dynmap, with an "Index out of bounds for length" exception.

### ISSUE THREAD

**Issue by wolfsprite** [webbukkit/dynmap#3511] opened 2021-10-07 00:19 UTC
**Issue Description:** Fabric server for Minecraft 1.17.1 with over 100 mods has been live for a few days, mostly without issue. Attempting to add Dynmap and start/restart the server though, leads to a crash, caused by exception "Index *x* out of bounds for length *y*". The crash continues to happen each time a boot attempt is made, until the Dynmap .jar is removed from the mods folder, after which the server starts again without issue. Dynmap does generate a dynmap folder.

* **Dynmap Version:** Dynmap-3.2.1-fabric-1.17.1.jar (and also happened with Dynmap-3.2-beta-3-fabric-1.17.1.jar)
* **Server Version:** 1.17.1/Fabric
* **Pastebin of Configuration.txt:** Configuration.txt was not altered, is available here though: https://pastebin.com/AM0QnB0u
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/hSqtT6Dv
* **Other Relevant Data/Screenshots:** As mentioned earlier, there are over 100 mods on the server. However, the server refuses to start if dynmap is added to the mods folder, and runs/starts fine when dynmap's jar is not there.
* **Steps to Replicate:** Play around on a server/world with a large amount of Fabric mods without dynmap, then attempt to add dynmap after a lot of chunks have been generated. Dynmap runs and creates dynmap directory, then server crashes and won't start. Removing dynmap jar allows the server to start again.

 

[yes] *I have looked at all other issues and this is not a duplicate*  

[yes] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-10-07 13:14
What all mods do you have? I can't replicate this with Dynmap on its own but there are some known conflicts with other mods

**Comment by wolfsprite** [comment] 2021-10-08 04:00
List of .jars in mods folder for server in initial report: https://pastebin.com/FNJni10P

It is also happening on another server/world with about 40 mods, list here: https://pastebin.com/tsJNEFxD

Thought at first that it may have been Applied Energistics 2, or Requiem 2.0, which is in early alpha, but trying to run dynmap on that second server (without those) has the same error.

Am noticing this in the logs now though, each time, which had not previously noticed:
`[Server thread/FATAL]: [Dynmap] Error reading dynmap/markers.yml`
This is the only error, fatal or not, that Dynmap mentions prior to crashing the server with the index out of bounds for length.

I looked into the dynmap folder that gets generated, and there was an empty markers file, but no markers.yml file.

We ended up switching to BlueMap, which is working fine on both servers, but I would still like to help figure out what the issue with this is.

**Comment by Patbox** [comment] 2021-10-08 10:45
It's the same issue as https://github.com/webbukkit/dynmap/issues/3495

**Comment by FedUpWith-Tech** [comment] 2021-10-08 17:27
Duplicate of #3495

**Comment by FedUpWith-Tech** [comment] 2021-10-08 17:28
Since its a duplicate we will consolidate it down to a single issue thread

**Closed as completed by FedUpWith-Tech** 2021-10-08 17:27 UTC
Labels: Duplicate, Bug Report, Fabric

**Comment by wolfsprite** [comment] 2021-10-08 23:45
Removed graves-1.1.0+1.17.1.jar from mods folder after seeing this, and can confirm that Dynmap started up with zero issues after that, so Universal Graves is definitely the culprit. 👍
