### ISSUE TITLE
/dynmap webregister doesn't work for Geyser players

### ISSUE THREAD

**Issue by t0mtee** [webbukkit/dynmap#3514] opened 2021-10-10 15:53 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:**
If a Geyser player tries to register, the code doesn't work in the register menu.

* **Dynmap Version:** *3.2.1-531*
* **Server Version:** *Paper 1.17.1 v321*
* **Pastebin of Configuration.txt:** *[Link](https://mcpaste.io/c9f0bb37a77903f0)*
* **Server Host (if applicable):** *PebbleHost*
* **Steps to Replicate:**

1. Try to register on Bedrock using Geyser
2. See the error

 [x] *I have looked at all other issues and this is not a duplicate*  
 [players on my server have] *I have been able to replicate this*

**Comment by generrosity** [comment] 2021-12-02 03:33
Have you also reported this to Geyser to see if they can assist with diagnostics? There might be some fundamental differences in user IDs, and what assumptions are made about users .... it might not make sense for a bedrock player to be able to registery as a forge user??

**Comment by generrosity** [comment] 2021-12-02 04:11
Also - possibly related to feature request to support Geyser UUIDE https://github.com/webbukkit/dynmap/issues/3461#issuecomment-902366645

**Comment by FedUpWith-Tech** [comment] 2021-12-21 22:19
Yeah, I'm going to mark this as a duplicate of #3449

**Closed as completed by FedUpWith-Tech** 2021-12-21 22:19 UTC
Labels: Duplicate
