### ISSUE TITLE
Dynmap stops writing new created markers to markers.txt after about 10 markers

### ISSUE THREAD

**Issue by thiefa** [webbukkit/dynmap#2414] opened 2019-01-11 07:40 UTC
## Server Information

- I can reproduce this issue consistently
     - [X] In Multiplayer 
     - [ ] After deleting/renaming the DYNMAP folder
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [X] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Reproduce Steps
1.
2.
...

## Additional Information
Simillar to "Markers Disappearing after Dynmap reload or server restart #2242"

i use Bytecart for railway transportation, thus having about 30 Markers for the Stations and far more for tracks and routers.
never had an issue on older versions of dynmap allthought i just started to mark traks & routers with dynmap v3

since im on 1.13.2 and Dynmap3+ i deleted my worlds tiles folder to re-render.
at the first starts dynmap brought errors because of the marker file, so i deleted it aswell, as i thought there might have been updates to Dynmap that arent going well thogether with old markers.txt.

so while dynmap was rendering, i was redoing the station markers, they showed up on dynmap for a while, then they disapeared, exept a few.
checking the markers.txt, i figured out those stations still left where still written in the markers.txt, while newly created stations pop up in dynmap, but dosent get written to the markers file.. so after a brief moment, they disapear again.

as a workaround i cloned an existing marker, and edited it to fit for the next place i needed one.. made that for about 20 markers, then i reloaded dynmap. no more markers poped up...

same goes if i do markers with /dmarker add

i then did a restart, and had that damn error about markers.txt again.
as recomended i checked with the yaml checker, ---> no errors in markers.txt
double and trippel checked that i didnt had same marker tags or anything.. all fine.. so deleted all markers down to 10, restartetd again...
dynmap works.. tryed to add markers via command --> markercount ingame was going up (not given special names, so just marker_x) added up to 15, but again just poped up quick in dynmap and no entry in the markers.txt.

really hope for an idea on how to get that working again...

**Comment by thiefa** [comment] 2019-01-16 19:59
tested with dynmap v3.0-beta-3-160 today, could create 83 markers till dynmap stopped writing to markers.txt.

**Comment by thiefa** [comment] 2019-01-28 11:02
hello, 
i fugured if i monitor the markers.txt for changes after creating new markers, and i stop and restart the server after markers havent been written to markers.txt anymore, i can add another 10 or so till it happens again.

markers added that way stay in markers.txt and aslo get rendert on dynmap.. 

so after about 20 restarts i had my most importent markers in place, and they also survive a restart...

for what reason ever, dynmap dosent die with markers.txt created that way.

[Dynamp](http://pia.hopto.org/dynmap)




however its really pain to monitore the file while creating the markers, not to mention all the reboots of the server that can drive anyone crazy...

**Comment by ChimneySwift** [comment] 2020-04-11 04:14
Any progress on this issue?

I'm experiencing the same issue. I have 60 markers, but they were working fine until I did a server restart, now dynmap doesn't want to load them.

MC Version: Spigot 1.15.2

**Comment by ChimneySwift** [comment] 2020-04-18 15:25
Seemed to have resolved my particular issue, one of the marker groups had a `/` in it which dynmap didn't want to load, even though yamllint said it was valid yaml.

**Comment by Laurenshup** [comment] 2020-07-01 11:18
I had this issue too. Removing all "allowed-icons" from each marker set made it work. Some problem with the icons not being loaded at start.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:17
Duplicate of #1936

**Closed by FedUpWith-Tech** 2021-08-20 00:17 UTC
Labels: Bug, Marker Issues
