### ISSUE TITLE
Dynmap Exception while loading chunks in all but Overworld

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#2223] opened 2018-04-07 19:00 UTC
Minecraft Ver: 1.12.2
Forge ver: 14.23.2.2635
Dynmap Ver: 3.0 alpha 1 forge 1.12.2
Dynmap blockscan ver: 3.0 alpha 1 forge 1.12.2
ModPack: SevTech:Ages  (250 mods)

Dynmap working perfect for the Overworld, also works fine in DIM10 (The Beneath)
Dynmap does nothing for DIM20 (thebetweenlands) Running any form of render states "Render started on DIM20", but dynmap hasn't even created the DIM20 folder in the tiles directory. 
![image](https://user-images.githubusercontent.com/5133282/38459178-6bbc45fe-3a5b-11e8-88a7-62206aa7e2a5.png)

Tried enabling and disabling the world. No change. World does show selectable in dynmaps side menu but is completely black.

dmap maplist DIM20 shows all maps active for that world.
![image](https://user-images.githubusercontent.com/5133282/38459150-137125e0-3a5b-11e8-9aaa-c82b487fd51e.png)

Any thoughts why this world wont render at all.

**Comment by BonaireDreams** [comment] 2018-04-16 19:16
So did some more digging on this. We did finally get renders on DIM20 but now seeing the same challenge on DIM28885. So it's not DIM related. Double checked all the permissions on the tiles folders and they are correct. But I did notice this today when trying a render on DIM28885. It seems its a chunk loading issue.

`> /dynmap fullrender DIM28885:flat
[11:51:05] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render starting on world 'DIM28885'...
[11:51:06] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException: null
        at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:317) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:817) ~[ForgeChunkManager.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:262) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:246) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.access$1500(DynmapPlugin.java:98) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:757) ~[DynmapPlugin$ForgeServer$1.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:753) ~[DynmapPlugin$ForgeServer$1.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:845) ~[DynmapPlugin$ForgeServer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1883_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`
We are currently on Forge 1.12.2-14.23.2.2651 (had the same issue on previous) and Dynmap 3.0-alpha-1-forge-1.12.2  3.0-SNAPSHOT-Dev201801061609

Is there a newer DEV snapshot we should try and see if it eliminates the chunk load challenge?

Thanks

**Comment by BonaireDreams** [comment] 2018-04-20 19:29
Pinging @mikeprimm Help us Obi-wan Kenobi. You're our only hope. :p Happy to test any new 3.0 Dev snapshot you may have ready.

**Comment by mikeprimm** [comment] 2018-04-21 16:41
@BonaireDreams This isn't a fix, but might be helpful - try editing <forge-base-dir>/config/dynmap.cfg file, and change UseForcedChunks setting from 'true' to 'false'.  I'll try to find some time this weekend to see about reproducing the problem, but this MAY help in the short run.

**Comment by BonaireDreams** [comment] 2018-04-22 18:31
Seems to have the trick. Twilight is now rendering! You sir are a genius!! :)
A less important side question. I have Blockscan running as well which has managed to render about 90% of all blocks from unsupported mods. Theres afew that still refuse to render (Abyssalcraft stone for example) I tried to use the Block alias "2068" : 1 to force it to render stone just so we dont have these black holes but it didnt seem to work. Is block alias still supported with the changes to ID's in 1.12?  Not critical if its no longer works, its affecting very small areas of the map.

Thanks again for all you efforts!

**Comment by MattJeanes** [comment] 2018-05-31 20:51
Getting the same problem trying to render DIM-1 aka the nether, Using the jar from `http://mikeprimm.com/dynmap/builds/DynmapForge/Dynmap-2.6-alpha-2-forge-1.12.2.jar`

Changing `UseForcedChunks` to true has fixed it for me too!

May I ask what that setting actually does, and if it may impact render/game performance with it being off?

Thanks!

**Comment by generrosity** [comment] 2018-06-09 10:49
Will try this setting  myself tomorrow. Running from head 25-May

**Comment by FedUpWith-Tech** [comment] 2021-08-19 23:49
Closing due to age, please open a new issue if this is still relevant.

**Closed by FedUpWith-Tech** 2021-08-19 23:49 UTC
Labels: Workaround available, Bug Report
