### ISSUE TITLE
Tab completions for commands

### ISSUE THREAD

**Issue by NJDaeger** [webbukkit/dynmap#2956] opened 2020-05-31 18:29 UTC
Hello,

Sometimes when I use this plugin, it can be challenging to remember the command to run, and or a pain to type the whole command out. I was thinking tab completions might not be a bad idea for the commands of dynmap? It would certainly make the plugin easier to use!

**Comment by FedUpWith-Tech** [comment] 2020-08-01 02:41
duplicate of #2832

**Closed as completed** 2020-08-01 02:42 UTC
Labels: Duplicate, Feature Request
