### ISSUE TITLE
Spigot 1.9 build not supported by Dynmap

### ISSUE THREAD

**Issue by Leesam** [webbukkit/dynmap#1891] opened 2016-03-01 02:06 UTC
Excerpt from the startup log below, dynmap worked before the 1.9 update.

`7:59:11 PM CONSOLE: [INFO] Bukkit version format changed. Version not checked.
7:59:11 PM CONSOLE: [INFO] git-Spigot-7ebe8ff-5eceede (MC: 1.9)
7:59:11 PM CONSOLE: [INFO] 1.9-R0.1-SNAPSHOT
7:59:11 PM CONSOLE: [INFO] Using locale en_US
7:59:11 PM CONSOLE: [INFO] Using locale en_US
7:59:11 PM CONSOLE: [INFO] Essentials: Using PermissionsEx based permissions.
7:59:11 PM dynmap: Enabling dynmap v2.2-1118
7:59:11 PM dynmap: Dynmap is disabled (unsupported platform)`

**Comment by deltaflyer4747** [comment] 2016-03-01 05:29
[06:23:28] [Server thread/INFO]: [dynmap] Loading dynmap v2.2-1118
[06:23:28] [Server thread/INFO]: [dynmap] version=git-Spigot-b27d06a-32587ed (MC: 1.9)
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field biomes for net.minecraft.server.v1_9_R1.BiomeBase
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field temperature for net.minecraft.server.v1_9_R1.BiomeBase
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field humidity for net.minecraft.server.v1_9_R1.BiomeBase
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field y for net.minecraft.server.v1_9_R1.BiomeBase
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field id for net.minecraft.server.v1_9_R1.BiomeBase
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find field chunkProviderServer for net.minecraft.server.v1_9_R1.WorldServer
[06:23:28] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[06:23:28] [Server thread/ERROR]: [dynmap] Unable to find method b for net.minecraft.server.v1_9_R1.TileEntity
[06:23:28] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v2.2-1118 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:129) ~[?:?]
        at org.dynmap.bukkit.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:35) ~[?:?]
        at org.dynmap.bukkit.BukkitVersionHelper.getHelper(BukkitVersionHelper.java:47) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:756) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.9.jar:git-Spigot-b27d06a-32587ed]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.jar:git-Spigot-b27d06a-32587ed]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-b27d06a-32587ed]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by primis** [comment] 2016-03-01 20:00
This has to do with dynmap using 1.7 era API calls, you'll need to update to modern 1.8+ api to get it working again

**Comment by Cosmosis42** [comment] 2016-03-01 23:48
What's the easiest way to do that?

**Comment by Psy-Virus** [comment] 2016-03-02 00:10
There's a PR #1892.
But it isn't merged yet. I also don't know if it's a fix for full compatibility (incl. new blocks etc.) or only a work around to get it working on 1.9....

**Comment by Psy-Virus** [comment] 2016-03-02 00:53
Okay, just compiled it, it's only a work around without new Block rendering, but it runs... maybe @firstEncounter can "complete" his PR(?)

:-)

**Comment by Psy-Virus** [comment] 2016-03-02 01:02
Here's the compiled 1.9 semi-compatible version. Idk if it runs on Spigot, but it does on CB. But as I said, no rendering for new blocks...

[dynmap.zip](https://github.com/webbukkit/dynmap/files/153902/dynmap.zip)

**Comment by MxLinux** [comment] 2016-03-02 02:38
Confirmed does not work on Spigot. 

`[20:31:57] [Server thread/ERROR]: Could not load 'plugins/dynmap.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:743) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d15d07-c194444]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_03]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0_03]
at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0_03]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_03]
at java.util.zip.ZipFile.at java.util.zip.ZipFile.(ZipFile.java:214) ~[?:1.7.0_03]
at java.util.zip.ZipFile.(ZipFile.java:144) ~[?:1.7.0_03]
at java.util.jar.JarFile.(JarFile.java:152) ~[?:1.7.0_03]
at java.util.jar.JarFile.(JarFile.java:116) ~[?:1.7.0_03]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-7d15d07-c194444]
... 21 more`

**Comment by firstEncounter** [comment] 2016-03-02 02:42
It works on Spigot, it looks like you renamed the .zip to .jar and put that in your plugins instead of extracting the .jar.

I'll be looking into the block rendering and whether I want to tackle that as well.

**Comment by primis** [comment] 2016-03-02 02:44
Confirmed that Psy-Virus's posted zip file does work once extracted. This pull request should be a no brainer.

**Comment by MxLinux** [comment] 2016-03-02 02:47
I apologize then, may have been an issue with Safari. Double-clicked the finished download from the download manager and uploaded the "extracted" jar.

**Comment by deltaflyer4747** [comment] 2016-03-02 05:20
I can also confirm that this build works well in spigot 1.9 - thank you!

**Comment by primis** [comment] 2016-03-02 06:56
Latest build fixed this issue :smiley:

**Comment by WyRe** [comment] 2016-03-02 19:36
@primis how could I get latest build? :P

**Comment by Psy-Virus** [comment] 2016-03-02 20:01
[Dynmap-Head.jar](http://dynmap.us/builds/dynmap/dynmap-HEAD.jar)

**Comment by WyRe** [comment] 2016-03-02 20:16
Thanks you so much @Psy-Virus ! :D

**Closed** 2018-12-31 02:33 UTC
Labels: Bug, Fixed
