### ISSUE TITLE
Marker name not proper

### ISSUE THREAD

**Issue by winnipeg21** [webbukkit/dynmap#2844] opened 2020-04-04 19:32 UTC
So I'm using the latest version of Dynmap that's on spigot. When I add marker names and use basic punctuation such as & and ' it spits out I'm guessing the Unicode name for it so &amp; instead of &. Any way to fix this?

**Comment by FedUpWith-Tech** [comment] 2020-08-01 01:50
Duplicate of #2288

**Closed as completed by FedUpWith-Tech** 2020-08-01 01:50 UTC
Labels: Duplicate, Marker Issues
