### ISSUE TITLE
NullPointerException in DynmapCore.java at 441 - Caused by null return from System.getenv("PATH")

### ISSUE THREAD

**Issue by JethroHotep** [webbukkit/dynmap#3198] opened 2020-11-24 14:05 UTC
**Issue Description:** *Getting a NullPointerException in DynmapCore.java at 441 - Caused by null return from System.getenv("PATH")*

* **Dynmap Version:** Dynmap-3.1-beta5-spigot
* **Server Version:** Paper version git-Paper-288 (MC: 1.16.4)
* **Pastebin of Configuration.txt:** irrelevant
* **Server Host (if applicable):** Bisect
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/q4zBpYJB
* **Other Relevant Data/Screenshots:** Added an if statement to return null if System.getenv("PATH") returns null and it is working, just reporting the missing cwebp or dwebp modules rather than blowing up.
* **Steps to Replicate:** Remove (or secure) the PATH env variable.

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

[DynmapCore.zip](https://github.com/webbukkit/dynmap/files/5590355/DynmapCore.zip)

**Comment by gbl** [comment] 2020-11-26 19:55
This is a duplicate of #3170

**Closed as completed** 2021-08-20 16:01 UTC
Labels: Duplicate
