### ISSUE TITLE
[Collection] Dynmap not rendering Pre-Anvil Chunks

### ISSUE THREAD

**Issue by PlagueDog** [webbukkit/dynmap#2282] opened 2018-08-10 14:38 UTC
Dynmaps fullrender doesn't appear to work on pre-anvil worlds. Seems like its seeing the mapchunks as nonexistent. Not sure this is fixable as the gamerule "spectatorsGenerateChunks false" exhibits the same issue. Going into spectator mode then flying over to pre-anvil converted mapchunks will not load. It appears to be a 1.13 bug.

I am using very VERY old worlds. Pre-anvil ones which have been converted to the latest 1.13 world format.

**Comment by mikeprimm** [comment] 2018-08-26 22:12
In spigot, I don't specifically handle loading of chunks - I trust the Spigot API to function properly and allow me to load chunks that way.  I'd need to see if Spigot 1.13 is handling plugin-based chunk loading of worlds that old.  You have an idea how old the worlds are, as far as version?

**Comment by Mickket** [comment] 2018-08-27 09:38
The worlds were from the InfDev versions of Minecraft. I think 1.2.6 alpha was the specific version.  I tested this with the spectator mode in single player with the gamerule "spectatorsGenerateChunks" set to false. It appears that Mojangs world converter for 1.13 is setting converted pre-anvil world chunks to being "new/non-existing" map chunks even though the chunks are not actually so.

The screenshots below show what is happening. The one that appears to be on the edge of the world is me in spectator mode with "spectatorsGenerateChunks" set to false. There are map chunks beyond this which have already been generated a long time ago.

The secondary screenshot is what happens when I turn on "spectatorsGenerateChunks".

![2018-08-10_10 57 59](https://user-images.githubusercontent.com/11625939/44652804-e5402e80-a9ba-11e8-899b-ea5c1767c9f7.png)
![2018-08-10_10 58 18](https://user-images.githubusercontent.com/11625939/44652810-e7a28880-a9ba-11e8-9eef-6e24e87a2a9f.png)

**Comment by mikeprimm** [comment] 2018-12-08 22:55
Yep - I confirmed this problem in the Spigot API, which is what is impacting Dynmap.  Just like 'spectatorGenerateChunks=false', dynmap needs to avoid driving chunk generation, and the fact that vanilla doesn't handle the problem of loading-without-generating with pre 1.13 chunks at least confirms that the problem isn't limited to Spigot, but is a baseline Mojang problem.
In any case, the latest dev builds for Dynmap have a workaround that I think will work - and, as a plus, will drive migration of your pre-1.13 chunks to 1.13 format for you without growing the already-generated world in the process :)   Try https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by XeonG** [comment] 2021-01-27 17:06
Is there nothing that can be done about this with dynmap... I just want to render an older map, that was working fine 1.15 without having to generate all the tiles from areas that were never explored by players anyway.. 

[16:35:54 INFO]: Update render starting on world 'k_world'...
[16:35:54 INFO]: Update render of map 'flat' of 'k_world' completed - 0 tiles rendered (47.00 msec/map-tile, 0.00 msec per render)
[16:35:54 INFO]: Update render of map 'surface' of 'k_world' completed - 0 tiles rendered (51.00 msec/map-tile, 0.00 msec per render)
[16:35:54 INFO]: Update render of 'k_world' finished.

renders nothing... 5gb world... used to render just fine.. now not a thing with 1.16 :/

**Comment by xiphoid24** [comment] 2021-07-30 16:01
Is this still an issue or is there some fix for this? @mikeprimm mentioned the dynmap 3.0 snapshot should have a work around but I am still having this issue.
I have a pre 1.13 world I am running for the first time in awhile. I am using paperMC for Minecraft 1.17 and dynmap v3.2-beta-2. I ran --forceUpgrade to migrate the world before installing dynmap. 
After running a full render only a small radius around spawn renders even though there is much more to the world.

**Comment by villermen** [comment] 2021-12-14 08:49
Adding to @gregpechiro: I've converted my worlds from 1.17 to 1.18 using `--forceUpgrade` on both versions. After this, Dynmap would only render chunks loaded for players in 1.18 upon fullrender. I'm assuming that's the same as "[..] only a small radius around spawn renders even though there is much more to the world."

Setting `migrate-chunks: true` in the config allowed fullrender to render out the upgraded chunks for me. It seems like toggling that option and running `/dynmap fullrender` properly deals with post-Anvil chunks.

**Comment by xiphoid24** [comment] 2021-12-14 13:23
@villermen, yes I think we are referring to the same thing. At the time, I was rendering the world I had only been to the spawn.

 I set `migrate-chunks: true` and ran a full render. I am still experiencing the same issue. The only chunks that render are ones visited since updating the world.  I am not sure if it is because I have a slightly different situation. My world is all pre-anvil chunks that were converted to anvil when updating to 1.13. Those are the chunks that do not render unless revisited.

**Comment by coldice4** [comment] 2021-12-15 09:08
I'm facing the same issue on 1.18.1. I upgraded the world with forceUpgrade, and now only the chunks players visited are rendered. Setting `migrate-chunks: true` didn't change anything.

**Comment by coldice4** [comment] 2021-12-15 16:23
I put a small bash script together to automatically teleport a player around the world in order to fix those chunks.
Requires: 
- bash
- mcrcon

**Description:** The script generates a list of all region files in a given folder. Based on this list it teleports the player to each chunk in that region. It does not check if the chunk was generated before, so your world size might increase considerably.
Because it teleports you to each chunk it has quite a long runtime, on my world around 66 hours. Therefore I save the list of regions in a temporary file and delete each entry after it's done. When starting the script it checks if the file exists and if yes continues with the last region.


```#!/bin/bash
region_path="world/region/*"
player="your playername"
mcrcon_exec="/home/minecraft/minecraft/mcrcon"
rcon_password="your-rcon-password"


if [ -f "chunk_fixer.tmp" ]; then
	echo "continuing from previous run"
else
	for region_file in $region_path
	do
		file=$(basename "$region_file")
		echo $file >> chunk_fixer.tmp
	done
fi


total_files=$(wc -l < chunk_fixer.tmp)
region_counter=0
start_time=$(date +%s)


while [ -f "chunk_fixer.tmp" ]
#for region_file in $region_path
do
	region_counter=$((region_counter + 1))
	region=$(head -n 1 chunk_fixer.tmp)
	echo "current region file: $region"

	IFS='.'
	read -a regionArr <<< "$region"
	
	regionX=${regionArr[1]}
	regionY=${regionArr[2]}
	blockX=$((regionX * 32 * 16))
	blockY=$((regionY * 32 * 16))

	# Only loading the region is not enough, we need to load each chunk
	# Solution: teleport to each individual chunk in the region file
	# Caution: this also teleports to ungenerated chunks in the file, 
	# potentially increasing your world size by a lot
	startX=$((blockX + 8)) # we want to be in the middle of the chunk
	startY=$((blockY + 8))
	for i in {0..31}
	do
		tpX=$((startX + i * 16))
		for j in {0..31}
		do
			tpY=$((startY + j * 16))
			output=$($mcrcon_exec -p $rcon_password "tp $player $tpX 256 $tpY")
			if [ $? -eq 0 ]
			then
				echo -n "."
			else
				echo $output
				exit 1
			fi
			sleep 0.2s
		done
	done
	echo "region done"

	sed -i '1d' chunk_fixer.tmp

	current_time=$(date +%s)
	runtime=$((current_time - start_time))
	avgRegionTime=$((runtime / region_counter))
	approxFinishTime=$(((total_files - region_counter) * avgRegionTime))

	echo "$region_counter of $total_files done"
	echo "Average time per region so far: $avgRegionTime s"
	echo "Approximate time to finish: $approxFinishTime s"	
done
```

**Comment by FedUpWith-Tech** [comment] 2021-12-27 15:05
Hi all! I think @mikeprimm finally has fixed this issue in the snapshot builds 611+ and should be included in the v3.3-beta-4 release.

If you follow along the discussion of  #3565 Mike had to implement a custom light engine to add lighting data to chunks that don't get generated with it using pre-generation plugins and the like. I believe that fix has also fixed this issue.

Unfortunately, I don't have an easy way of testing this aside from spending time pregenerating a bunch of old maps, upgrading them to newer versions, and seeing if this behavior is replicated at all. If anyone on this issue still has dynmap and can test the new beta4 release I would be most appreciative.

**Comment by xiphoid24** [comment] 2021-12-27 16:23
@FedUpWith-Tech I am still using dynmap. Later today I can update dynmap to 3.3 beta 4 and run a full render. I will post here with my results when it is finished. Should migrate-chunks be set to true?

**Comment by WoutervanderLoopNL** [comment] 2021-12-27 18:05
I can confirm that this is the final fix. my world is now generating all the old pre-anvil chunks. 

Thanks @mikeprimm  for this fix after al those years. You are a real legend. ❤️

**Comment by FedUpWith-Tech** [comment] 2021-12-27 18:28
> @FedUpWith-Tech I am still using dynmap. Later today I can update dynmap to 3.3 beta 4 and run a full render. I will post here with my results when it is finished. Should migrate-chunks be set to true?

migrate-chunks should not be needed

**Comment by mikeprimm** [comment] 2021-12-27 19:33
Believe it or not, things will work better if you AVOID --forceUpgrade...  it'll make the whole map have untrustworthy lighting data, which will force me to generate lighting (see earlier comments), which IS a measurable performance hit.  Net-net: we can render 1.17 or 1.16 chunks faster and with better lighting results than we can render the 'migrated-but-not-really' 1.18 chunks that forgeUpgrade creates.    The borders between player activity migrated chunks and the old version chunks will still need 'help' from the lighting workaround in beta-4, but that is a much smaller fraction of your chunks than the whole world being half-ass-migrated 1.18 chunks ;)

**Comment by xiphoid24** [comment] 2021-12-28 14:24
@mikeprimm, so are you saying it is better to not do --forceUpgrade when changing Minecraft versions. Should we update the Minecraft server, run a full render, then run with --forceUpgrade or should we avoid running --forceUpgrade at all?

I thought running --forceUpgrade made the server run better but I am not sure.

**Comment by xiphoid24** [comment] 2021-12-28 14:25
Also @FedUpWith-Tech and @mikeprimm, I did a full render last night and it worked perfectly. Thanks for all you work on this.

**Comment by mikeprimm** [comment] 2021-12-28 14:47
@gregpechiro What I'm saying is relative to how fast our renders will work, and how correct lighting will be (vanilla lighting IS better than what I scribbled up, because it is tied into worldgen and handles all kind of chunk to chunk stuff that I'm not going to do, besides emitted light - which is about an order of magnitude more expensive to compute), using --forceUpgrade is a negative.  To the degree that it is any better for server performance in general - I doubt it, because the translation it does do is pretty trivial versus all the additional worldgen steps that still need to be repeated in order for the chunk to be usable for players (which still happens 'on-demand' versus happening ahead of time).   Best way to describe things:

1.17 chunk -> 1.18 chunk in empty state (but with 1.18 format data) -> 1.18 chunk pulled through worldgen when first activated by players

--forceUpgrade does the first step ahead of time: everything in the following step (which includes discarding then recreating chunk lighting) still happens during normal server activity, as players move around and cause chunks to become activated.  CPU-wise, that first step is pretty trivial versus the following step(s).  Put another way, run --forceUpgrade, and see how quickly it runs for your whole world - that's the sum total of all the savings PLUS the cost of saving those loaded chunks (which always happens when a chunk is unloaded, so no net savings there).

**Comment by mikeprimm** [comment] 2021-12-28 14:51
Re: nether - nether is lit by emitted light (lava mostly), and generating emitted light is not something I'm doing, nor plan to do: it's just too expensive and too likely to not be worth it.  Nether chunks without usable emitted light are gonna be dark - as much as I can do at this point is hide them (treat them as non-existant chunks) but that gets us back to the 'black bands' and other shit, since the transition to 1.18 empty chunk state keeps light, but the first couple steps of a chunk being 'pulled forward' by player activity causes lighting to be discarded (and ultimately recomputed in one of the final steps that only occur when a chunk is closer to a player).

**Closed** 2021-12-29 00:25 UTC
Labels: Bug, Fixed, World Conversion
