### ISSUE TITLE
Bugs in Dynmap 3.2-beta-1-470

### ISSUE THREAD

**Issue by EncryptSL** [webbukkit/dynmap#3405] opened 2021-06-25 21:05 UTC
**Issue Description:** *Problem with reloading and Delete with command dmap mapdelete*

* **Dynmap Version:** *3.2-beta-1-470*
* **Server Version:** 1.17 git-Paper-46*
* **Pastebin of Configuration.txt:**https://paste.hostify.cz/?c44c0058de80cb16#92D7HEMStCzDipVSXCF2rAaBCunQmWtFePh2bp6LWote**
* **Pastebin of crashlogs or other relevant logs:** *There is problem with reloading https://paste.hostify.cz/?d24ca8685e5e7458#4QnEHHhcMunZapuuS4nBptUK3BfsxTgBS846wB5mxNma*
* **Steps to Replicate:** *I write command from console and game, dynmap pause all, and now when rendering is disabled i send dmap mapdelete world_nether:surface and dmap mapdelete world_the_end:surface no working. on dynmap still maps exist and still same when server is restarted*

There is same issue with reloading command but in ver for 1.16.5, still no fixed *https://github.com/webbukkit/dynmap/issues/3377*

**Comment by mikeprimm** [comment] 2021-07-08 21:21
Dupe of #3350

**Closed as completed by mikeprimm** 2021-07-08 21:21 UTC
Labels: Bug Report
