### ISSUE TITLE
DynMap + The Undergarden

### ISSUE THREAD

**Issue by Sniffity** [webbukkit/dynmap#3252] opened 2021-01-21 04:20 UTC
**Issue Description:** *Creating a portal to the Undergarden (The Undergarden Mod) causes a crash, which mentions DynMap (see attached crash report).*

Further detailed description:

- I created a new world for testing, immediately built a portal to the Undergarden and proceeded to crash upon lighting up the portal.
- Removing DynMap: The crash no longer occurs.. However:
**
- I run a server with both DynMap and The Undergarden, and it works just fine, there are no crashes involved when attempting to light up the portal. The two mods are apparently compatible. I do not know what is causing this crash, but whatever it is, does not seem to happen all the time.
**
The crash happens when attempting to light up the portal, upon reloading the world the portal has correctly lit up, however.

* **Dynmap Version:** *Dynmap-3.1-beta5-forge-1.16.3*
* **Server Version:** *forge 1.16.4 - 35.1.13*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*
* Create a new world.
* Create a portal frame for the Undergarden portal (stone bricks).
* Use a "Catalyst" (The Undergarden, item) to light up the portal.
* Crash occurs.

 [X
[Crash_UG.txt](https://github.com/webbukkit/dynmap/files/5846817/Crash_UG.txt)
] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:32
Duplicate of #3231

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:32 UTC
Labels: Fixed, Duplicate
