### ISSUE TITLE
Dynmap plugin rendering issue on 1.13.2

### ISSUE THREAD

**Issue by SajmonOriginal** [webbukkit/dynmap#2466] opened 2019-04-07 14:58 UTC
Hello i have my own server on minecraft and i would like to have rendered dynmap
so i added that plugin with WorldBorder and used **/wb fill** but when i used command **/wb fill** it did this with map: https://i.imgur.com/QvOZJe0.png
Is something wrong with Dynmap or WorldBorder plugin?

Dynmap version: v3.0-beta-3
Worldborder version: 1.9.0
Dynmap link: http://81.0.209.227:25567

Configuration file: https://gist.github.com/SajmonOriginal/dcf78d30d89e889726a3bace48dcb3b4

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:11
Duplicate of #2485

**Closed by FedUpWith-Tech** 2021-08-20 00:11 UTC
Labels: Bug, Render Issues
