### ISSUE TITLE
Issue with Markers and Marker writing

### ISSUE THREAD

**Issue by OmegaShaman** [webbukkit/dynmap#3458] opened 2021-08-18 20:17 UTC
**Issue Description:** *When I restart my server, there seems to be an issue with the Marker writing (especially with signs), as they disappear after the server starts back up again. I don't know the exact cause and I don't know how to replicate it, but I dunno how its happening.

One unique thing I did find was that in my timings report, a LOT of ticks happening for the value "dynmap::Task: org.dynmap.markers.impl.MarkerAPIImpl.DoFileWrites (Single)", so I'm guessing it's having a problem writing the file for the marker position, which then resets after a restart.*

* **Dynmap Version:** *v3.2-beta-2*
* **Server Version:** *Purpur 1.17.1 latest build (almost identical to paper just with some extra configuration)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/55DG5iNn*
* **Server Host (if applicable):** *Dedicated server*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *N/A*
* **Steps to Replicate:** *N/A*

 [ X ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:25
Duplicate of #1936

**Closed as completed by FedUpWith-Tech** 2021-08-20 00:25 UTC
Labels: Duplicate
