### ISSUE TITLE
Loading ssue with Build918

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#4019] opened 2023-09-26 08:34 UTC
```
[10:23:42] [Server thread/ERROR]: Error occurred while enabling dynmap v3.7-SNAPSHOT-918 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistryCustom$Dimension net.minecraft.server.MinecraftServer.aU()'
	at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.getBiomeReg(BukkitVersionHelperSpigot120_2.java:118) ~[Dynmap_3.7-Build918.jar:?]
	at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.getBiomeBaseList(BukkitVersionHelperSpigot120_2.java:131) ~[Dynmap_3.7-Build918.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:852) ~[Dynmap_3.7-Build918.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:937) ~[Dynmap_3.7-Build918.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:23:42] [Server thread/INFO]: [dynmap] Disabling dynmap v3.7-SNAPSHOT-918
[10:23:42] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling dynmap v3.7-SNAPSHOT-918 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.disableCore()" because "this.core" is null
	at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:1095) ~[Dynmap_3.7-Build918.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
We used Build 900 before... switching back to Build 900 solved it for now..

**Comment by ghost** [comment] 2023-09-26 09:37
Got the same issue

**Comment by JurgenKuyper** [comment] 2023-09-26 16:37
3.7 is only for 1.20.2, please use 3.6.x for earlier versions

**Comment by ghost** [comment] 2023-09-27 12:04
[14:03:53] [Server thread/ERROR]: Error occurred while enabling dynmap v3.7-beta-1-917 (Is it up to date?)
java.lang.NoSuchFieldError: o
        at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.initializeBlockStates(BukkitVersionHelperSpigot120_2.java:159) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:934) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3891-Spigot-a0f3d48-46e4ba6]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mikeprimm** [comment] 2023-09-27 21:08
I don't see anything useful here, like which distro, version, and build number you guys are running....  follow the template if you want a response.

**Comment by mikeprimm** [comment] 2023-09-27 21:41
Let's not be mixing things - and let's try to use the damn template, so that the issue has good data, versus trying to figure out what is being run by crawling through the stack trace - if you don't have time to fill out the template, you should hardly expect us to find time to look at your concerns.

Looking at the stack details, the initial problem for was when running Paper 1.20.1 - so adding complains about (looking at the stack, since no proper report there either) Spigot 1.20.2 isn't particularly useful, particularly since the error stack has little in common...

The first issue is a problem that was introduced that caused 1.20 and 1.20.1 on spigot/paper to incorrectly be treated as 1.20.2 - I'm building a fix for that now.

The second issue is one I am unable to reproduce, both with the Spigot build that I built with initially - Spigot 3875-Spigot-17ca32d-5dfd33d (MC: 1.20.2) - nor with a fresh buildtools run about 10 minutes ago (Spigot 3894-Spigot-a0f3d48-851a32c (MC: 1.20.2).   Run a fresh buildtools build and let me know if the problem persists.

**Comment by ropo** [comment] 2023-09-28 03:40
Same problem.

```
[12:32:02] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[12:32:04] [ServerMain/INFO]: Loaded 7 recipes
[12:32:05] [Server thread/INFO]: Starting minecraft server version 1.20.2
[12:32:05] [Server thread/INFO]: Loading properties
[12:32:05] [Server thread/INFO]: This server is running CraftBukkit version 3894-Spigot-a0f3d48-851a32c (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)
[12:32:05] [Server thread/INFO]: Debug logging is disabled
[12:32:05] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:32:05] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:32:05] [Server thread/INFO]: Default game type: SURVIVAL
[12:32:05] [Server thread/INFO]: Generating keypair
[12:32:06] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:32:06] [Server thread/INFO]: Using default channel type
[12:32:06] [Server thread/INFO]: [dynmap] Loading dynmap v3.7-beta-1-917
[12:32:06] [Server thread/INFO]: [dynmap] version=3894-Spigot-a0f3d48-851a32c (MC: 1.20.2)
[12:32:06] [Server thread/INFO]: [dynmap] Mod Support API available
[12:32:06] [Server thread/INFO]: Preparing level "world"
(snip)
[12:32:17] [Server thread/INFO]: Time elapsed: 2220 ms
[12:32:17] [Server thread/INFO]: [dynmap] Enabling dynmap v3.7-beta-1-917
[12:32:17] [Server thread/ERROR]: Error occurred while enabling dynmap v3.7-beta-1-917 (Is it up to date?)
java.lang.NoSuchFieldError: o
	at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.initializeBlockStates(BukkitVersionHelperSpigot120_2.java:159) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:934) ~[?:?]
:
```
what i tried
・BuildTools.jar --rev 1.20.2 from a clean state
・Disable all plugins except Dynmap

**Comment by mikeprimm** [comment] 2023-09-28 04:10
Since folks don't seem to read, I'm closing this issue, as all contributions after the first are for AN UNRELATED PROBLEM, and the original issue, which was specific to 1.20.1, has been fixed in the development builds.   Open another issue, FOLLOW THE TEMPLATE TO PROVIDE INFORMATION, and it'll be considered - I'm running beta-1 on Spigot 1.20.2 3894-Spigot-a0f3d48-851a32c.

**Closed as completed by mikeprimm** 2023-09-28 04:10 UTC
Labels: Bug Report
