### ISSUE TITLE
Dynmap Error

### ISSUE THREAD

**Issue by cocuia** [webbukkit/dynmap#3827] opened 2022-08-15 18:04 UTC
i get this error on my server and Pebblehost have not seen it before so idk what to do, hop somone can help :-D
15.08 17:48:25 [Server] ERROR [dynmap] SQLException: Tile enum error
15.08 17:48:25 [Server] ERROR [dynmap]   ErrorCode: 1064, SQLState=42000
15.08 17:48:25 [Server] ERROR [dynmap]   Message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OFFSET 0 LIMIT 100' at line 1
15.08 17:48:25 [Server] ERROR [dynmap]   ConnectionString: jdbc:mysql://eu01-sql.pebblehost.com:3306/customer_360879_dynmap?allowReconnect=true&autoReconnect=true
15.08 17:48:25 [Server] INFO Full render of 'Openworld' finished.

and on the wep for the map, it stops rendering, and its not done at all

**Comment by masmc05** [comment] 2022-08-15 18:09
try latest version of dynmap, seems like a dublicate of #3806 which was fixed

**Comment by cocuia** [comment] 2022-08-15 19:02
thx a lot @mastermc05

**Comment by FedUpWith-Tech** [comment] 2022-08-19 14:56
Duplicate of #3806

**Closed as completed by FedUpWith-Tech** 2022-08-19 14:56 UTC
Labels: Duplicate
