### ISSUE TITLE
Dynmap disables on startup

### ISSUE THREAD

**Issue by Leomelonseeds** [webbukkit/dynmap#2418] opened 2019-01-14 16:44 UTC
Recently, I have been having an issue whee dynmap disables upon startup. Here is the error:
```
[03:16:31] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-3-160 (Is it up to date?)
java.lang.NullPointerException: null
	at org.dynmap.markers.impl.MarkerSetImpl.loadPersistentData(MarkerSetImpl.java:423) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.loadMarkers(MarkerAPIImpl.java:686) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.initializeMarkerAPI(MarkerAPIImpl.java:375) ~[?:?]
	at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:395) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:851) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[03:16:31] [Server thread/INFO]: [dynmap] Disabling dynmap v3.0-beta-3-160
[03:16:31] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[03:16:31] [Server thread/INFO]: [dynmap] Disabled
```
This happened with no changes to the config file. Deleting markers.yml temporarily fixes the problem until next restart.

If anyone could help it would be appreciated :D

Also sorry the error isnt formatted, I do not know formatting codes on phone.

**Comment by thiefa** [comment] 2019-01-18 20:20
had similar on my issue tracker:
[https://github.com/webbukkit/dynmap/issues/2414](https://github.com/webbukkit/dynmap/issues/2414)

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:26
Duplicate of #2414

**Closed by FedUpWith-Tech** 2020-07-28 22:26 UTC
Labels: Bug, Duplicate, Marker Issues
