### ISSUE TITLE
Cant render

### ISSUE THREAD

**Issue by sfxworks** [webbukkit/dynmap#2379] opened 2018-11-11 01:10 UTC
Using the mysql setting, I get

```

[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face write error - (conn:253491) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face exists error - (conn:253492) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face write error - (conn:253493) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face exists error - (conn:253494) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face write error - (conn:253495) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face exists error - (conn:253496) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:21] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Face write error - (conn:253497) Table 'tbgn.dyn_Faces' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253498) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253499) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253500) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253501) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253502) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:22] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253503) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:23] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253504) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:23] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253505) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:23] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253506) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:23] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253507) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253508) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253509) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253510) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253511) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253512) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:25] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253513) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:25] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253514) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:25] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253515) Table 'tbgn.dyn_Maps' doesn't exist
[20:08:25] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - (conn:253516) Table 'tbgn.dyn_Maps' doesn't exist
```
I tried restarting it hoping it would make the tables. It didnt. So I switched it to flat file and it still would not load.

```
[20:08:44] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'dynmap reload' for source DedicatedServer: mapping values are not allowed here
Caused by: org.dynmap.snakeyaml.scanner.ScannerException: null; mapping values are not allowed here
        at org.dynmap.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:733) ~[ScannerImpl.class:?]
        at org.dynmap.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:305) ~[ScannerImpl.class:?]
        at org.dynmap.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179) ~[ScannerImpl.class:?]
        at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:563) ~[ParserImpl$ParseBlockMappingKey.class:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[ParserImpl.class:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146) ~[ParserImpl.class:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230) ~[Composer.class:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[Composer.class:?]
        at org.dynmap.snakeyaml.composer.Composer.composeDocument(Composer.java:123) ~[Composer.class:?]
        at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:106) ~[Composer.class:?]
        at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121) ~[BaseConstructor.class:?]
        at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:480) ~[Yaml.class:?]
        at org.dynmap.snakeyaml.Yaml.load(Yaml.java:423) ~[Yaml.class:?]
        at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:86) ~[ConfigurationNode.class:?]
        at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:370) ~[DynmapCore.class:?]
        at org.dynmap.forge_1_12_2.DynmapPlugin.onEnable(DynmapPlugin.java:1469) ~[DynmapPlugin.class:?]
        at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.reload(DynmapPlugin.java:537) ~[DynmapPlugin$ForgeServer.class:?]
        at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1413) ~[DynmapCore.class:?]
        at org.dynmap.forge_1_12_2.DynmapPlugin.onCommand(DynmapPlugin.java:1587) ~[DynmapPlugin.class:?]

````

**Comment by Psy-Virus** [comment] 2018-11-11 05:40
Seems like you have wrong characters in a config file... try checking them here: http://www.yamllint.com/

**Comment by Psy-Virus** [comment] 2018-12-31 01:11
Closing this support request as the OP didn't answer and assume it's fixed.

For further Support questions, that are not a bug or if you're not sure about it, please visit https://forums.dynmap.us

Thanks

**Closed by Psy-Virus** 2018-12-31 01:11 UTC
Labels: Answered, Support Question
