### ISSUE TITLE
Suggestion: Keep position when switching map

### ISSUE THREAD

**Issue by ProClifo** [webbukkit/dynmap#3382] opened 2021-06-05 18:20 UTC
I have a suggestion: Can you make an option to enable following position when switching map? When clicking on another map, you'll view the same coordinates as you did in the previous map. The page would always centered around the same coordinates when switching map. Sort of how the zoom level maintains the same.

Together with this, it would be useful to scale the maps. Example: let's say you're viewing the overworld, and you want to view the nether. When clicking the nether world map, your position is divided by 8, so you'll start to view the same position as before according to scale. That will help you see exactly where you will end up if you go through a nether portal at that location.

I can see the config looking like something like this
- contant-position
  Enabled: true
  Scale:
   world: 1
   world_nether: 8
  Exclude:
   world_the_end

I hope I'm explaining it well. The main reason I want this feature is it would work well on [my map](http://map.murucraft.xyz). The Huge World and Tiny World are identical maps in different sizes, and a feature like this would help players see where they are in relation to the other worlds. In my case, the config would look like this:
- constant-position
  Enabled: true
  Scale:
   world: 1
   world_nether: 8
   world_tiny: 4
   world_tiny_nether: 32
  Exclude:
   world_the_end

**Comment by FedUpWith-Tech** [comment] 2021-08-20 03:45
Duplicate of #2716

**Closed as completed by FedUpWith-Tech** 2021-08-20 03:45 UTC
Labels: Duplicate
