### ISSUE TITLE
Chunk Migration Active but not Functional

### ISSUE THREAD

**Issue by LEC1224** [webbukkit/dynmap#2603] opened 2019-09-02 15:53 UTC
Hello! I have an 6 years old survival world currently running the latest build of spigot on Minecraft 1.14! As one could imagine we have generated a lot of areas before 1.13. When spigot upgrades to 1.13 there was something that hindered dynmap from finding the old chunks, resulting in generating only the newly visited areas of the world. The developer found out and fixed the problem with a new migrate-chunks option in 3.0-beta-5-release so I tried it out, thankful and hopeful!

It seems some people have gotten this to work, but I do not. When I start my server I get the "[dynmap] EXPERIMENTAL: chunk migration enabled" out print, but after a fullrender, only newly visited areas show on the map over at http://mc.lecani.se:8123.

Also there are scattered black chunks near edges, but from what I've read that occurs to most people using this option. I know chunk migration is still experimental and don't really expect anyone to have a solution but I want to know if anyone else has a similar problem or if it's just me!

Thanks!
//Carl

**Comment by FedUpWith-Tech** [comment] 2021-12-17 18:20
Duplicate of #2282

**Closed as completed by FedUpWith-Tech** 2021-12-17 18:20 UTC
Labels: Duplicate
