### ISSUE TITLE
Spots on the Dynmap

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2510] opened 2019-06-11 04:17 UTC
With the latest version of Dynmap I get some new spots on the dynmap that I didn't have before. Has anything been changed on the dynmap?

how can I get rid of them? Even re-rendering with radiusrender does not work.

![dynmap1](https://user-images.githubusercontent.com/35557302/59243513-b248ed80-8c10-11e9-9e21-b10a61e11bf0.png)

**Comment by MentalDisorder** [comment] 2019-08-07 11:14
Forceload the chunks or go there and make sure they're generated, then do an update or radius render in the middle of each patch. 
That is if the patches are actually missing chunks and not just missing in some zoom levels. 
Going there and changing blocks might also be an option.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:06
Likely duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 00:06 UTC
Labels: Bug Report, Render Issues
