### ISSUE TITLE
MapChunkCache | loadChunks server freeze guess

### ISSUE THREAD

**Issue by hostkimjang** [webbukkit/dynmap#3312] opened 2021-03-15 05:57 UTC
Issue Description: Server world capacity is large It's over 80gb in the world. It's over 200gb in dynmap rendering. There was a case like this in the past. So after removing the dynmap, this bug didn't happen. So I did rendering again after initializing dynmap. However, these errors have recently started to occur again.

* **Dynmap Version: dynmap version 3.1-beta7
* **Server Version: Paper 1.16.5
* **Pastebin of Configuration.txt: https://pastebin.com/9VtuPsxG
* **Server Host (if applicable): Self Hosting
* **Pastebin of crashlogs or other relevant logs: https://pastebin.com/Yg3C7peD
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment] 2021-08-20 15:24
Duplicate of #3251

**Closed as completed by FedUpWith-Tech** 2021-08-20 15:24 UTC
Labels: Duplicate
