### ISSUE TITLE
dynmap wont load due to marker error? [Fresh Install]

### ISSUE THREAD

**Issue by KhaozFrost** [webbukkit/dynmap#2422] opened 2019-01-16 18:14 UTC
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
```
16.01 13:09:37 [Server] ERROR Error occurred while enabling dynmap v3.0-beta-3-160 (Is it up to date?) 
16.01 13:09:37 [Server] INFO java.lang.NullPointerException: null
16.01 13:09:37 [Server] INFO at org.dynmap.markers.impl.MarkerSetImpl.loadPersistentData(MarkerSetImpl.java:423) ~[Dynmap-3.0-beta-3-spigot(1).jar:?]
16.01 13:09:37 [Server] INFO at org.dynmap.markers.impl.MarkerAPIImpl.loadMarkers(MarkerAPIImpl.java:686) ~[Dynmap-3.0-beta-3-spigot(1).jar:?]
16.01 13:09:37 [Server] INFO at org.dynmap.markers.impl.MarkerAPIImpl.initializeMarkerAPI(MarkerAPIImpl.java:375) ~[Dynmap-3.0-beta-3-spigot(1).jar:?]
16.01 13:09:37 [Server] INFO at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:395) ~[Dynmap-3.0-beta-3-spigot(1).jar:?] 
16.01 13:09:37 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:851) ~[Dynmap-3.0-beta-3-spigot(1).jar:?]
16.01 13:09:37 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
16.01 13:09:37 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

## Reproduce Steps
1. Fresh Install. Error on startup.
2.
...

**Comment by thiefa** [comment] 2019-01-18 20:18
had that when i used my old markers.txt on new dynmaps with markers.txt containing more than 10 or so markers... had to cut them down to below 10 Markers...
see here:
[ #2414](url)

**Comment by KhaozFrost** [comment] 2019-01-19 09:48
> 
> 
> had that when i used my old markers.txt on new dynmaps with markers.txt containing more than 10 or so markers... had to cut them down to below 10 Markers...
> see here:
> [ https://github.com/webbukkit/dynmap/issues/2414](https://github.com/webbukkit/dynmap/issues/2414)
> 
> Crash happend when i had more than 10 Markers in the markers.txt..

I don't have any. thats tha sad part. This is a fresh install

**Comment by Psy-Virus** [comment] 2019-01-26 14:59
The latest Dynmap version is `3.0-SNAPSHOT-164`

http://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar

The one in your crash log is v3.0-beta-3-160

Did you try it with the latest HEAD from 03-Jan-2019 23:32 ?

**Comment by mikeprimm** [comment] 2019-01-27 21:15
Could you guys try latest build?  https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar - should be 166 (or later).  I've updated the YAML library and added some file locking, but otherwise nothing big - I had no luck producing the problem in the first place, so not having too much luck with working a specific fix.  The "JSON-looking" file content is fine - YAML uses {} for empty objects (and newer YAML, YAML 1.2, has actually expanded to be a proper superset of JSON, even though the current code is using YAML 1.0 and my updates bumped us to 1.1).

**Comment by Psy-Virus** [comment] 2019-02-19 21:26
@KhaozFrost,
has this issue been resolved?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:34
Duplicate of #2414

**Closed by FedUpWith-Tech** 2020-07-28 22:34 UTC
Labels: Cannot reproduce, Duplicate
