### ISSUE TITLE
Some marker labels containing apostrophes display &#39; instead

### ISSUE THREAD

**Issue by Dopplizzle** [webbukkit/dynmap#2257] opened 2018-07-08 22:38 UTC
I am not sure when this issue started, I only just noticed it. Some marker labels that contain a standard apostrophe (as in Joe's House) show the HTML character reference on the map instead (as in Joe&# 39;s House) <-- ignore the space between # and 3, I put it in so it would show as intended in this post...

This seems to affect the spawnlabel key in configuration.txt, and non-sign markers in markers.yml (those created with /dmarker add id:<marker-id>...)

Does not seem to affect sign markers.

As a work-around, using an alternate symbol (such as ’ ) displays correctly.

[Edit] Using CraftBukkit version git-Spigot-642f6d2-ab13683 (MC: 1.12.2) and Dynmap v2.6-SNAPSHOT-Dev201807081557

**Comment by DaniDipp** [comment] 2019-08-22 10:54
Apparently these symbols are affected:
```
&: &amp;
': &#39;
+: &#43;
<: &lt;
=: &#61;
>: &gt;
@: &#64;
`: &#96;
```

Example:
![image](https://user-images.githubusercontent.com/17002453/63508212-cc892c80-c4d9-11e9-9a84-6179c1fed849.png)
Created with this command: `/dmarker add set:markers label:"! # $ % & ' ( ) * + , - . / 0 : ; < = > ? @ A [ \ ] ^ _ ` a { | } ~ \"`
Looks like this in the database:
```json
"marker_1": {
	"markup": false,
	"x": -30.0,
	"icon": "default",
	"y": 98.0,
	"dim": "16x16",
	"z": 154.0,
	"label": "! # $ % &amp; &#39; ( ) * &#43; , - . \/ 0 : ; &lt; &#61; &gt; ? &#64; A [ \\ ] ^ _ &#96; a { | } ~ \\"
}
```
And like this in `markers.yml`:
```yaml
marker_1:
    world: DocsWorldTour_nether
    markup: false
    x: -30.0
    icon: default
    y: 98.0
    z: 154.0
    label: '! # $ % & '' ( ) * + , - . / 0 : ; < = > ? @ A [ \ ] ^ _ `
        a { | } ~ \'

**Comment by AugusDogus** [comment] 2019-09-19 00:29
Any update on this?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 22:53
Marking as Duplicate of #2288 since that thread is more inclusive

**Closed by FedUpWith-Tech** 2020-07-28 22:53 UTC
Labels: Bug, Duplicate, Marker Issues
