### ISSUE TITLE
(sorry about the multiple tickets) Html question

### ISSUE THREAD

**Issue by Fyrlex** [webbukkit/dynmap#2157] opened 2017-11-07 00:42 UTC
here is my code for login.html
`<!DOCTYPE HTML>
<html>
<head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon">
<style>
input[type=text], input[type=password] {
    width: 90%;
    padding: 4px 10px;
    margin: 3px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
    text-align: left;
}
.loginregister {
    border: 10px solid black;
}
.signin {
    background-color: #736F6E;
    border: none;
    color: white;
    padding: 7px 9px;
    font-weight: bold;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 14px;
    margin: 4px 2px;
    cursor: pointer;
    font-family: helvetica;
}
.signin:hover {
    opacity: 0.8;
}
div {
    text-align: center;
    font-family: helvetica;
}
tr {
    text-align: center;
    font-size: 14px;
    font-family: helvetica;
}
td {
    text-align: center;
    font-size: 14px;
    font-family: helvetica;
}

b {
    text-align: left;
    font-family: helvetica;
}

label {
    text-align: left;
    font-family: helvetica;
}

h1 {
    font-family: helvetica;
    color: white;
    text-align: center;
    font-size: 30px;
}
h2 {
    font-family: helvetica;
    color: white;
    text-align: center;
}
h3 {
    font-family: helvetica;
    color: white;
    text-align: center;
}
h4 {
    font-family: helvetica;
    color: white;
    text-align: center;
}
h5 {
    font-family: helvetica;
    color: #EF3413;
    text-align: center;
}

p {
    font-family: helvetica;
    text-align: center;
}
</style>
</head>
<head>
	<meta charset="utf-8" />

	<META HTTP-EQUIV = "Pragma" CONTENT="no-cache">
	<title> Fyrlex Server DynMap | Login/Register</title>

	<link rel="stylesheet" type="text/css" href="css/leaflet.css?_=${project.version}-${BUILD_NUMBER}" />
	<link rel="stylesheet" type="text/css" href="css/standalone.css?_=${project.version}-${BUILD_NUMBER}" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/dynmap_style.css?_=${project.version}-${BUILD_NUMBER}" media="screen" />
	<script type="text/javascript" src="standalone/config.js?_=${project.version}-${BUILD_NUMBER}"></script>
	<script type="text/javascript" src="js/jquery-1.11.0.js?_=${project.version}-${BUILD_NUMBER}"></script>
	
	<script type="text/javascript">
		$(document).ready(function() {
			var status = $('#status_message');
			if(window.location.href.indexOf('error=loginfailed') >= 0)
				$('<div/>').text('Login Failed ').appendTo(status);
			if(window.location.href.indexOf('error=verifyfailed') >= 0)
				$('<div/>').text('Password Verification Error ').appendTo(status);
			if(window.location.href.indexOf('error=registerfailed') >= 0)
				$('<div/>').text('Registration failed (invalid passcode) ').appendTo(status);
			$('form')[0].setAttribute('action', config.url.login);
			$('form')[1].setAttribute('action', config.url.register);
			document.forms['login'].elements['j_username'].focus();
		});
		
		$(function(){
            $('form[name=register]').submit(function(){
                $.post($(this).attr('action'), $(this).serialize(), function(json) {
                    if(json.result == 'success')
                    	window.location = 'index.html';
                    else
                    	window.location = 'login.html?error=' + json.result;
                }, 'json');
                return false;
            });
        });

		$(function(){
            $('form[name=login]').submit(function(){
                $.post($(this).attr('action'), $(this).serialize(), function(json) {
                    if(json.result == 'success')
                    	window.location = 'index.html';
                    else
                    	window.location = 'login.html?error=' + json.result;
                }, 'json');
                return false;
            });
        });
	</script>
	
</head>
<body>
<div class='dynmaplogin'>
<h1>Fyrlex Server DynMap | Login</h1>
<div id="status_message" class="statusmessage"></div>
<table class='loginregister'>
<tr><td class='login'>
<FORM METHOD=POST name=login ACTION="up/login">
<p>
Enter your username and password:
<table>
<tr><td>Username:</td><td><input type="text" placeholder="Enter Username" size="48" name="j_username"></td></tr>
<tr><td>Password:</td><td><input type="password" placeholder="Enter Password" size="48" name="j_password"></td></tr>
</table>
<BR>
<input type="submit" class="signin" name="login" value="Login">
<tr>
<td class='register'>
<FORM METHOD=POST name=register ACTION="up/register">
<h5>If you do not have an account you do not belong here!
If you are an [ADMIN] on the Fyrlex server please contact a staff!</h5>
<h5>Staff: Do not share this link to anyone!</h5>
</p>
</form>
</td>
</tr>
</table>
</div>
</body>
</html>
`
and that displays as this when i put it in a .html doc on my desktop
(https://user-images.githubusercontent.com/31144090/32471263-5aa52108-c32a-11e7-81f0-8134904bb671.png)

this is the code when on the dynmap login.html
(https://user-images.githubusercontent.com/31144090/32471280-74124a62-c32a-11e7-8548-97eeeebd4565.png)

im not talking about the background or whatever, its the table, notice the one from my desktop has a thicker outer border, the one from dynmap doesn't have that. it doesn't seem to work on it. it also redirects to this 
(https://user-images.githubusercontent.com/31144090/32473549-fba0686e-c335-11e7-8d51-97b887af4d02.png)
or
(https://user-images.githubusercontent.com/31144090/32473550-fbf05d56-c335-11e7-8f9c-3bf231a9a9b1.png)
when a login is good or bad

any explanation?

**Comment by jwshields** [comment] 2017-11-07 02:49
**This is not a dynmap issue.**

**Comment by Fyrlex** [comment] 2017-11-07 14:04
then what am i doing wrong

**Comment by jwshields** [comment] 2017-11-07 14:39
No idea. But **this is not a dynmap issue.**
The issues you've posted have been issues stemming from things unrelated to dynmap, but dynmap being the thing to cause an error because of them.

**Comment by Fyrlex** [comment] 2017-11-07 14:54
why wouldnt it be part of the html of dynmap, it doesn't support specific code

**Comment by smmmadden** [comment] 2017-11-07 15:12
I think what they are saying is that if you need to change the styles of what gets displayed via a web browser you can do so.  Each browser/version you use may show slightly different because of how they treat JS & CSS content.  Additionally, table borders may not work exactly the same on each browser.  The html provided is only one way of doing it.  Note also that executing the html file from your desktop is not the same as doing so from the internet.  You are going through a web application server and its handling of the content which could also be different than the desktop view.

This goes beyond the scope of Dynmap as the basic process works as it is designed and intended.  So it isn't something that the owners of this plugin would provide support on how to make html work the way you expect it to.  There are thousands of resources out there on doing what you want.  That would be your next thing to do.

Finally, when you are making changes to styles or java scripts and testing, you need to delete your browser cache after each change to ensure you are going to get the latest change made.  All browsers cache and reuse it until told not to.

**Comment by Fyrlex** [comment] 2017-11-07 15:21
where would the browser cache be located, and is that for why the login isnt working?

**Comment by Psy-Virus** [comment] 2017-11-07 16:09
If you want to learn the basics of how the www works, including web-sites/servers/protocols/design/programming, you can start on the link below || go to school || use Google.
https://www.tutorialspoint.com/web_developers_guide/web_basic_concepts.htm

You should seriously close this issue, because it's **NOT** related to Dynmap. @smmmadden wasted precious time to tell you this in a 216 words post. And you ask another **NOT** Dynmap related question.

Sorry for sounding rude but it's intentional.

:-)

**Comment by jwshields** [comment] 2017-11-07 18:53
Dynmap includes all the required html/css/js to get the site going. Including login, php map updates, etc.
You're trying to re-engineer the login page for what purpose?
What we're saying is that this isn't a dynmap issue; Dynmap isn't an "html for beginners" course. The way the repository, and the compiled jar file sit right now, everything should work for the internal site as intended.

You've posted **FOUR (4)** separate issues within the last day, all unrelated to dynmap other than the fact that the errors you are seeing are caused by things stemming from user-error and causing Dynmap to hiccup.
Please exercise common sense, use google to search for errors, try to learn and infer information from what you are given. Spamming a project with non-issues clutters up notifications, emails, and causes others to expend energy to attempt to figure out what's broken when nothing is truly broken.

You should really close the issues you've created, as 1. they're non-issues 2. answers have been given. 3. they're not related to this project.

**Comment by Fyrlex** [comment] 2017-11-07 19:38
I know what HTML is I am just wondering why it was not working for some things. A html file was given, it is part of the plugin. It shouldn't be excused. There are no errors and if this isn't part of the plugin as you say why would I search it up to get a documentation. The thing that is broken is the html.

**Comment by Fyrlex** [comment] 2017-11-07 19:40
and also @Psy-Virus i know what www and that all is so you don't have to pretend to be cool and you wasted your time counting how many words @smmmadden typed so goodbye and thanks for not helping

**Comment by Fyrlex** [comment] 2017-11-07 19:41
my purpose of editing the login page is to make it look better, the default is ugly af

**Closed** 2017-11-07 19:40 UTC

**Comment by Psy-Virus** [comment] 2017-11-07 22:03
> where would the browser cache be located, and is that for why the login isnt working?
> and also @Psy-Virus i know what www and that all is[...]

I see :D
