### ISSUE TITLE
Feature request: expiry on tiles

### ISSUE THREAD

**Issue by gerardvanschip** [webbukkit/dynmap#2231] opened 2018-04-30 02:36 UTC
Dynmap renders tyles of areas explored which is nice as it slowly fills out the map but I was wondering if it would be possible to have that exploration expire. Meaning if people don't go to parts of the map they slowly turn black again.

**Comment by rautamiekka** [comment] 2018-04-30 11:54
An interesting idea.

**Comment by generrosity** [comment] 2018-06-10 22:44
It would be a new thing to track where people have "travelled". There is already a heat map view that tracks changes in chunks (so being active and making changes could highlight a tile).

Unfortunately, I figure its a bit specialist for what people might use, but the code is there and open? And as I said, already tracking changes (maybe have it as a opacity overlay against the existing map?

**Comment by FedUpWith-Tech** [comment] 2020-07-28 19:52
Duplicate of #1934

**Closed by FedUpWith-Tech** 2020-07-28 19:52 UTC
Labels: Duplicate, Feature Request
