### ISSUE TITLE
Full rendered just a part

### ISSUE THREAD

**Issue by elessday** [webbukkit/dynmap#2522] opened 2019-06-19 10:52 UTC
Hi,

I downloaded Dynmap-3.0-beta-4-spigot.jar this morning and try a /dynmap fullrender
But after like 10minutes it just rendered a small part of my map and got this message :

"Full render of 'MYMAP' finished"

It rendered flat, cave and surface, but just a part.

I tried with world name at the end of command, but it did the same. Like 300-500 blocks around worldspawn

I tried this one too, but same thing
/dynmap radiusrender 999999999

I'm on last version of spigot

**Comment by elessday** [comment] 2019-06-19 10:58
> 
> 
> Hi,
> 
> I downloaded Dynmap-3.0-beta-4-spigot.jar this morning and try a /dynmap fullrender
> But after like 10minutes it just rendered a small part of my part after message
> 
> "Full render of 'MYMAP' finished"
> 
> It rendered flat, cave and surface, but just a part.
> 
> I tried with world name at the end of command, but it did the same. Like 300-500 blocks around worldspawn

²

**Comment by WeltensiedlerDE** [comment] 2019-06-21 01:44
Same for me. Using Spigot 1.14.2 with Worldborder Plugin and have a new created world with a border radius of 3000 and only flat. WB Fill and Trim are done, restarting the server and starting fullrender of the world.

[03:40:19] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'Farmwelt' completed - 29101 tiles rendered (156,38 msec/map-tile, 120,17 msec per render)

![Screenshot_1](https://user-images.githubusercontent.com/10679451/59891800-dd80c900-93d6-11e9-9eb9-2453b0faa80d.png)

**Comment by maciejnierzwicki** [comment] 2019-06-22 08:28
Same - Paper 1.14.2

![1](https://user-images.githubusercontent.com/40160115/59961463-54ea5180-94d8-11e9-83ab-995d48881cae.png)

**Comment by WeltensiedlerDE** [comment] 2019-06-23 00:08
This is a version with a world generated with EWG, radius 4500:

![Screenshot_2](https://user-images.githubusercontent.com/10679451/59970002-bf90a100-955b-11e9-992a-fceecef67edd.png)

**Comment by ghost** [comment] 2019-06-24 06:01
I actually ended up having to write the below bash script to iterate over my entire map. First it loaded a section of chunks, then told dynmap to render it, then moved to the next section. World border's fill doesn't work as the map is already generated. Dynmap just doesn't see the chunks, and doesn't recognize it as needing to be rendered.


`#!/bin/bash`
`#10752 / 48 = 224 | 5376 / 48 = 112`
`for xi in {-224..224}; do`
`  for zi in {-112..112}; do`
`    x=$[xi*48]`
`    z=$[zi*48]`
`    /bin/screen -S minecraft -p 0 -X stuff "forceload add $x $z $[x+48] $[z+48]^M"`
`    sleep 2`
`    /bin/screen -S minecraft -p 0 -X stuff "forceload remove all^M"`
`    /bin/screen -S minecraft -p 0 -X stuff "dynmap radiusrender world $[x+24] $[z+24] 24^M"`
`  done`
`  sleep 5`
`done`

You could try something similar.

**Comment by WeltensiedlerDE** [comment] 2019-06-24 06:10
Yes, I notiticed that chunks would be renderer if there are enough blockchanges in it. I will try something simmilar with a self-written plugin.

**Comment by WeltensiedlerDE** [comment] 2019-06-24 13:24
So, I've tried it nowm but it wouldn't work. I've written your code in a plugin and trued it, but it wouldn't update the map. I've tried it manually and teleporting me to an area the map was not renndered and made a manual radiusrender and also not working. It updates, if I make some blockchanges, but not if only the chunks are loaded.

**Comment by GamingTrainer** [comment] 2019-06-27 18:02
1.14.3 fix the issue

**Comment by Teumaat** [comment] 2019-06-28 07:09
This is off topic but I was wondering, why are you using a plugin like WorldBorder? Why would you want to constrain your players like that?

**Comment by WeltensiedlerDE** [comment] 2019-06-28 09:28
Since yesterday i'm using 1.14.3 and have made a worldborder fill again followed by a dynmap fullrender again, but nothing happens. Must it be a completly new generated world to fix this issue in 1.14.3?

Why i'm using Worldborder plugin? Ths is a funny question. Because of saving memory, because of saving time for rendering, because of general administrative reasons.

**Comment by WeltensiedlerDE** [comment] 2019-07-01 14:48
Any progress due to the render errors with 1.14.x ? The Problem appears still with a newly generated world with 1.14.3.

**Comment by ghost** [comment] 2019-07-06 14:16
I also have been experiencing this issue and after investigating the issue I found that PaperLib is outdated.
PaperLib has not yet been updated to 1.14 and that's why WorldBorder was not loading chunks correctly.
In my modified version of WorldBorder I replaced all use of PaperLib with direct paper api access.
The benefit is now all chunks are loaded correctly and map is full on dynmap, but only on PaperSpigot.
My modified version of WorldBorder is only compatible with PaperSpigot, not Spigot or CraftBukkit.
[WorldBorder modified to support Paper 1.14.3 + Dynmap 1.14.3](https://ci.skorrloregaming.com/view/dynmap/)

[Before using modified WorldBorder](https://i.imgur.com/JEJTqeI.png)
[After using modified WorldBorder](https://i.imgur.com/F7wJTcq.png)
The only issue remaining for me is an unknown lighting issue that none of my friends can reproduce.

**Comment by WeltensiedlerDE** [comment] 2019-07-06 14:27
I found another solution. Just fill with worldborder fill with the arguments /wb fill world freq pad true.

The argument true forces worldborder to fill the chunk, wether the chunk was allready loaded or not. This takes much more time to fill an on my vServer with 8GB RAM the server crashes one time at around 90% with a radius of 5000, but the dynmap fullrender works afterwards correctly.

Before:
![59970002-bf90a100-955b-11e9-992a-fceecef67edd](https://user-images.githubusercontent.com/10679451/60757422-af240000-a00a-11e9-9086-fb141e9138f3.png)

After (in the finding progress, I switched from a round to a square border)
![Screenshot_1](https://user-images.githubusercontent.com/10679451/60757446-f8744f80-a00a-11e9-9d09-61657d03a011.png)

**Comment by patrix87** [comment] 2019-07-11 05:17
This is a problem with WorldBorder not properly filling all chunks because it runs out of memory but it thinks all the chunks are created.

**Comment by Charkel** [comment] 2019-07-19 11:06
I am NOT using worldboarders and I cannot finish more than a fraction of the map before it says [INFO]: Full render of 'YOURWORLD' finished.

**Comment by ghost** [comment] 2019-07-19 15:05
Charkel then it's working as expected. Dynmap doesn't load chunks, it only renders what has been loaded before. You need to use WorldBorder for the full render of the map.

**Comment by FedUpWith-Tech** [comment] 2021-08-20 00:08
Duplicate of #2485

**Closed as completed by FedUpWith-Tech** 2021-08-20 00:08 UTC
Labels: Bug Report, Render Issues
