### ISSUE TITLE
Chat messages don't show on the map when using bungeechat

### ISSUE THREAD

**Issue by nmills3** [webbukkit/dynmap#3714] opened 2022-03-12 12:06 UTC
> template is **bold**
> sample data is *italicized*

**Issue Description:** When using the bungeecord plugin bungeechat the functionality of the online map showing messages sent by users no longer works

* **Dynmap Version:** Dynmap-3.4-beta-2-spigot
* **Server Version:** spigot 1.18.2, bungeecord
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *McProHosting, Shockbyte, Selfhosted, etc.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/crashcausedbydynmap*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** create bungeecord proxy, add bungeechat plugin. create spigot server, add dynmap. send messages

 [*] *I have looked at all other issues and this is not a duplicate*  
 [*] *I have been able to replicate this*

**Comment by kosma** [comment] 2022-03-12 14:56
Can you post your bungeechat configuration?

**Comment by nmills3** [comment] 2022-03-12 15:39
https://pastebin.com/HtZj3edH
I did have to clear out the profanity filter list for that pastebin because it wouldn't allow some of the words in that list

**Comment by kosma** [comment] 2022-06-20 12:21
This is expected behavior - once you enable global chat, the chat messages no longer reach the server so the Dynmap plugin can't process them. You can try enabling this:
```
# This passes the chat to the servers the bungee connects to. This will cause doubled
# messages unless you block the chat on these servers!
passToBackendServer=true
```
But then you have to also figure out how to block duplicate messages. Additionally, any messages sent from the web will only appear to players on the same server, not to everyone on the Bungee network. This is a limitation of Bungeecord that's not easily fixable.

**Comment by JurgenKuyper** [comment] 2022-08-11 13:31
closing due to scope and no further input from user.

**Closed as not planned by JurgenKuyper** 2022-08-11 13:31 UTC
Labels: Not Dynmap related, Bug Report
